ScriptML C API: resources/c/include/scriptml/ad5627.h File Reference
ad5627.h File Reference
AD562 DAC device driver.
#include <scriptml/i2c.h>
#include "i2c_regmap.h"
#include "stdio.h"
Macros
#define AD5627_BASE_ADDR 0x0C
#define AD5627_REG_SIZE 3
#define AD5627_COMMAND_WRITE_TO_DAC 0x10
#define AD5627_COMMAND_SW_RESET 0x280001
#define AD5627_COMMAND_PWR_UP_DACS 0x200003
#define AD5627_COMMAND_SET_LDAC 0x300003
#define AD5627_DACA_ONLY 0x0
#define AD5627_DACB_ONLY 0x1
#define AD5627_DACA_AND_DACB 0x7
#define AD5627_MAX_INT_VALUE 65535
#define AD5627_MAX_FLOAT_VALUE_3V3_REF 3.3
#define AD5627_MAX_FLOAT_VALUE_2V5_REF 2.5
Functions
void sml_ad5627_set_level (sml_i2c_regmap_t dev, int channel, int level)
Set the level of output pins on the DAC The device takes a 24 bit word. {COMMAND, MSB, LSB}.
void sml_ad5627_reset (sml_i2c_regmap_t dev)
Perform a power on software reset.
void sml_ad5627_power (sml_i2c_regmap_t dev)
Power up both DACs and activate buffers.
void sml_ad5627_set_ldac (sml_i2c_regmap_t dev)
Set LDAC pin as SW driven.
void sml_ad5627_sw_init (sml_i2c_regmap_t dev)
Initialise the AD5627 to standard start conditions using a SW triggered conversion.
Detailed Description
AD562 DAC device driver.
Support for output level setting on both channels, power down and software reset
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file ad5627.h.
Function Documentation
void sml_ad5627_set_level (sml_i2c_regmap_t dev, int channel, int level)
Set the level of output pins on the DAC The device takes a 24 bit word. {COMMAND, MSB, LSB}.
Parameters
dev Device handle
channel Channel number to set: 0 - DAC A; 1 - DAC B; 7 - Both
level integer containing the 16 bit level
Definition at line 37 of file ad5627.h.
References sml_i2c_reg_write().
 {
     uint8_t reg[AD5627_REG_SIZE];
     reg[0] = (uint8_t) AD5627_COMMAND_WRITE_TO_DAC | channel;
     reg[1] = (uint8_t) ( (level & 0xFF00) >> 8 );
     reg[2] = (uint8_t) ( (level & 0xFF) );
     sml_i2c_reg_write( dev, reg, AD5627_REG_SIZE );
 }
void sml_ad5627_reset (sml_i2c_regmap_t dev)
Perform a power on software reset.
Parameters
dev Device handle
Definition at line 52 of file ad5627.h.
References sml_i2c_reg_write().
Referenced by sml_ad5627_sw_init().
 {
     uint8_t reg[AD5627_REG_SIZE];
     reg[0] = (uint8_t) ( (AD5627_COMMAND_SW_RESET & 0xFF0000) >> 16 );
     reg[1] = (uint8_t) ( (AD5627_COMMAND_SW_RESET & 0x00FF00) >> 8 );
     reg[2] = (uint8_t) ( (AD5627_COMMAND_SW_RESET & 0x0000FF) );
     sml_i2c_reg_write( dev, reg, AD5627_REG_SIZE );
 }
void sml_ad5627_power (sml_i2c_regmap_t dev)
Power up both DACs and activate buffers.
Parameters
dev Device handle
Definition at line 67 of file ad5627.h.
References sml_i2c_reg_write().
Referenced by sml_ad5627_sw_init().
 {
     uint8_t reg[AD5627_REG_SIZE];
     reg[0] = (uint8_t) ( (AD5627_COMMAND_PWR_UP_DACS & 0xFF0000) >> 16 );
     reg[1] = (uint8_t) ( (AD5627_COMMAND_PWR_UP_DACS & 0x00FF00) >> 8 );
     reg[2] = (uint8_t) ( (AD5627_COMMAND_PWR_UP_DACS & 0x0000FF) );
     sml_i2c_reg_write( dev, reg, AD5627_REG_SIZE );
 }
void sml_ad5627_set_ldac (sml_i2c_regmap_t dev)
Set LDAC pin as SW driven.
Parameters
dev Device handle
Definition at line 82 of file ad5627.h.
References sml_i2c_reg_write().
Referenced by sml_ad5627_sw_init().
 {
     uint8_t reg[AD5627_REG_SIZE];
     reg[0] = (uint8_t) ( (AD5627_COMMAND_SET_LDAC & 0xFF0000) >> 16 );
     reg[1] = (uint8_t) ( (AD5627_COMMAND_SET_LDAC & 0x00FF00) >> 8 );
     reg[2] = (uint8_t) ( (AD5627_COMMAND_SET_LDAC & 0x0000FF) );
     sml_i2c_reg_write( dev, reg, AD5627_REG_SIZE );
 }
void sml_ad5627_sw_init (sml_i2c_regmap_t dev)
Initialise the AD5627 to standard start conditions using a SW triggered conversion.
Parameters
dev Device handle
Definition at line 98 of file ad5627.h.
References sml_ad5627_power(), sml_ad5627_reset(), and sml_ad5627_set_ldac().
 {
     /* Software reset */
     sml_ad5627_reset( dev);
     /* Power up DACs */
     sml_ad5627_power(dev);
     /* Set LDAC register to indicate software conversion trigger */
     sml_ad5627_set_ldac(dev);
 }