ScriptML C API: resources/c/include/scriptml/ad7091.h File Reference
ad7091.h File Reference
Quad channel 12 bit ADC.
#include <i2c_regmap.h>
Data Structures
struct sml_ad7091_t
Macros
#define SML_AD7091_BASE_ADDR 0x22
#define SML_AD7091_CONV_RES_ALERT_FLAG_NO_ALERT 0x0
#define SML_AD7091_CONV_RES_ALERT_FLAG_ALERT 0x1
#define SML_AD7091_CONV_RES_CHAN_CH0 0x0
#define SML_AD7091_CONV_RES_CHAN_CH1 0x1
#define SML_AD7091_CONV_RES_CHAN_CH2 0x2
#define SML_AD7091_CONV_RES_CHAN_CH3 0x3
#define SML_AD7091_CHANNEL_REGISTER_CH0_DISABLED 0x0
#define SML_AD7091_CHANNEL_REGISTER_CH0_ENABLED 0x1
#define SML_AD7091_CHANNEL_REGISTER_CH1_DISABLED 0x0
#define SML_AD7091_CHANNEL_REGISTER_CH1_ENABLED 0x1
#define SML_AD7091_CHANNEL_REGISTER_CH2_DISABLED 0x0
#define SML_AD7091_CHANNEL_REGISTER_CH2_ENABLED 0x1
#define SML_AD7091_CHANNEL_REGISTER_CH3_DISABLED 0x0
#define SML_AD7091_CHANNEL_REGISTER_CH3_ENABLED 0x1
#define SML_AD7091_CONF_REG_P_DOWN_MODE_0 0x0
#define SML_AD7091_CONF_REG_P_DOWN_MODE_1 0x1
#define SML_AD7091_CONF_REG_P_DOWN_MODE_2 0x2
#define SML_AD7091_CONF_REG_P_DOWN_MODE_3 0x3
#define SML_AD7091_CONF_REG_GPO1_DRIVE_0 0x0
#define SML_AD7091_CONF_REG_GPO1_DRIVE_1 0x1
#define SML_AD7091_CONF_REG_ALERT_POL_OR_GPO0_PIN_ACTIVE_LOW 0x0
#define SML_AD7091_CONF_REG_ALERT_POL_OR_GPO0_PIN_ACTIVE_HIGH 0x1
#define SML_AD7091_CONF_REG_ALERT_EN_OR_GPO0_USED_FOR_GPO0 0x0
#define SML_AD7091_CONF_REG_ALERT_EN_OR_GPO0_USED_FOR_ALERT 0x1
#define SML_AD7091_CONF_REG_BUSY_NOT_USED_FOR_BUSY 0x0
#define SML_AD7091_CONF_REG_BUSY_USED_FOR_BUSY 0x1
#define SML_AD7091_CONF_REG_CYCLE_TIMER_100_US 0x0
#define SML_AD7091_CONF_REG_CYCLE_TIMER_200_US 0x1
#define SML_AD7091_CONF_REG_CYCLE_TIMER_400_US 0x2
#define SML_AD7091_CONF_REG_CYCLE_TIMER_800_US 0x3
#define SML_AD7091_CONF_REG_AUTO_MODE_SAMP_OR_CMD_MODE 0x0
#define SML_AD7091_CONF_REG_AUTO_MODE_AUTO_OR_SAMP_MODE 0x1
#define SML_AD7091_CONF_REG_SRST_DONT_ACTIVATE 0x0
#define SML_AD7091_CONF_REG_SRST_ACTIVATE 0x1
#define SML_AD7091_CONF_REG_CMD_SAMP_OR_AUTO_MODE 0x0
#define SML_AD7091_CONF_REG_CMD_CMD_OR_SAMP_MODE 0x1
#define SML_AD7091_CONF_REG_FLTR_ENABLE 0x0
#define SML_AD7091_CONF_REG_FLTR_BYPASS 0x1
#define SML_AD7091_CONF_REG_GPO2_DRIVE_0 0x0
#define SML_AD7091_CONF_REG_GPO2_DRIVE_1 0x1
#define SML_AD7091_CONF_REG_ALERT_DRIVE_TYPE_OPEN_DRAIN 0x0
#define SML_AD7091_CONF_REG_ALERT_DRIVE_TYPE_CMOS 0x1
Functions
sml_ad7091_t sml_ad7091_create (sml_i2c_t i2c)
Create device driver instance.
void sml_ad7091_get_conv_res (sml_ad7091_t dev, int *result, int *alert_flag, int *chan)
Get Conversion result register.
void sml_ad7091_set_channel_register (sml_ad7091_t dev, int ch0, int ch1, int ch2, int ch3)
Set Channel Register.
void sml_ad7091_get_channel_register (sml_ad7091_t dev, int *ch0, int *ch1, int *ch2, int *ch3)
Get Channel Register.
void sml_ad7091_set_conf_reg (sml_ad7091_t dev, int p_down, int gpo1, int alert_pol_or_gpo0, int alert_en_or_gpo0, int busy, int cycle_timer, int auto_mode, int srst, int cmd, int fltr, int gpo2, int alert_drive_type)
Set Configuration register.
void sml_ad7091_get_conf_reg (sml_ad7091_t dev, int *p_down, int *gpo1, int *alert_pol_or_gpo0, int *alert_en_or_gpo0, int *busy, int *cycle_timer, int *auto_mode, int *srst, int *cmd, int *fltr, int *gpo2, int *alert_drive_type)
Get Configuration register.
void sml_ad7091_set_ch0_low_limit (sml_ad7091_t dev, uint16_t ch0_low_limit)
Set Channel 0 low limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch0_low_limit (sml_ad7091_t dev)
Get Channel 0 low limit register, only 12 least significant bits.
void sml_ad7091_set_ch0_high_limit (sml_ad7091_t dev, uint16_t ch0_high_limit)
Set Channel 0 high limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch0_high_limit (sml_ad7091_t dev)
Get Channel 0 high limit register, only 12 least significant bits.
void sml_ad7091_set_ch0_hyst_limit (sml_ad7091_t dev, uint16_t ch0_hyst_limit)
Set Channel 0 hysteresis register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch0_hyst_limit (sml_ad7091_t dev)
Get Channel 0 hysteresis register, only 12 least significant bits.
void sml_ad7091_set_ch1_low_limit (sml_ad7091_t dev, uint16_t ch1_low_limit)
Set Channel 1 low limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch1_low_limit (sml_ad7091_t dev)
Get Channel 1 low limit register, only 12 least significant bits.
void sml_ad7091_set_ch1_high_limit (sml_ad7091_t dev, uint16_t ch1_high_limit)
Set Channel 1 high limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch1_high_limit (sml_ad7091_t dev)
Get Channel 1 high limit register, only 12 least significant bits.
void sml_ad7091_set_ch1_hyst_limit (sml_ad7091_t dev, uint16_t ch1_hyst_limit)
Set Channel 1 hysteresis register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch1_hyst_limit (sml_ad7091_t dev)
Get Channel 1 hysteresis register, only 12 least significant bits.
void sml_ad7091_set_ch2_low_limit (sml_ad7091_t dev, uint16_t ch2_low_limit)
Set Channel 2 low limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch2_low_limit (sml_ad7091_t dev)
Get Channel 2 low limit register, only 12 least significant bits.
void sml_ad7091_set_ch2_high_limit (sml_ad7091_t dev, uint16_t ch2_high_limit)
Set Channel 2 high limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch2_high_limit (sml_ad7091_t dev)
Get Channel 2 high limit register, only 12 least significant bits.
void sml_ad7091_set_ch2_hyst_limit (sml_ad7091_t dev, uint16_t ch2_hyst_limit)
Set Channel 2 hysteresis register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch2_hyst_limit (sml_ad7091_t dev)
Get Channel 2 hysteresis register, only 12 least significant bits.
void sml_ad7091_set_ch3_low_limit (sml_ad7091_t dev, uint16_t ch3_low_limit)
Set Channel 3 low limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch3_low_limit (sml_ad7091_t dev)
Get Channel 3 low limit register, only 12 least significant bits.
void sml_ad7091_set_ch3_high_limit (sml_ad7091_t dev, uint16_t ch3_high_limit)
Set Channel 3 high limit register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch3_high_limit (sml_ad7091_t dev)
Get Channel 3 high limit register, only 12 least significant bits.
void sml_ad7091_set_ch3_hyst_limit (sml_ad7091_t dev, uint16_t ch3_hyst_limit)
Set Channel 3 hysteresis register, only 12 least significant bits.
uint16_t sml_ad7091_get_ch3_hyst_limit (sml_ad7091_t dev)
Get Channel 3 hysteresis register, only 12 least significant bits.
Detailed Description
Quad channel 12 bit ADC.
The ADI AD7091R quad channel ADC with 12 bits resolution, accessed via the I2C interface.
Auto-generated 30 April 2018; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file ad7091.h.
Data Structure Documentation
struct sml_ad7091_t
Definition at line 65 of file ad7091.h.
Data Fields
sml_i2c_regmap_t iic
Function Documentation
sml_ad7091_t sml_ad7091_create (sml_i2c_t i2c)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
Returns
Device handle
Definition at line 76 of file ad7091.h.
References sml_i2c_regmap_create().
 {
     sml_ad7091_t dev;
     dev.iic = sml_i2c_regmap_create( i2c, SML_AD7091_BASE_ADDR, 0x100, 0 );
     return dev;
 }
void sml_ad7091_get_conv_res (sml_ad7091_t dev, int * result, int * alert_flag, int * chan)
Get Conversion result register.
Parameters
dev The device handle
result pointer to 12-bit conversion result
alert_flag pointer to Alert flag bit
chan pointer to Analog input channel
Definition at line 91 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint16_t _value;
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x0, 2 );
     _value = ((int)(_bytes[0]) << 8) | (int)(_bytes[1]);
     *result = _value & 0xfff;
     *alert_flag = (_value >> 12) & 0x1;
     *chan = (_value >> 13) & 0x3;
 }
void sml_ad7091_set_channel_register (sml_ad7091_t dev, int ch0, int ch1, int ch2, int ch3)
Set Channel Register.
Parameters
dev The device handle
ch0 Channel 0 status
ch1 Channel 1 status
ch2 Channel 2 status
ch3 Channel 3 status
Definition at line 111 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = (ch0 & 0x1) | ((ch1 & 0x1) << 1) | ((ch2 & 0x1) << 2) | ((ch3 & 0x1) << 3);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1, 1 );
 }
void sml_ad7091_get_channel_register (sml_ad7091_t dev, int * ch0, int * ch1, int * ch2, int * ch3)
Get Channel Register.
Parameters
dev The device handle
ch0 pointer to Channel 0 status bit
ch1 pointer to Channel 1 status bit
ch2 pointer to Channel 2 status bit
ch3 pointer to Channel 3 status bit
Definition at line 127 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x1, 1 );
     *ch0 = _bytes[0] & 0x1;
     *ch1 = (_bytes[0] >> 1) & 0x1;
     *ch2 = (_bytes[0] >> 2) & 0x1;
     *ch3 = (_bytes[0] >> 3) & 0x1;
 }
void sml_ad7091_set_conf_reg (sml_ad7091_t dev, int p_down, int gpo1, int alert_pol_or_gpo0, int alert_en_or_gpo0, int busy, int cycle_timer, int auto_mode, int srst, int cmd, int fltr, int gpo2, int alert_drive_type)
Set Configuration register.
Parameters
dev The device handle
p_down Power down mode
gpo1 Value at GPO 1
alert_pol_or_gpo0 Polarity of ALERT/BUSY/GPO 0 pin if (ALERT_EN is 1) or value at GPO 0
alert_en_or_gpo0 Enable alert or GPO0
busy Alert busy pin indicates busy
cycle_timer Timer value for Autocycle mode
auto_mode Autocycle mode (depends on CMD mode field)
srst Software Reset
cmd command mode (depends on Auto mode field)
fltr Enable glitch filter
gpo2 Value at GPO2
alert_drive_type Alert gpo 0 drive type
Definition at line 154 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint16_t _value;
     uint8_t _bytes[2];
     _value = (p_down & 0x3) | ((gpo1 & 0x1) << 2) | ((alert_pol_or_gpo0 & 0x1) << 3) | ((alert_en_or_gpo0 & 0x1) << 4) | ((busy & 0x1) << 5) | ((cycle_timer & 0x3) << 6) | ((auto_mode & 0x1) << 8) | ((srst & 0x1) << 9) | ((cmd & 0x1) << 10) | ((fltr & 0x1) << 11) | ((gpo2 & 0x1) << 14) | ((alert_drive_type & 0x1) << 15);
     _bytes[0] = (_value >> 8) & 0xff;
     _bytes[1] = _value & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x2, 2 );
 }
void sml_ad7091_get_conf_reg (sml_ad7091_t dev, int * p_down, int * gpo1, int * alert_pol_or_gpo0, int * alert_en_or_gpo0, int * busy, int * cycle_timer, int * auto_mode, int * srst, int * cmd, int * fltr, int * gpo2, int * alert_drive_type)
Get Configuration register.
Parameters
dev The device handle
p_down pointer to Power down mode
gpo1 pointer to Value at GPO 1 bit
alert_pol_or_gpo0 pointer to Polarity of ALERT/BUSY/GPO 0 pin if (ALERT_EN is 1) or value at GPO 0 bit
alert_en_or_gpo0 pointer to Enable alert or GPO0 bit
busy pointer to Alert busy pin indicates busy bit
cycle_timer pointer to Timer value for Autocycle mode
auto_mode pointer to Autocycle mode (depends on CMD mode field) bit
srst pointer to Software Reset bit
cmd pointer to command mode (depends on Auto mode field) bit
fltr pointer to Enable glitch filter bit
gpo2 pointer to Value at GPO2 bit
alert_drive_type pointer to Alert gpo 0 drive type bit
Definition at line 181 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint16_t _value;
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x2, 2 );
     _value = ((int)(_bytes[0]) << 8) | (int)(_bytes[1]);
     *p_down = _value & 0x3;
     *gpo1 = (_value >> 2) & 0x1;
     *alert_pol_or_gpo0 = (_value >> 3) & 0x1;
     *alert_en_or_gpo0 = (_value >> 4) & 0x1;
     *busy = (_value >> 5) & 0x1;
     *cycle_timer = (_value >> 6) & 0x3;
     *auto_mode = (_value >> 8) & 0x1;
     *srst = (_value >> 9) & 0x1;
     *cmd = (_value >> 10) & 0x1;
     *fltr = (_value >> 11) & 0x1;
     *gpo2 = (_value >> 14) & 0x1;
     *alert_drive_type = (_value >> 15) & 0x1;
 }
void sml_ad7091_set_ch0_low_limit (sml_ad7091_t dev, uint16_t ch0_low_limit)
Set Channel 0 low limit register, only 12 least significant bits.
Parameters
dev The device handle
ch0_low_limit Channel 0 low limit register, only 12 least significant bits
Definition at line 207 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch0_low_limit >> 8) & 0xff;
     _bytes[1] = ch0_low_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x4, 2 );
 }
uint16_t sml_ad7091_get_ch0_low_limit (sml_ad7091_t dev)
Get Channel 0 low limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 0 low limit register, only 12 least significant bits
Definition at line 221 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x4, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch0_high_limit (sml_ad7091_t dev, uint16_t ch0_high_limit)
Set Channel 0 high limit register, only 12 least significant bits.
Parameters
dev The device handle
ch0_high_limit Channel 0 high limit register, only 12 least significant bits
Definition at line 234 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch0_high_limit >> 8) & 0xff;
     _bytes[1] = ch0_high_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x5, 2 );
 }
uint16_t sml_ad7091_get_ch0_high_limit (sml_ad7091_t dev)
Get Channel 0 high limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 0 high limit register, only 12 least significant bits
Definition at line 248 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x5, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch0_hyst_limit (sml_ad7091_t dev, uint16_t ch0_hyst_limit)
Set Channel 0 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
ch0_hyst_limit Channel 0 hysteresis register, only 12 least significant bits
Definition at line 261 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch0_hyst_limit >> 8) & 0xff;
     _bytes[1] = ch0_hyst_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x6, 2 );
 }
uint16_t sml_ad7091_get_ch0_hyst_limit (sml_ad7091_t dev)
Get Channel 0 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 0 hysteresis register, only 12 least significant bits
Definition at line 275 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x6, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch1_low_limit (sml_ad7091_t dev, uint16_t ch1_low_limit)
Set Channel 1 low limit register, only 12 least significant bits.
Parameters
dev The device handle
ch1_low_limit Channel 1 low limit register, only 12 least significant bits
Definition at line 288 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch1_low_limit >> 8) & 0xff;
     _bytes[1] = ch1_low_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x7, 2 );
 }
uint16_t sml_ad7091_get_ch1_low_limit (sml_ad7091_t dev)
Get Channel 1 low limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 1 low limit register, only 12 least significant bits
Definition at line 302 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x7, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch1_high_limit (sml_ad7091_t dev, uint16_t ch1_high_limit)
Set Channel 1 high limit register, only 12 least significant bits.
Parameters
dev The device handle
ch1_high_limit Channel 1 high limit register, only 12 least significant bits
Definition at line 315 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch1_high_limit >> 8) & 0xff;
     _bytes[1] = ch1_high_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x8, 2 );
 }
uint16_t sml_ad7091_get_ch1_high_limit (sml_ad7091_t dev)
Get Channel 1 high limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 1 high limit register, only 12 least significant bits
Definition at line 329 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x8, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch1_hyst_limit (sml_ad7091_t dev, uint16_t ch1_hyst_limit)
Set Channel 1 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
ch1_hyst_limit Channel 1 hysteresis register, only 12 least significant bits
Definition at line 342 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch1_hyst_limit >> 8) & 0xff;
     _bytes[1] = ch1_hyst_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x9, 2 );
 }
uint16_t sml_ad7091_get_ch1_hyst_limit (sml_ad7091_t dev)
Get Channel 1 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 1 hysteresis register, only 12 least significant bits
Definition at line 356 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x9, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch2_low_limit (sml_ad7091_t dev, uint16_t ch2_low_limit)
Set Channel 2 low limit register, only 12 least significant bits.
Parameters
dev The device handle
ch2_low_limit Channel 2 low limit register, only 12 least significant bits
Definition at line 369 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch2_low_limit >> 8) & 0xff;
     _bytes[1] = ch2_low_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xa, 2 );
 }
uint16_t sml_ad7091_get_ch2_low_limit (sml_ad7091_t dev)
Get Channel 2 low limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 2 low limit register, only 12 least significant bits
Definition at line 383 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xa, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch2_high_limit (sml_ad7091_t dev, uint16_t ch2_high_limit)
Set Channel 2 high limit register, only 12 least significant bits.
Parameters
dev The device handle
ch2_high_limit Channel 2 high limit register, only 12 least significant bits
Definition at line 396 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch2_high_limit >> 8) & 0xff;
     _bytes[1] = ch2_high_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xb, 2 );
 }
uint16_t sml_ad7091_get_ch2_high_limit (sml_ad7091_t dev)
Get Channel 2 high limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 2 high limit register, only 12 least significant bits
Definition at line 410 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xb, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch2_hyst_limit (sml_ad7091_t dev, uint16_t ch2_hyst_limit)
Set Channel 2 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
ch2_hyst_limit Channel 2 hysteresis register, only 12 least significant bits
Definition at line 423 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch2_hyst_limit >> 8) & 0xff;
     _bytes[1] = ch2_hyst_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xc, 2 );
 }
uint16_t sml_ad7091_get_ch2_hyst_limit (sml_ad7091_t dev)
Get Channel 2 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 2 hysteresis register, only 12 least significant bits
Definition at line 437 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xc, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch3_low_limit (sml_ad7091_t dev, uint16_t ch3_low_limit)
Set Channel 3 low limit register, only 12 least significant bits.
Parameters
dev The device handle
ch3_low_limit Channel 3 low limit register, only 12 least significant bits
Definition at line 450 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch3_low_limit >> 8) & 0xff;
     _bytes[1] = ch3_low_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xd, 2 );
 }
uint16_t sml_ad7091_get_ch3_low_limit (sml_ad7091_t dev)
Get Channel 3 low limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 3 low limit register, only 12 least significant bits
Definition at line 464 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xd, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch3_high_limit (sml_ad7091_t dev, uint16_t ch3_high_limit)
Set Channel 3 high limit register, only 12 least significant bits.
Parameters
dev The device handle
ch3_high_limit Channel 3 high limit register, only 12 least significant bits
Definition at line 477 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch3_high_limit >> 8) & 0xff;
     _bytes[1] = ch3_high_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xe, 2 );
 }
uint16_t sml_ad7091_get_ch3_high_limit (sml_ad7091_t dev)
Get Channel 3 high limit register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 3 high limit register, only 12 least significant bits
Definition at line 491 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xe, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_ad7091_set_ch3_hyst_limit (sml_ad7091_t dev, uint16_t ch3_hyst_limit)
Set Channel 3 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
ch3_hyst_limit Channel 3 hysteresis register, only 12 least significant bits
Definition at line 504 of file ad7091.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = (ch3_hyst_limit >> 8) & 0xff;
     _bytes[1] = ch3_hyst_limit & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xf, 2 );
 }
uint16_t sml_ad7091_get_ch3_hyst_limit (sml_ad7091_t dev)
Get Channel 3 hysteresis register, only 12 least significant bits.
Parameters
dev The device handle
Returns
Channel 3 hysteresis register, only 12 least significant bits
Definition at line 518 of file ad7091.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xf, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }