ScriptML C API: resources/c/include/scriptml/bluetooth.h File Reference
bluetooth.h File Reference
ScriptML bluetooth support.
#include <assert.h>
#include <string.h>
#include <stdio.h>
Functions
char * sml_bluetooth_get_paired ()
Determine which bluetooth devices are paired.
char * sml_bluetooth_scan (int timeout)
Scan for bluetooth devices.
int sml_bluetooth_pair (char *mac_address, char *pin_code, char *error_message)
Pair a bluetooth device.
void sml_bluetooth_remove (char *mac_address)
Remove a bluetooth device.
int sml_bluetooth_serial_bind (char *mac_address, char *device, char *error_message)
Bind a bluetooth serial port.
void sml_bluetooth_serial_release (char *mac_address)
Release a bluetooth serial port.
Detailed Description
ScriptML bluetooth support.
API functions for scanning and pairing bluetooth devices.
API functions for binding bluetooth serial ports
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file bluetooth.h.
Function Documentation
char* sml_bluetooth_get_paired ()
Determine which bluetooth devices are paired.
This is the list of configured paired devices regardless of whether they are detectable or not. Output format is
<mac address>="">[/<channel>],<mac address>="">[/<channel>]...
Where a device has been bound as a serial port, the channel number is given after a forward slash.
Returns
A string continaing the devices
Definition at line 36 of file bluetooth.h.
References assert.
 {
     ___Send(request:"Bluetooth_GetPaired", client_handle:-1, str_payload:"", int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     assert( l[0]=="Value" );
     return l[1];
 }
char* sml_bluetooth_scan (int timeout)
Scan for bluetooth devices.
Checks for devices that can be detected by the bluetooth hardware Output format is
<mac address>="">/,<mac address>="">/...
A 20s timeout is usually sufficient.
Parameters
timeout The amount of time to spend scanning, in seconds.
Returns
A string continaing the devices
Definition at line 58 of file bluetooth.h.
References assert.
 {
     ___Send(request:"Bluetooth_Scan", client_handle:-1, str_payload:"", int_payload:___ISeq(timeout), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     assert( l[0]=="Value" );
     return l[1];
 }
int sml_bluetooth_pair (char * mac_address, char * pin_code, char * error_message)
Pair a bluetooth device.
Pair the device. This is a configuration change that persists across power cycles. Note that the device must have been found by a scan operation since the last power cycle or remove operation.
Mac address is of the form xx:xx:xx:xx:xx:xx
Parameters
mac_address MAC address of the bluetooth device to pair
pin_code PIN code of the device or "" id none required
error_message Optional buffer to receive the text of any error messages
Returns
0 if successful
Definition at line 80 of file bluetooth.h.
References i2c_msg::buf, sprintf(), and strcpy().
 {
     char buf[200];
     sprintf(buf, "%s/%s", mac_address, pin_code);
     ___Send(request:"Bluetooth_Pair", client_handle:-1, str_payload:buf, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     if( l[0]=="Fail" )
     {
         if( error_message )
             strcpy( error_message, l[2] ); // failure
         return -1;
     }
     return 0;
 }
void sml_bluetooth_remove (char * mac_address)
Remove a bluetooth device.
Undoes the action of scan and pair (i.e. unpair and forget).
Mac address is of the form xx:xx:xx:xx:xx:xx
Parameters
mac_address MAC address of the bluetooth device to remove
Definition at line 105 of file bluetooth.h.
References assert.
 {
     ___Send(request:"Bluetooth_Remove", client_handle:-1, str_payload:mac_address, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     assert( l[0]=="OK" );
 }
int sml_bluetooth_serial_bind (char * mac_address, char * device, char * error_message)
Bind a bluetooth serial port.
Bind the bluetooth serial port to a node in /dev so that it can be used for serial communications. This does not persist across power cycles. Note that the device must have been successfully paired and be detectable.
Mac address is of the form xx:xx:xx:xx:xx:xx
Device path is of the form /dev/<device>
Parameters
mac_address MAC address of the bluetooth serial port to bind
device Optional buffer to receive the device path
error_message Optional buffer to receive the text of any error messages
Returns
0 if successful
Definition at line 128 of file bluetooth.h.
References sprintf(), and strcpy().
 {
     ___Send(request:"Bluetooth_Bind", client_handle:-1, str_payload:mac_address, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     if( l[0]=="Fail" )
     {
         if( error_message )
             strcpy( error_message, l[2] );
         return -1;
     }
     if( device )
         sprintf( device, "/dev/rfcomm%d", l[1] );
     return 0;
 }
void sml_bluetooth_serial_release (char * mac_address)
Release a bluetooth serial port.
Undoes the action of bind (i.e. unbind).
Mac address is of the form xx:xx:xx:xx:xx:xx
Parameters
mac_address MAC address of the bluetooth device to release
Definition at line 153 of file bluetooth.h.
References assert.
 {
     ___Send(request:"Bluetooth_Release", client_handle:-1, str_payload:mac_address, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     assert( l[0]=="OK" );
 }