ScriptML C API: resources/c/include/scriptml/coroutines.h File Reference
coroutines.h File Reference
Direct access to ScriptML coroutines.
Macros
#define MAIN_COROUTINE_ID 0
Id of the main coroutine.
#define sml_coroutine_wait(TEST) ___Wait(test:(TEST))
Wait for the given expression to evaluate true.
Functions
typedef ___CoroutineType_T ()*sml_coroutine_handle_t
Coroutine handle.
sml_coroutine_handle_t sml_coroutine_create_0 (void(*entrypoint)())
Create a coroutine with 0 arguments.
sml_coroutine_handle_t sml_coroutine_create_1 (void(*entrypoint)(___NULL_T() arg1), ___NULL_T() arg1)
Create a coroutine with 1 argument.
sml_coroutine_handle_t sml_coroutine_create_2 (void(*entrypoint)(___NULL_T() arg1, ___NULL_T() arg2), ___NULL_T() arg1, ___NULL_T() arg2)
Create a coroutine with 2 arguments.
___NULL_T () sml_coroutine_join(sml_coroutine_handle_t coroutine)
Wait for a coroutine to exit.
int sml_coroutine_get_id (sml_coroutine_handle_t coroutine)
Get id of a coroutine.
void sml_coroutine_yield ()
Yield the current coroutine.
void sml_coroutine_exit (___NULL_T() result)
Exit and delete the current coroutine.
int sml_coroutine_get_current_id ()
Get id of currently running coroutine.
Detailed Description
Direct access to ScriptML coroutines.
Coroutines behave like simple and lightweight threads. However, a coroutine must call sml_coroutine_yield() or sml_coroutine_wait() regularly in order to allow other coroutines to run.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file coroutines.h.
Macro Definition Documentation
#define sml_coroutine_wait (TEST) ___Wait(test:(TEST))
Wait for the given expression to evaluate true.
Parameters
TEST Expression to wait for (evaluated multiple times; not side-effect-safe)
Note: a preprocessor macro is used to permit the Wait node to evaluate TEST more than once (and in future to access the spinless-wait feature).
Definition at line 106 of file coroutines.h.
Referenced by pthread_cond_wait(), pthread_mutex_lock(), pthread_rwlock_rdlock(), pthread_rwlock_wrlock(), and sem_wait().
Function Documentation
sml_coroutine_handle_t sml_coroutine_create_0 (void(*)() entrypoint)
Create a coroutine with 0 arguments.
Parameters
entrypoint Pointer to the entry point function
Returns
Coroutine handle
Definition at line 32 of file coroutines.h.
 {
     return &___Construct( object_type:___CoroutineType(), args_list:___ArgsList(args:___ISeq(*entrypoint)), args_map:___ArgsMap(args:___IMap()), variadic_arg:___NULL() );
 }
sml_coroutine_handle_t sml_coroutine_create_1 (void(*)(___NULL_T() arg1) entrypoint, ___NULL_T() arg1)
Create a coroutine with 1 argument.
Parameters
entrypoint Pointer to the entry point function
arg1 First argument to entry point function (any type)
Returns
Coroutine handle
Definition at line 44 of file coroutines.h.
Referenced by pthread_create().
 {
     return &___Construct( object_type:___CoroutineType(), args_list:___ArgsList(args:___ISeq(*entrypoint, arg1)), args_map:___ArgsMap(args:___IMap()), variadic_arg:___NULL() );
 }
sml_coroutine_handle_t sml_coroutine_create_2 (void(*)(___NULL_T() arg1, ___NULL_T() arg2) entrypoint, ___NULL_T() arg1, ___NULL_T() arg2)
Create a coroutine with 2 arguments.
Parameters
entrypoint Pointer to the entry point function
arg1 First argument to entry point function (any type)
arg2 Second argument to entry point function (any type)
Returns
Coroutine handle
Definition at line 58 of file coroutines.h.
 {
     return &___Construct( object_type:___CoroutineType(), args_list:___ArgsList(args:___ISeq(*entrypoint, arg1, arg2)), args_map:___ArgsMap(args:___IMap()), variadic_arg:___NULL() );
 }
___NULL_T ()
Wait for a coroutine to exit.
Parameters
coroutine Handle of coroutine to wait for
Returns
Coroutine's result value
Definition at line 70 of file coroutines.h.
 {
     ___Wait( test:___IsCompleted(target:*coroutine) );
     return ___PopResult(target:*coroutine);
 }
int sml_coroutine_get_id (sml_coroutine_handle_t coroutine)
Get id of a coroutine.
Parameters
coroutine Coroutine handle
Returns
The coroutine's id
Definition at line 83 of file coroutines.h.
 {
     return ___GetId(target:*coroutine);
 }
void sml_coroutine_exit (___NULL_T() result)
Exit and delete the current coroutine.
Parameters
result Current coroutine's result value
Definition at line 114 of file coroutines.h.
Referenced by pthread_exit().
 {
     ___CoroutineExit(value:result);
 }
int sml_coroutine_get_current_id ()
Get id of currently running coroutine.
Returns
The current coroutine's id
Definition at line 125 of file coroutines.h.
Referenced by pthread_self().
 {
     return ___GetId( target:___CurrentCoroutine() );
 }