ScriptML C API: resources/c/include/scriptml/devsysfs.h File Reference
devsysfs.h File Reference
Access to /dev and /sys nodes.
#include <unistd.h>
Macros
#define FIX_LEN(P, L) P[ ___Range(start:0 , stop:(X), step:1) ]
#define VAR_ARRAY(T) ___ListType(element_type:T)
#define _data ___NULL_T()
Functions
typedef ___StringType_T (size:___NULL()) _str
typedef ___DevSysfsDeviceType_T () sml_devsysfs_t
sml_devsysfs_t sml_devsysfs_open (_str path)
Open a device. Returns a handle.
void sml_devsysfs_close (sml_devsysfs_t dev)
Close a device.
void sml_devsysfs_write (sml_devsysfs_t dev, _data data)
Write to device.
void sml_devsysfs_write_block (sml_devsysfs_t dev, int pos, _data data)
Write a block of data to device.
_data sml_devsysfs_read (sml_devsysfs_t dev, int len)
Read a number of bytes from device.
_data sml_devsysfs_read_to_eof (sml_devsysfs_t dev)
Read from device until EOF.
_data sml_devsysfs_read_block (sml_devsysfs_t dev, int pos, int len)
Read a block of data from device.
_data sml_devsysfs_read_block_to_eof (sml_devsysfs_t dev, int pos)
Read a block of data from device until end of file.
void sml_devsysfs_ioctl (sml_devsysfs_t dev, unsigned request, _data data)
Perform ioctl on device.
void sml_devsysfs_mono_write (_str path, _data data)
Monolithic write to device.
void sml_devsysfs_mono_write_block (_str path, int pos, _data data)
Monolithic write a block of data to device.
_str sml_devsysfs_mono_read_to_eof (_str path)
Monolithic read from device until EOF.
_str sml_devsysfs_mono_read (_str path, int len)
Monolithic read a number of bytes from device.
_str sml_devsysfs_mono_read_block (_str path, int pos, int len)
Monolithic read a block of data from device.
void sml_devsysfs_mono_ioctl (_str path, unsigned long request, _data data)
Perform monolithic ioctl on device.
Detailed Description
Access to /dev and /sys nodes.
General:
This is the correct API to use for device drivers when accessing these nodes under /dev or /sys. Other "file" APIs may not be able to access these nodes in the correct manner.
There is a class-based interface which holds the device file open while the driver class instance exists, and alternative free functions that open the device, act, and close it again. the latter are termed "monolithic" and begin with mono_.
Read and write operations work with lists of byte data only (numpy.uint8 or numpy.int8). The variants containing _block are for intended for block devices and use pread() and pwrite(). The others use read() and write() are meant for character devices. This correspondance is not strict and some devices don't really correspond to block or character idioms.
The ioctl can accept data structures made up of pointers, arrays and structs, and converts them to and from a memory-based form for use with the underlying ioctl operation. Alignment padding is generated consistent with the C++11 cross-compiler used to build the scriptml interpreter.
C:
The C version of this file includes non-scriptML implementations for use in reference builds for comaprative tests. They are automatically subsituted when ScriptML is not detected.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file devsysfs.h.
Function Documentation
sml_devsysfs_t sml_devsysfs_open (_str path)
Open a device. Returns a handle.
Parameters
path Path to device
Returns
Device handle
Definition at line 83 of file devsysfs.h.
References printf().
Referenced by sml_devsysfs_mono_ioctl(), sml_devsysfs_mono_read(), sml_devsysfs_mono_read_block(), sml_devsysfs_mono_read_to_eof(), sml_devsysfs_mono_write(), sml_devsysfs_mono_write_block(), sml_i2c_open(), sml_serial_open(), and sml_spi_open().
 {
 #ifdef __SCRIPTML
     return ___Construct( object_type:___DevSysfsDeviceType(), args_list:___ArgsList(args:___ISeq(path)), args_map:___ArgsMap(args:___IMap()), variadic_arg:___NULL() );
 #else
     int fd = open(path, O_RDWR);
     if( fd < 0 )
     {
         printf("Failed to open %s: %s\n", path, strerror(errno));
         abort();
     }
     return fd;
 #endif
 }
void sml_devsysfs_close (sml_devsysfs_t dev)
Close a device.
Parameters
dev Device handle
Definition at line 104 of file devsysfs.h.
References printf().
Referenced by sml_devsysfs_mono_ioctl(), sml_devsysfs_mono_read(), sml_devsysfs_mono_read_block(), sml_devsysfs_mono_read_to_eof(), sml_devsysfs_mono_write(), sml_devsysfs_mono_write_block(), sml_i2c_close(), sml_serial_close(), and sml_spi_close().
 {
 #ifdef __SCRIPTML
 #else
     int res = close(dev);
     if( res < 0 )
     {
         printf("Failed to close fd %d: %s\n", dev, strerror(errno));
         abort();
     }
 #endif
 }
void sml_devsysfs_write (sml_devsysfs_t dev, _data data)
Write to device.
Parameters
dev Device handle
data Data to write to the device
Definition at line 124 of file devsysfs.h.
References printf(), and strlen().
Referenced by sml_devsysfs_mono_write(), and sml_serial_write().
 {
 #ifdef __SCRIPTML
     ___Write( device:dev, pos:___NULL(), data:data );
 #else
     int res = write( dev, data, strlen(data) );
     if( res < 0 )
     {
         printf("Failed to write to fd %d: %s\n", dev, strerror(errno));
         abort();
     }
 #endif
 }
void sml_devsysfs_write_block (sml_devsysfs_t dev, int pos, _data data)
Write a block of data to device.
Parameters
dev Device handle
pos Position of start of block
data Data to write to the device
Definition at line 146 of file devsysfs.h.
References printf(), and strlen().
Referenced by sml_devsysfs_mono_write_block().
 {
 #ifdef __SCRIPTML
     ___Write( device:dev, pos:pos, data:data );
 #else
     int res = pwrite( dev, data, strlen(data), pos );
     if( res < 0 )
     {
         printf("Failed to write to fd %d: %s\n", dev, strerror(errno));
         abort();
     }
 #endif
 }
_data sml_devsysfs_read (sml_devsysfs_t dev, int len)
Read a number of bytes from device.
Parameters
dev Device handle
len Number of bytes
Returns
Data read from device
Definition at line 168 of file devsysfs.h.
References i2c_msg::buf, malloc(), and printf().
Referenced by sml_devsysfs_mono_read().
 {
 #ifdef __SCRIPTML
     return ___Read( device:dev, pos:___NULL(), len:len );
 #else
     char *buf = (char *)malloc(len); // compromise for tests: scriptml has no problem here
     int res = read( dev, buf, len );
     if( res < 0 )
     {
         printf("Failed to read from fd %d: %s\n", dev, strerror(errno));
         abort();
     }
     return buf;
 #endif
 }
_data sml_devsysfs_read_to_eof (sml_devsysfs_t dev)
Read from device until EOF.
Parameters
dev Device handle
Returns
Data read from device
Definition at line 191 of file devsysfs.h.
References i2c_msg::buf, i2c_msg::len, and printf().
Referenced by sml_devsysfs_mono_read_to_eof().
 {
 #ifdef __SCRIPTML
     return ___Read( device:dev, pos:___NULL(), len:___NULL() );
 #else
     static char buf[PAGE_SIZE]; // compromise for tests: scriptml has no problem here
     int res = read( dev, buf, PAGE_SIZE );
     if( res < 0 )
     {
         printf("Failed to read from fd %d: %s\n", dev, strerror(errno));
         abort();
     }
     return buf;
 #endif
 }
_data sml_devsysfs_read_block (sml_devsysfs_t dev, int pos, int len)
Read a block of data from device.
Parameters
dev Device handle
pos Position of start of block
len Number of bytes
Returns
Data read from device
Definition at line 216 of file devsysfs.h.
References i2c_msg::buf, malloc(), and printf().
Referenced by sml_devsysfs_mono_read_block().
 {
 #ifdef __SCRIPTML
     return ___Read( device:dev, pos:pos, len:len );
 #else
     char *buf = (char *)malloc(len); // compromise for tests: scriptml has no problem here
     int res = pread( dev, buf, len, pos );
     if( res < 0 )
     {
         printf("Failed to read from fd %d: %s\n", dev, strerror(errno));
         abort();
     }
     return buf;
 #endif
 }
_data sml_devsysfs_read_block_to_eof (sml_devsysfs_t dev, int pos)
Read a block of data from device until end of file.
Parameters
dev Device handle
pos Position of start of block
Returns
Data read from device
Definition at line 240 of file devsysfs.h.
References i2c_msg::buf, i2c_msg::len, and printf().
 {
 #ifdef __SCRIPTML
     return ___Read( device:dev, pos:pos, len:___NULL() );
 #else
     static char buf[PAGE_SIZE]; // compromise for tests: scriptml has no problem here
     int res = pread( dev, buf, PAGE_SIZE, pos );
     if( res < 0 )
     {
         printf("Failed to read from fd %d: %s\n", dev, strerror(errno));
         abort();
     }
     return buf;
 #endif
 }
void sml_devsysfs_ioctl (sml_devsysfs_t dev, unsigned request, _data data)
Perform ioctl on device.
Parameters
dev Device handle
request Ioctl request code
data Pointer to data block, used as input and output
Definition at line 263 of file devsysfs.h.
References printf().
Referenced by sml_devsysfs_mono_ioctl(), sml_i2c_smbus_access(), sml_i2c_smbus_set_addr(), sml_i2c_transfer(), sml_serial_read(), sml_spi_config(), and sml_spi_sync_transfer().
 {
 #ifdef __SCRIPTML
     ___Ioctl( device:dev, request:request, data:data );
 #else
     int res = ioctl( dev, request, data );
     if( res < 0 )
     {
         printf("Failed to ioctl 0x%x: %s\n", request, strerror(errno));
         abort();
     }
 #endif
 }
void sml_devsysfs_mono_write (_str path, _data data)
Monolithic write to device.
Parameters
path Path to device
data Data to write to the device
Definition at line 284 of file devsysfs.h.
References sml_devsysfs_close(), sml_devsysfs_open(), and sml_devsysfs_write().
Referenced by sml_gpio_set_direction(), and sml_gpio_set_level().
 {
     sml_devsysfs_t d = sml_devsysfs_open( path );
     sml_devsysfs_write( d, data );
     sml_devsysfs_close( d );
 }
void sml_devsysfs_mono_write_block (_str path, int pos, _data data)
Monolithic write a block of data to device.
Parameters
path Path to device
pos Position of start of block
data Data to write to the device
Definition at line 299 of file devsysfs.h.
References sml_devsysfs_close(), sml_devsysfs_open(), and sml_devsysfs_write_block().
 {
     sml_devsysfs_t d = sml_devsysfs_open( path );
     sml_devsysfs_write_block( d, pos, data );
     sml_devsysfs_close( d );
 }
_str sml_devsysfs_mono_read_to_eof (_str path)
Monolithic read from device until EOF.
Parameters
path Path to device
Returns
Data read from device
Definition at line 313 of file devsysfs.h.
References sml_devsysfs_close(), sml_devsysfs_open(), and sml_devsysfs_read_to_eof().
Referenced by sml_gpio_get_level(), and sml_serial_read().
 {
     sml_devsysfs_t d = sml_devsysfs_open( path );
     _str data = sml_devsysfs_read_to_eof( d );
     sml_devsysfs_close( d );
     return data;
 }
_str sml_devsysfs_mono_read (_str path, int len)
Monolithic read a number of bytes from device.
Parameters
path Path to device
len Number of bytes
Returns
Data read from device
Definition at line 328 of file devsysfs.h.
References sml_devsysfs_close(), sml_devsysfs_open(), and sml_devsysfs_read().
 {
     sml_devsysfs_t d = sml_devsysfs_open( path );
     _str data = sml_devsysfs_read( d, len );
     sml_devsysfs_close( d );
     return data;
 }
_str sml_devsysfs_mono_read_block (_str path, int pos, int len)
Monolithic read a block of data from device.
Parameters
path Path to device
pos Position of start of block
len Number of bytes
Returns
Data read from device
Definition at line 345 of file devsysfs.h.
References sml_devsysfs_close(), sml_devsysfs_open(), and sml_devsysfs_read_block().
 {
     sml_devsysfs_t d = sml_devsysfs_open( path );
     _str data = sml_devsysfs_read_block( d, pos, len );
     sml_devsysfs_close( d );
     return data;
 }
void sml_devsysfs_mono_ioctl (_str path, unsigned long request, _data data)
Perform monolithic ioctl on device.
Parameters
path Path to device
request Ioctl request code
data Pointer to data block, used as input and output
Definition at line 361 of file devsysfs.h.
References sml_devsysfs_close(), sml_devsysfs_ioctl(), and sml_devsysfs_open().
 {
     sml_devsysfs_t d = sml_devsysfs_open( path );
     sml_devsysfs_ioctl( d, request, data );
     sml_devsysfs_close( d );
 }