ScriptML C API: resources/c/include/scriptml/gpio.h File Reference
gpio.h File Reference
Drive GPIOs using the sysfs interface.
#include <scriptml/devsysfs.h>
#include <unistd.h>
#include <assert.h>
Data Structures
struct sml_gpio_handle
Macros
#define SML_GPIO_IN 0
#define SML_GPIO_OUT 1
Typedefs
typedef struct sml_gpio_handle * sml_gpio_handle_t
Functions
typedef ___StringType_T (size:___NULL()) _str
void sml_gpio_set_direction (sml_gpio_handle_t dev, int dir)
Set pin direction.
sml_gpio_handle_t sml_gpio_open (char *pin)
Initialise access to a GPIO pin.
void sml_gpio_close (char *pin)
End access to a GPIO pin.
void sml_gpio_set_level (sml_gpio_handle_t dev, int l)
Set level of an output pin.
int sml_gpio_get_level (sml_gpio_handle_t dev)
Get level of an output pin.
Detailed Description
Drive GPIOs using the sysfs interface.
The GPIO pins are specified using strings. This is because some platforms use a combination of numbers and letters to specify ports, eg ports named A, B, C and D and pins A0, A1, ... A7, B0, B1, ... and so on.
Recommended practice is to hard-code these strings. If GPIO ports need to be indexed by a numerical expression, simply place the GPIO instances in an list:
gpios = [ gpio.device("A0"), gpio.device("A1"), gpio.device("A2"), gpio.device("A3") ] gpio[index].set_level(...)
This provides robustness against arbitrary re-assignment of GPIOs.
It is recommended to ensure that gpio.device objects are destructed before exiting the executable, because if this is not done, the GPIO device will be left inaccessible (until unexport is performed manually).
Note: On Raspberry Pi, these pins are numbered according to the BCM scheme, not the BOARD scheme. That is to say, the GPIO numbers are as defined at chip-level, not board-pinout-level.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file gpio.h.
Data Structure Documentation
struct sml_gpio_handle
Definition at line 46 of file gpio.h.
Data Fields
_str path
int direction
Path to GPIO pin sysfs directory
Function Documentation
void sml_gpio_set_direction (sml_gpio_handle_t dev, int dir)
Set pin direction.
Parameters
dev Device handle
dir Direction; one of SML_GPIO_IN or SML_GPIO_OUT
Definition at line 59 of file gpio.h.
References sml_gpio_handle::direction, and sml_devsysfs_mono_write().
Referenced by sml_gpio_open().
 {
     dev->direction = dir;
     sml_devsysfs_mono_write( dev->path+"direction", dev->direction==SML_GPIO_OUT?"out":"in" );
 }
sml_gpio_handle_t sml_gpio_open (char * pin)
Initialise access to a GPIO pin.
Parameters
num GPIO pin number (as a string) or name
Returns
Device handle
Definition at line 72 of file gpio.h.
References sml_gpio_set_direction().
 {
     struct sml_gpio_handle dev;
     _str spin = pin;
     _str s0 = "/sys/class/gpio/gpio"+spin;
     dev.path = s0+"/";
     sml_gpio_set_direction( &dev, SML_GPIO_IN );
     return &dev;
 }
void sml_gpio_close (char * pin)
End access to a GPIO pin.
Parameters
num GPIO pin number (note: not the handle)
Definition at line 88 of file gpio.h.
 {
 }
void sml_gpio_set_level (sml_gpio_handle_t dev, int l)
Set level of an output pin.
Parameters
dev Device handle
l Level; 0 or 1
Definition at line 99 of file gpio.h.
References assert, sml_gpio_handle::direction, and sml_devsysfs_mono_write().
 {
     assert( dev->direction == SML_GPIO_OUT );
     _str sl = l;
     sml_devsysfs_mono_write( dev->path+"value", sl );
 }
int sml_gpio_get_level (sml_gpio_handle_t dev)
Get level of an output pin.
Parameters
dev Device handle
Returns
Level; 0 or 1
Definition at line 113 of file gpio.h.
References sml_devsysfs_mono_read_to_eof().
 {
     _str sl = sml_devsysfs_mono_read_to_eof( dev->path+"value" );
     int l = sl;
     return l;
 }