ScriptML C API: resources/c/include/scriptml/i2c.h File Reference
i2c.h File Reference
Generic I2C bus driver using /dev and ioctl.
#include <scriptml/devsysfs.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
Data Structures
struct i2c_msg
struct i2c_rdwr_ioctl_data
struct i2c_smbus_ioctl_data
Macros
#define I2C_M_RD
#define I2C_M_TEN 0x0010 /** this is a ten bit chip address */
#define I2C_M_RECV_LEN 0x0400 /** length will be first received byte */
#define I2C_M_NO_RD_ACK 0x0800 /** if I2C_FUNC_PROTOCOL_MANGLING */
#define I2C_M_IGNORE_NAK 0x1000 /** if I2C_FUNC_PROTOCOL_MANGLING */
#define I2C_M_REV_DIR_ADDR 0x2000 /** if I2C_FUNC_PROTOCOL_MANGLING */
#define I2C_M_NOSTART 0x4000 /** if I2C_FUNC_NOSTART */
#define I2C_M_STOP 0x8000 /** if I2C_FUNC_PROTOCOL_MANGLING */
#define I2C_RDWR 0x0707 /* Combined R/W transfer (one STOP only) */
#define I2C_SMBUS 0x0720 /* SMBus transfer */
#define I2C_SLAVE 0x0703 /* Use this slave address */
#define I2C_SMBUS_BLOCK_MAX 32
#define I2C_SMBUS_BLOCK_MAX_PADDED 34
#define I2C_SMBUS_READ 1
#define I2C_SMBUS_WRITE 0
#define I2C_SMBUS_QUICK 0
#define I2C_SMBUS_BYTE 1
#define I2C_SMBUS_BYTE_DATA 2
#define I2C_SMBUS_WORD_DATA 3
#define I2C_SMBUS_PROC_CALL 4
#define I2C_SMBUS_BLOCK_DATA 5
#define I2C_SMBUS_I2C_BLOCK_BROKEN 6
#define I2C_SMBUS_BLOCK_PROC_CALL 7 /* SMBus 2.0 */
#define I2C_SMBUS_I2C_BLOCK_DATA 8
Typedefs
typedef sml_devsysfs_t sml_i2c_t
typedef struct i2c_msg i2c_msg_t
Functions
sml_i2c_t sml_i2c_open (char *path)
Create device driver instance.
void sml_i2c_close (sml_i2c_t dev)
Destroy device driver instance.
void sml_i2c_transfer (sml_i2c_t dev, struct i2c_msg *msgs, int num)
Perform I2C transfer(s)
void sml_i2c_write (sml_i2c_t dev, uint8_t addr, const uint8_t *buf, size_t count)
Write to I2C device registers.
void sml_i2c_read (sml_i2c_t dev, uint8_t addr, uint8_t *buf, size_t count)
Read from I2C device registers.
void sml_i2c_smbus_set_addr (sml_i2c_t dev, uint8_t addr)
Set I2C bus device address.
void sml_i2c_smbus_access (sml_i2c_t dev, uint8_t read_write, uint8_t command, uint32_t size, uint8_t *data)
Perform I2C/SMBUS access.
void sml_i2c_smbus_write_quick (sml_i2c_t dev, uint8_t value)
uint8_t sml_i2c_smbus_read_byte (sml_i2c_t dev)
void sml_i2c_smbus_write_byte (sml_i2c_t dev, uint8_t value)
uint8_t sml_i2c_smbus_read_byte_data (sml_i2c_t dev, uint8_t command)
void sml_i2c_smbus_write_byte_data (sml_i2c_t dev, uint8_t command, uint8_t value)
uint16_t sml_i2c_smbus_read_word_data (sml_i2c_t dev, uint8_t command)
void sml_i2c_smbus_write_word_data (sml_i2c_t dev, uint8_t command, uint16_t value)
uint16_t sml_i2c_smbus_process_call (sml_i2c_t dev, uint8_t command, uint16_t value)
int32_t sml_i2c_smbus_read_block_data (sml_i2c_t dev, uint8_t command, uint8_t *values)
void sml_i2c_smbus_write_block_data (sml_i2c_t dev, uint8_t command, uint8_t length, const uint8_t *values)
Detailed Description
Generic I2C bus driver using /dev and ioctl.
General:
Broadly speaking this driver follows the precedents set by the internal Linux API for device drivers that access their devices via I2C.
For maximum flexibility, this driver does not encode the paths to the i2c nodes. This is because it will often be desirable to make such paths a config option, or to use a symbolic link or other alias in lieu of the usual path.
Note: this driver does not keep track of I2C addresses. This is a more natural fit for individual device drivers. Firstly, the I2C base address is hard-coded into i2c ICs. Secondly, the address offset, if any, is managed by the IC according to its own documentation (eg as a function of Ax pins). Finally, while the Linux i2c driver model carries a device address in its equivalent of our "device" class, that address is overridden by the one passed to i2c_transfer() in the i2c_msg struct. We are in fact consistent in behaviour because of this.
C:
The i2c_msg structure, the i2c_rdwr_ioctl_data structure and the sml_i2c_transfer() function have been designed to match the Linux internal device driver APIs for I2C, in order to simplify porting.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file i2c.h.
Data Structure Documentation
struct i2c_msg
I2C message structure from linux/i2c.h
Definition at line 46 of file i2c.h.
Data Fields
uint16_t addr
uint16_t flags
Slave address
uint16_t len
An "or" comination of I2C_M_ values
uint8_t * buf
Msg length
struct i2c_rdwr_ioctl_data
Definition at line 67 of file i2c.h.
Data Fields
struct i2c_msg * msgs
uint32_t nmsgs
struct i2c_smbus_ioctl_data
Definition at line 168 of file i2c.h.
Data Fields
uint8_t read_write
uint8_t command
uint32_t size
uint8_t * data
Macro Definition Documentation
#define I2C_M_RD
Value:
0x0001
Definition at line 56 of file i2c.h.
Function Documentation
sml_i2c_t sml_i2c_open (char * path)
Create device driver instance.
Parameters
path Absolute path to the device node.
Returns
Device handle
Example paths would be "/dev/i2c-1", "/dev/i2c-2" and so on
Definition at line 79 of file i2c.h.
References sml_devsysfs_open().
 {
     return sml_devsysfs_open( path );
 }
void sml_i2c_close (sml_i2c_t dev)
Destroy device driver instance.
Parameters
dev Device handle
Definition at line 89 of file i2c.h.
References sml_devsysfs_close().
 {
     return sml_devsysfs_close( dev );
 }
void sml_i2c_transfer (sml_i2c_t dev, struct i2c_msg * msgs, int num)
Perform I2C transfer(s)
Parameters
dev Device handle
msgs An array of i2c_msg structures
num The number of i2c_msg structures pointed to by msgs
The i2c_msg structures should be filled in with addr, flags and a pointer to a char buffer containing bytes to read or write.
Definition at line 110 of file i2c.h.
References sml_devsysfs_ioctl().
Referenced by sml_24lc64_read(), sml_24lc64_write(), sml_ad7991_read(), sml_ad7991_write(), sml_i2c_read(), sml_i2c_reg_write(), sml_i2c_regmap_read(), sml_i2c_regmap_readL(), sml_i2c_regmap_write(), sml_i2c_regmap_writeL(), sml_i2c_write(), sml_max518_power(), sml_max518_reset(), sml_max518_set_level(), sml_pcf8574a_read(), and sml_pcf8574a_write().
 {
     struct i2c_rdwr_ioctl_data rdwr_arg;
     rdwr_arg.msgs = msgs;
     rdwr_arg.nmsgs = num;
     sml_devsysfs_ioctl( dev, I2C_RDWR, &rdwr_arg );
 }
void sml_i2c_write (sml_i2c_t dev, uint8_t addr, const uint8_t * buf, size_t count)
Write to I2C device registers.
Parameters
dev Device handle
addr I2C device address
buf Buffer of data to write
count Number of bytes to write
Single block write transaction
Definition at line 128 of file i2c.h.
References i2c_msg::buf, i2c_msg::flags, i2c_msg::len, and sml_i2c_transfer().
 {
     struct i2c_msg msg[1];
     msg[0].addr = addr;
     msg[0].flags = 0; // Write
     msg[0].buf = buf;
     msg[0].len = count;
     sml_i2c_transfer( dev, msg, 1 );
 }
void sml_i2c_read (sml_i2c_t dev, uint8_t addr, uint8_t * buf, size_t count)
Read from I2C device registers.
Parameters
dev Device handle
addr I2C device address
buf Buffer of data for read
count Number of bytes to read
Single block read transaction
Definition at line 151 of file i2c.h.
References i2c_msg::buf, i2c_msg::flags, i2c_msg::len, and sml_i2c_transfer().
 {
     struct i2c_msg msg[1];
     msg[0].addr = addr;
     msg[0].flags = I2C_M_RD; // Read
     msg[0].buf = buf;
     msg[0].len = count;
     sml_i2c_transfer( dev, msg, 1 );
 }
void sml_i2c_smbus_set_addr (sml_i2c_t dev, uint8_t addr)
Set I2C bus device address.
Parameters
dev Device handle
read_write Data direction; one of I2C_SMBUS_READ or I2C_SMBUS_WRITE
Definition at line 197 of file i2c.h.
References sml_devsysfs_ioctl().
Referenced by sml_i2c_regmap_read(), and sml_i2c_regmap_write().
 {
     sml_devsysfs_ioctl( dev, I2C_SLAVE, addr );
 }
void sml_i2c_smbus_access (sml_i2c_t dev, uint8_t read_write, uint8_t command, uint32_t size, uint8_t * data)
Perform I2C/SMBUS access.
Parameters
dev Device handle
read_write Data direction; one of I2C_SMBUS_READ or I2C_SMBUS_WRITE
command Depends on the transaction type - usually the register or only byte to transfer
size The transaction type; one of I2C_SMBUS_QUICK etc
data Optional extra data block, organised as bytes
The size parameter chooses the kind of transaction (not the size). command is the first byte used and additional bytes are in a block pointed to by data.
Definition at line 214 of file i2c.h.
References sml_devsysfs_ioctl().
Referenced by sml_i2c_smbus_process_call(), sml_i2c_smbus_read_block_data(), sml_i2c_smbus_read_byte(), sml_i2c_smbus_read_byte_data(), sml_i2c_smbus_read_word_data(), sml_i2c_smbus_write_block_data(), sml_i2c_smbus_write_byte(), sml_i2c_smbus_write_byte_data(), sml_i2c_smbus_write_quick(), and sml_i2c_smbus_write_word_data().
 {
     struct i2c_smbus_ioctl_data args;
     args.read_write = read_write;
     args.command = command;
     args.size = size;
     args.data = data;
     sml_devsysfs_ioctl( dev, I2C_SMBUS, &args );
 }
void sml_i2c_smbus_write_quick (sml_i2c_t dev, uint8_t value)
SMBus Quick Command
This sends a single bit to the device, at the place of the Rd/Wr bit.
Bus sequence A Addr Rd/Wr [A] P
Parameters
dev Device handle
value Value of bit (1 for read)
Definition at line 238 of file i2c.h.
References NULL, and sml_i2c_smbus_access().
 {
     sml_i2c_smbus_access(dev, value, 0, I2C_SMBUS_QUICK, NULL);
 }
uint8_t sml_i2c_smbus_read_byte (sml_i2c_t dev)
SMBus Receive Byte:
This reads a single byte from a device, without specifying a device register. Some devices are so simple that this interface is enough; for others, it is a shorthand if you want to read the same register as in the previous SMBus command.
Bus sequence S Addr Rd [A] [Data] NA P
Parameters
dev Device handle
Returns
The byte that was read
Definition at line 257 of file i2c.h.
References sml_i2c_smbus_access().
 {
     uint8_t byte;
     sml_i2c_smbus_access(dev, I2C_SMBUS_READ, 0, I2C_SMBUS_BYTE, &byte);
     return byte;
 }
void sml_i2c_smbus_write_byte (sml_i2c_t dev, uint8_t value)
SMBus Send Byte:
This operation is the reverse of Receive Byte: it sends a single byte to a device. See Receive Byte for more information.
Bus sequence: S Addr Wr [A] Data [A] P
Parameters
dev Device handle
value The byte to write
Definition at line 277 of file i2c.h.
References NULL, and sml_i2c_smbus_access().
 {
     sml_i2c_smbus_access(dev, I2C_SMBUS_WRITE, value,
                 I2C_SMBUS_BYTE, NULL);
 }
uint8_t sml_i2c_smbus_read_byte_data (sml_i2c_t dev, uint8_t command)
SMBus Register Read Byte:
This reads a single byte from a device, from a designated register. The register is specified through the Comm byte.
Bus sequence S Addr Wr [A] Comm [A] S Addr Rd [A] [Data] NA P
Parameters
dev Device handle
command The register to read from
Returns
The byte that was read
Definition at line 296 of file i2c.h.
References sml_i2c_smbus_access().
Referenced by sml_i2c_regmap_read().
 {
     uint8_t byte;
     sml_i2c_smbus_access(dev, I2C_SMBUS_READ, command,
                          I2C_SMBUS_BYTE_DATA, &byte);
     return byte;
 }
void sml_i2c_smbus_write_byte_data (sml_i2c_t dev, uint8_t command, uint8_t value)
SMBus Register Write Byte:
This writes a single byte to a device, to a designated register. The register is specified through the Comm byte. This is the opposite of the Read Byte operation.
Bus sequence: S Addr Wr [A] Comm [A] Data [A] P
Parameters
dev Device handle
command The register to write to
value the byte to write
Definition at line 319 of file i2c.h.
References sml_i2c_smbus_access().
Referenced by sml_i2c_regmap_write().
 {
     sml_i2c_smbus_access(dev, I2C_SMBUS_WRITE, command,
                          I2C_SMBUS_BYTE_DATA, &value);
 }
uint16_t sml_i2c_smbus_read_word_data (sml_i2c_t dev, uint8_t command)
SMBus Register Read Word:
This operation is very like Read Byte; again, data is read from a device, from a designated register that is specified through the Comm byte. But this time, the data is a complete word (16 bits).
Bus sequence: S Addr Wr [A] Comm [A] S Addr Rd [A] [DataLow] A [DataHigh] NA P
Parameters
dev Device handle
command The register to read from
Returns
The word that was read
Definition at line 339 of file i2c.h.
References sml_i2c_smbus_access().
 {
     uint16_t word;
     sml_i2c_smbus_access(dev, I2C_SMBUS_READ, command,
                    I2C_SMBUS_WORD_DATA, &word);
     return word;
 }
void sml_i2c_smbus_write_word_data (sml_i2c_t dev, uint8_t command, uint16_t value)
SMBus Register Write Word:
This is the opposite of the Read Word operation. 16 bits of data is written to a device, to the designated register that is specified through the Comm byte.
Bus sequence: S Addr Wr [A] Comm [A] DataLow [A] DataHigh [A] P
Parameters
dev Device handle
command The register to write to
value the word to write
Definition at line 363 of file i2c.h.
References sml_i2c_smbus_access().
 {
     sml_i2c_smbus_access(dev, I2C_SMBUS_WRITE, command,
                 I2C_SMBUS_WORD_DATA, &value);
 }
uint16_t sml_i2c_smbus_process_call (sml_i2c_t dev, uint8_t command, uint16_t value)
SMBus Process Call:
This command selects a device register (through the Comm byte), sends 16 bits of data to it, and reads 16 bits of data in return.
Bus sequence: S Addr Wr [A] Comm [A] DataLow [A] DataHigh [A] S Addr Rd [A] [DataLow] A [DataHigh] NA P
Parameters
dev Device handle
command The register to write to/read from
value the word to write
Returns
The word that was read back
Definition at line 383 of file i2c.h.
References sml_i2c_smbus_access().
 {
     uint16_t word = value;
     sml_i2c_smbus_access(dev, I2C_SMBUS_WRITE, command,
                  I2C_SMBUS_PROC_CALL, &word);
     return word;
 }
int32_t sml_i2c_smbus_read_block_data (sml_i2c_t dev, uint8_t command, uint8_t * values)
SMBus Block Read:
This command reads a block of up to 32 bytes from a device, from a designated register that is specified through the Comm byte. The amount of data is specified by the device in the Count byte.
Bus sequence: S Addr Wr [A] Comm [A] S Addr Rd [A] [Count] A [Data] A [Data] A ... A [Data] NA P
Parameters
dev Device handle
command The register to read from
values Pointer to the block of bytes to read
Returns
The number of read bytes
Definition at line 407 of file i2c.h.
References sml_i2c_smbus_access().
 {
     uint8_t data[I2C_SMBUS_BLOCK_MAX_PADDED];
     int i;
     sml_i2c_smbus_access(dev, I2C_SMBUS_READ, command,
                    I2C_SMBUS_BLOCK_DATA, &data);
     for (i = 1; i <= data[0]; i++)
         values[i-1] = data[i];
     return data[0];
 }
void sml_i2c_smbus_write_block_data (sml_i2c_t dev, uint8_t command, uint8_t length, const uint8_t * values)
SMBus Block Write:
The opposite of the Block Read command, this writes up to 32 bytes to a device, to a designated register that is specified through the Comm byte. The amount of data is specified in the Count byte.
Bus sequence: S Addr Wr [A] Comm [A] Count [A] Data [A] Data [A] ... [A] Data [A] P
Parameters
dev Device handle
command The register to write to
length The number of bytes
values Pointer to the block of bytes to write
Definition at line 435 of file i2c.h.
References assert, and sml_i2c_smbus_access().
 {
     uint8_t data[I2C_SMBUS_BLOCK_MAX_PADDED];
     int i;
     assert(length <= I2C_SMBUS_BLOCK_MAX);
     for (i = 1; i <= length; i++)
         data[i] = values[i-1];
     data[0] = length;
     sml_i2c_smbus_access(dev, I2C_SMBUS_WRITE, command,
                 I2C_SMBUS_BLOCK_DATA, &data);
 }