ScriptML C API: resources/c/include/scriptml/i2c_regmap.h File Reference
i2c_regmap.h File Reference
Sub-driver for I2C devices organised as regmaps.
#include <scriptml/i2c.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
Data Structures
struct sml_i2c_regmap_t
Functions
sml_i2c_regmap_t sml_i2c_regmap_create (sml_i2c_t i2c, int addr, int size, int smbus_api)
Create device driver instance.
void sml_i2c_regmap_write (sml_i2c_regmap_t dev, const uint8_t *buf, uint8_t reg, size_t count)
Write to I2C device registers.
void sml_i2c_regmap_read (sml_i2c_regmap_t dev, uint8_t *buf, uint8_t reg, size_t count)
Read from I2C device registers.
uint8_t * int_to_byte (int *input_int, int num_bytes)
Convert an integer into a defined bumber of bytes.
void sml_i2c_regmap_writeL (sml_i2c_regmap_t dev, const uint8_t *buf, int *reg, int reg_addr_size, size_t count)
Write long to I2C device registers for register addresses greater than one byte.
void sml_i2c_reg_write (sml_i2c_regmap_t dev, const uint8_t *buf, size_t count)
Simple write of a number of bytes to a single address (0x00)
void sml_i2c_regmap_readL (sml_i2c_regmap_t dev, uint8_t *buf, int *reg, int reg_addr_size, size_t count)
Read long from I2C device registers for register addresses greater than one byte.
Detailed Description
Sub-driver for I2C devices organised as regmaps.
Where an I2C device implements a "regular" regmap, a sml_i2c_regmap_t instance may be created to permit access using straightforward read and write operations, simplifying device driver implementation.
The device must accept writes of the form START <device addr+W bit> <register> <bytes...> STOP
and reads of the form START <device addr+W bit> <register> START <device addr+R bit> <bytes...> STOP
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file i2c_regmap.h.
Data Structure Documentation
struct sml_i2c_regmap_t
Definition at line 29 of file i2c_regmap.h.
Data Fields
sml_i2c_t * piic
int addr
int size
int smbus_api
Function Documentation
sml_i2c_regmap_t sml_i2c_regmap_create (sml_i2c_t i2c, int addr, int size, int smbus_api)
Create device driver instance.
Note that the I2C/SMBUS API can only be used with devices that auto-increment the register number on multi-byte operations.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
addr Address of the I2C device on the bus
size Number of registers in the regmap (just for a check)
smbus_api 0 for plain I2C; 1 for I2C/SMBUS.
Returns
Device handle
Definition at line 49 of file i2c_regmap.h.
Referenced by sml_ad7091_create(), sml_isl29023_create(), sml_lm75b_create(), sml_mpl115a2_create(), sml_mpu6050_create(), sml_pca9534_create(), sml_pca9685_create(), and sml_pcf8563_create().
 {
     sml_i2c_regmap_t dev;
     dev.piic = &i2c;
     dev.addr = addr;
     dev.size = size;
     dev.smbus_api = smbus_api;
     return dev;
 }
void sml_i2c_regmap_write (sml_i2c_regmap_t dev, const uint8_t * buf, uint8_t reg, size_t count)
Write to I2C device registers.
Parameters
dev Device handle
buf Buffer of data to write
reg Number of first register to write
count Number of bytes to write
If count is greater than one, multiple bytes are written stating at reg. Count must be at least one byte and the write operation must not go past the end of the register map. Note that it is dependent on the device whether a multiple write goes to sucessive registers.
Definition at line 72 of file i2c_regmap.h.
References assert, i2c_msg::buf, i2c_msg::flags, i2c_msg::len, malloc(), memcpy(), printf(), sml_i2c_smbus_set_addr(), sml_i2c_smbus_write_byte_data(), and sml_i2c_transfer().
Referenced by sml_ad7091_set_ch0_high_limit(), sml_ad7091_set_ch0_hyst_limit(), sml_ad7091_set_ch0_low_limit(), sml_ad7091_set_ch1_high_limit(), sml_ad7091_set_ch1_hyst_limit(), sml_ad7091_set_ch1_low_limit(), sml_ad7091_set_ch2_high_limit(), sml_ad7091_set_ch2_hyst_limit(), sml_ad7091_set_ch2_low_limit(), sml_ad7091_set_ch3_high_limit(), sml_ad7091_set_ch3_hyst_limit(), sml_ad7091_set_ch3_low_limit(), sml_ad7091_set_channel_register(), sml_ad7091_set_conf_reg(), sml_isl29023_set_command_1(), sml_isl29023_set_command_2(), sml_isl29023_set_int_ht(), sml_isl29023_set_int_lt(), sml_lm75b_set_conf(), sml_lm75b_set_thyst(), sml_lm75b_set_tos(), sml_mpl115a2_convert(), sml_mpu6050_set_accel_config(), sml_mpu6050_set_config(), sml_mpu6050_set_fifo_en(), sml_mpu6050_set_fifo_r_w(), sml_mpu6050_set_gyro_config(), sml_mpu6050_set_int_enable(), sml_mpu6050_set_int_pin_cfg(), sml_mpu6050_set_pwr_mgmt_1(), sml_mpu6050_set_pwr_mgmt_2(), sml_mpu6050_set_signal_path_reset(), sml_mpu6050_set_smprt_div(), sml_mpu6050_set_user_ctrl(), sml_pca9534_set_configuration(), sml_pca9534_set_output(), sml_pca9534_set_polarity(), sml_pca9685_set_all_led_on_off(), sml_pca9685_set_led_on_off(), sml_pca9685_set_mode1(), sml_pca9685_set_mode2(), sml_pca9685_set_pre_scale(), sml_pca9685_set_subadr(), sml_pcf8563_set_clkout_control(), sml_pcf8563_set_control_status_1(), sml_pcf8563_set_control_status_2(), sml_pcf8563_set_day_alarm(), sml_pcf8563_set_hour_alarm(), sml_pcf8563_set_minute_alarm(), sml_pcf8563_set_timer(), sml_pcf8563_set_timer_control(), sml_pcf8563_set_vl_and_time_combined(), and sml_pcf8563_set_weekday_alarm().
 {
     assert( count >= 1 );
     assert( reg < dev.size );
 #ifdef TRACE_I2C_REGMAP
     printf("I2C at 0x%x regmap at 0x%x write", dev.addr, reg);
     int i;
     for( i=0; i<(int)count; i++ )
         printf(" 0x%x", buf[i] );
     printf("\n");
 #endif
     if( dev.smbus_api )
     {
         sml_i2c_smbus_set_addr( *(dev.piic), dev.addr );
         int i;
         for( i=0; i<count; i++ )
             sml_i2c_smbus_write_byte_data( *(dev.piic), reg+i, buf[i] );
     }
     else
     {
         uint8_t *wbuf = (uint8_t *)malloc( count+1 );
         wbuf[0] = (uint8_t)reg;
         memcpy( wbuf+1, buf, count );
         struct i2c_msg msg[1];
         msg[0].addr = dev.addr;
         msg[0].flags = 0; // Write
         msg[0].buf = wbuf;
         msg[0].len = count + 1; // Account for the register byte
         sml_i2c_transfer(*(dev.piic), msg, 1);
     }
 }
void sml_i2c_regmap_read (sml_i2c_regmap_t dev, uint8_t * buf, uint8_t reg, size_t count)
Read from I2C device registers.
Parameters
dev Device handle
buf Buffer of data for read
reg Number of first register to read
count Number of bytes to read
If count is greater than one, multiple bytes are read stating at reg. Count must be at least one byte and the write operation must not go past the end of the register map. Note that it is dependent on the device whether a multiple read reads sucessive registers.
Definition at line 123 of file i2c_regmap.h.
References assert, i2c_msg::buf, i2c_msg::flags, i2c_msg::len, printf(), sml_i2c_smbus_read_byte_data(), sml_i2c_smbus_set_addr(), and sml_i2c_transfer().
Referenced by sml_ad7091_get_ch0_high_limit(), sml_ad7091_get_ch0_hyst_limit(), sml_ad7091_get_ch0_low_limit(), sml_ad7091_get_ch1_high_limit(), sml_ad7091_get_ch1_hyst_limit(), sml_ad7091_get_ch1_low_limit(), sml_ad7091_get_ch2_high_limit(), sml_ad7091_get_ch2_hyst_limit(), sml_ad7091_get_ch2_low_limit(), sml_ad7091_get_ch3_high_limit(), sml_ad7091_get_ch3_hyst_limit(), sml_ad7091_get_ch3_low_limit(), sml_ad7091_get_channel_register(), sml_ad7091_get_conf_reg(), sml_ad7091_get_conv_res(), sml_isl29023_get_data(), sml_lm75b_get_temp(), sml_mpl115a2_get_a0(), sml_mpl115a2_get_b1(), sml_mpl115a2_get_b2(), sml_mpl115a2_get_c12(), sml_mpl115a2_get_padc(), sml_mpl115a2_get_tadc(), sml_mpu6050_get_accel_xout(), sml_mpu6050_get_accel_yout(), sml_mpu6050_get_accel_zout(), sml_mpu6050_get_fifo_count(), sml_mpu6050_get_fifo_r_w(), sml_mpu6050_get_gyro_xout(), sml_mpu6050_get_gyro_yout(), sml_mpu6050_get_gyro_zout(), sml_mpu6050_get_int_status(), sml_mpu6050_get_smprt_div(), sml_mpu6050_get_temp_out(), sml_mpu6050_get_who_am_i(), sml_pca9534_get_configuration(), sml_pca9534_get_input(), sml_pca9534_get_output(), sml_pca9534_get_polarity(), sml_pca9685_get_mode1(), sml_pcf8563_get_clkout_control(), sml_pcf8563_get_control_status_1(), sml_pcf8563_get_control_status_2(), sml_pcf8563_get_day_alarm(), sml_pcf8563_get_hour_alarm(), sml_pcf8563_get_minute_alarm(), sml_pcf8563_get_timer(), sml_pcf8563_get_timer_control(), sml_pcf8563_get_vl_and_time_combined(), and sml_pcf8563_get_weekday_alarm().
 {
     assert( count >= 1 );
     assert( reg < dev.size );
     if( dev.smbus_api )
     {
         sml_i2c_smbus_set_addr( *(dev.piic), dev.addr );
         int i;
         for( i=0; i<count; i++ )
             buf[i] = sml_i2c_smbus_read_byte_data( *(dev.piic), reg+i );
     }
     else
     {
         struct i2c_msg msg[2];
         msg[0].addr = dev.addr;
         msg[0].flags = 0; // Write
         msg[0].buf = &reg;
         msg[0].len = 1;
         msg[1].addr = dev.addr;
         msg[1].flags = I2C_M_RD; // Read
         msg[1].buf = buf;
         msg[1].len = count;
         sml_i2c_transfer(*(dev.piic), msg, 2);
     }
 #ifdef TRACE_I2C_REGMAP
     printf("I2C at 0x%x regmap at 0x%x read", dev.addr, reg);
     int i;
     for( i=0; i<(int)count; i++ )
         printf(" 0x%x", buf[i] );
     printf("\n");
 #endif
 }
uint8_t* int_to_byte (int * input_int, int num_bytes)
Convert an integer into a defined bumber of bytes.
Parameters
input_int Input integer to convert
num_bytes Number of bytes to extract from the integer
Returns
A byte array with num_bytes elements
Parameters
count Number of bytes to read
The endian-ness of this operations is as follows; The MSB is returned in the lowest index [0] and the LSB in the highest index [num_bytes - 1]
Definition at line 172 of file i2c_regmap.h.
References malloc().
Referenced by sml_i2c_regmap_readL(), and sml_i2c_regmap_writeL().
{
     int i;
     uint8_t * ret_bytes = malloc(num_bytes * 8);
     for (i = 0; i < num_bytes; i++){
         ret_bytes[i] = (* input_int) >> (((num_bytes-1)-i) * 8);
     }
     return ret_bytes;
 }
void sml_i2c_regmap_writeL (sml_i2c_regmap_t dev, const uint8_t * buf, int * reg, int reg_addr_size, size_t count)
Write long to I2C device registers for register addresses greater than one byte.
Parameters
dev Device handle
buf Buffer of data to write
reg Number of first register to write
reg_addr_size Register address size in bytes, maximum is 4 bytes
count Number of bytes to write
If count is greater than one, contiguous registers are written stating at reg. Count must be at least one byte and the write operation must not go past the end of the register map.
Definition at line 195 of file i2c_regmap.h.
References assert, i2c_msg::buf, i2c_msg::flags, int_to_byte(), i2c_msg::len, malloc(), memcpy(), printf(), and sml_i2c_transfer().
 {
     assert( count >= 1 );
     assert( *reg + count <= dev.size );
 #ifdef TRACE_I2C_REGMAP
     int i;
     for( i=0; i<(int)count; i++ )
         printf(" 0x%x", buf[i] );
     printf("\n");
 #endif
     int i;
     uint8_t *wbuf = (uint8_t *)malloc( count + reg_addr_size );
     uint8_t *raddr = (uint8_t *)malloc( reg_addr_size );
     raddr = int_to_byte(reg, reg_addr_size);
     for (i = 0; i < reg_addr_size; i++){
         wbuf[i]  = raddr[i];
     }
     memcpy( wbuf+reg_addr_size, buf, count );
     struct i2c_msg msg[1];
     msg[0].addr = (dev.addr);
     msg[0].flags = 0; // Write
     msg[0].buf = wbuf;
     msg[0].len = count;
     sml_i2c_transfer(*(dev.piic), msg, 1);
 }
void sml_i2c_reg_write (sml_i2c_regmap_t dev, const uint8_t * buf, size_t count)
Simple write of a number of bytes to a single address (0x00)
Parameters
dev Device handle
buf Buffer of data to write
count Number of bytes to write
If count is greater than one, contiguous registers are written stating at reg. Count must be at least one byte and the write operation must not go past the end of the register map.
Definition at line 238 of file i2c_regmap.h.
References i2c_msg::buf, i2c_msg::flags, i2c_msg::len, and sml_i2c_transfer().
Referenced by sml_ad5627_power(), sml_ad5627_reset(), sml_ad5627_set_ldac(), and sml_ad5627_set_level().
 {
     struct i2c_msg msg[1];
     msg[0].addr = (dev.addr);
     msg[0].flags = 0; // Write
     msg[0].buf = buf;
     msg[0].len = count;
     sml_i2c_transfer(*(dev.piic), msg, 1);
 }
void sml_i2c_regmap_readL (sml_i2c_regmap_t dev, uint8_t * buf, int * reg, int reg_addr_size, size_t count)
Read long from I2C device registers for register addresses greater than one byte.
Parameters
dev Device handle
buf Buffer of data for read
reg Number of first register to read
count Number of bytes to read
If count is greater than one, contiguous registers are written stating at reg. Count must be at least one byte and the write operation must not go past the end of the register map.
Definition at line 262 of file i2c_regmap.h.
References assert, i2c_msg::buf, i2c_msg::flags, int_to_byte(), i2c_msg::len, malloc(), printf(), and sml_i2c_transfer().
 {
     assert( count >= 1 );
     assert( *reg + count <= dev.size );
     struct i2c_msg msg[2];
     uint8_t *raddr = (uint8_t *)malloc( reg_addr_size );
     raddr = int_to_byte(reg, reg_addr_size);
     msg[0].addr = (dev.addr);
     msg[0].flags = 0; // Write
     msg[0].buf = raddr;
     msg[0].len = reg_addr_size;
     msg[1].addr = (dev.addr);
     msg[1].flags = I2C_M_RD; // Read
     msg[1].buf = buf;
     msg[1].len = count;
     sml_i2c_transfer(*(dev.piic), msg, 2);
 #ifdef TRACE_I2C_REGMAP
     int i;
     for( i=0; i<(int)count; i++ )
         printf(" 0x%x", buf[i] );
     printf("\n");
 #endif
 }