ScriptML C API: resources/c/include/scriptml/isl29023.h File Reference
isl29023.h File Reference
ISL29023 device driver.
#include <i2c_regmap.h>
#include <gpio.h>
Data Structures
struct sml_isl29023_t
Macros
#define SML_ISL29023_BASE_ADDR 0x44
#define SML_ISL29023_COMMAND_1_MODE_IR_ONCE 0x2
#define SML_ISL29023_COMMAND_1_MODE_IR_CONTINUOUS 0x6
#define SML_ISL29023_COMMAND_1_MODE_ALS_CONTINUOUS 0x5
#define SML_ISL29023_COMMAND_1_MODE_POWER_DOWN 0x0
#define SML_ISL29023_COMMAND_1_MODE_ALS_INTEGRATION_CYCLE 0x1
#define SML_ISL29023_COMMAND_1_PERSIST_1_CYCLE 0x0
#define SML_ISL29023_COMMAND_1_PERSIST_8_CYCLES 0x2
#define SML_ISL29023_COMMAND_1_PERSIST_16_CYCLES 0x3
#define SML_ISL29023_COMMAND_1_PERSIST_4_CYCLES 0x1
#define SML_ISL29023_COMMAND_2_RESOLUTION_4_BIT 0x3
#define SML_ISL29023_COMMAND_2_RESOLUTION_12_BIT 0x1
#define SML_ISL29023_COMMAND_2_RESOLUTION_8_BIT 0x2
#define SML_ISL29023_COMMAND_2_RESOLUTION_16_BIT 0x0
#define SML_ISL29023_COMMAND_2_RANGE_16000_LUX 0x2
#define SML_ISL29023_COMMAND_2_RANGE_64000_LUX 0x3
#define SML_ISL29023_COMMAND_2_RANGE_1000_LUX 0x0
#define SML_ISL29023_COMMAND_2_RANGE_4000_LUX 0x1
Functions
sml_isl29023_t sml_isl29023_create (sml_i2c_t i2c, sml_gpio_handle_t intr_pin)
Create device driver instance.
void sml_isl29023_set_command_1 (sml_isl29023_t dev, int mode, int persist)
Set the device's operation mode.
void sml_isl29023_set_command_2 (sml_isl29023_t dev, int resolution, int range)
Set the device's resolution and range.
uint16_t sml_isl29023_get_data (sml_isl29023_t dev)
Get data registers.
void sml_isl29023_set_int_lt (sml_isl29023_t dev, uint16_t int_lt)
Set lower interrupt threshold.
void sml_isl29023_set_int_ht (sml_isl29023_t dev, uint16_t int_ht)
Set upper interrupt threshold.
Detailed Description
ISL29023 device driver.
Detects the level of visible light or infra-red.
Program the two command registers and then read back from the data register.
Auto-generated 30 October 2017; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file isl29023.h.
Data Structure Documentation
struct sml_isl29023_t
Definition at line 44 of file isl29023.h.
Data Fields
sml_i2c_regmap_t iic
sml_gpio_handle_t intr_gpio
Function Documentation
sml_isl29023_t sml_isl29023_create (sml_i2c_t i2c, sml_gpio_handle_t intr_pin)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
intr_pin An instance of the GPIO driver for the pin connected to the interrupt line
Returns
Device handle
Definition at line 57 of file isl29023.h.
References sml_i2c_regmap_create().
 {
     sml_isl29023_t dev;
     dev.intr_gpio = intr_pin;
     dev.iic = sml_i2c_regmap_create( i2c, SML_ISL29023_BASE_ADDR, 0x100, 1 );
     return dev;
 }
void sml_isl29023_set_command_1 (sml_isl29023_t dev, int mode, int persist)
Set the device's operation mode.
Parameters
dev The device handle
mode operation mode
persist interrupt persistance mode
Definition at line 72 of file isl29023.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((mode & 0x7) << 5) | (persist & 0x3);
     sml_i2c_regmap_write( dev.iic, &_value, 0x0, 1 );
 }
void sml_isl29023_set_command_2 (sml_isl29023_t dev, int resolution, int range)
Set the device's resolution and range.
Parameters
dev The device handle
resolution ADC resolution
range full scale range
Definition at line 86 of file isl29023.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((resolution & 0x3) << 2) | (range & 0x3);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1, 1 );
 }
uint16_t sml_isl29023_get_data (sml_isl29023_t dev)
Get data registers.
Parameters
dev The device handle
Returns
data registers
Definition at line 99 of file isl29023.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x2, 2 );
     return (uint16_t)((int)(_bytes[0]) | ((int)(_bytes[1]) << 8));
 }
void sml_isl29023_set_int_lt (sml_isl29023_t dev, uint16_t int_lt)
Set lower interrupt threshold.
Parameters
dev The device handle
int_lt lower interrupt threshold
Definition at line 112 of file isl29023.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = int_lt & 0xff;
     _bytes[1] = (int_lt >> 8) & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x4, 2 );
 }
void sml_isl29023_set_int_ht (sml_isl29023_t dev, uint16_t int_ht)
Set upper interrupt threshold.
Parameters
dev The device handle
int_ht upper interrupt threshold
Definition at line 126 of file isl29023.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[2];
     _bytes[0] = int_ht & 0xff;
     _bytes[1] = (int_ht >> 8) & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x6, 2 );
 }