ScriptML C API: resources/c/include/scriptml/max518.h File Reference
max518.h File Reference
MAX518 DAC device driver.
#include <scriptml/i2c.h>
Data Structures
struct sml_max518_t
Macros
#define BASE_ADDR 0x2C
Functions
sml_max518_t sml_max518_create (sml_i2c_t i2c, int addr_offset)
Create device driver instance.
void sml_max518_set_level (sml_max518_t dev, int channel, int level)
Set the level of output pins on the IO expander.
void sml_max518_power (sml_max518_t dev, int power)
Set power status.
void sml_max518_reset (sml_max518_t dev)
Reset device.
Detailed Description
MAX518 DAC device driver.
Support for output level setting on both channels, power down and reset
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file max518.h.
Data Structure Documentation
struct sml_max518_t
Definition at line 15 of file max518.h.
Data Fields
sml_i2c_t * piic
int addr
Function Documentation
sml_max518_t sml_max518_create (sml_i2c_t i2c, int addr_offset)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
addr_offset The I2C address offset, corresponding to the value on the Ax pins, 0 through 3 inclusive
Returns
Device handle
Definition at line 28 of file max518.h.
 {
     sml_max518_t dev;
     dev.piic = &i2c;
     dev.addr = BASE_ADDR | addr_offset;
     return dev;
 }
void sml_max518_set_level (sml_max518_t dev, int channel, int level)
Set the level of output pins on the IO expander.
Parameters
dev Device handle
channel Channel number to set; 0 or 1
level A byte containing the level; 0 through 255 inclusive
Definition at line 43 of file max518.h.
References i2c_msg::buf, i2c_msg::flags, i2c_msg::len, and sml_i2c_transfer().
 {
     struct i2c_msg msg;
     msg.addr = dev.addr;
     msg.flags = 0;
     char b[2];
     msg.buf = b;
     int i=0;
     msg.buf[i++] = channel;
     msg.buf[i++] = level;
     msg.len = i;
     sml_i2c_transfer(*(dev.piic), &msg, 1);
 }
void sml_max518_power (sml_max518_t dev, int power)
Set power status.
Parameters
dev Device handle
power Power status; 0 for off, 1 for on
Note: device is intially powered on
Definition at line 65 of file max518.h.
References i2c_msg::buf, i2c_msg::flags, i2c_msg::len, and sml_i2c_transfer().
 {
     struct i2c_msg msg;
     msg.addr = dev.addr;
     msg.flags = 0;
     char b[2];
     msg.buf = b;
     int i=0;
     msg.buf[i++] = power ? 0x0 : 0x8;
     msg.len = i;
     sml_i2c_transfer(*(dev.piic), &msg, 1);
 }
void sml_max518_reset (sml_max518_t dev)
Reset device.
Parameters
dev Device handle
Device is reset as described in the data sheet
Definition at line 85 of file max518.h.
References i2c_msg::buf, i2c_msg::flags, i2c_msg::len, and sml_i2c_transfer().
 {
     struct i2c_msg msg;
     msg.addr = dev.addr;
     msg.flags = 0;
     char b[2];
     msg.buf = b;
     int i=0;
     msg.buf[i++] = 0x10;
     msg.len = i;
     sml_i2c_transfer(*(dev.piic), &msg, 1);
 }