ScriptML C API: resources/c/include/scriptml/mpl115a2.h File Reference
mpl115a2.h File Reference
Miniature I2C Digital Barometer.
#include <i2c_regmap.h>
Data Structures
struct sml_mpl115a2_t
Macros
#define SML_MPL115A2_BASE_ADDR 0x60
Functions
sml_mpl115a2_t sml_mpl115a2_create (sml_i2c_t i2c)
Create device driver instance.
void sml_mpl115a2_get_padc (sml_mpl115a2_t dev, int *padc)
Get Pressure ADC output value.
void sml_mpl115a2_get_tadc (sml_mpl115a2_t dev, int *tadc)
Get Temperature ADC output value.
int16_t sml_mpl115a2_get_a0 (sml_mpl115a2_t dev)
Get a0 coefficient.
int16_t sml_mpl115a2_get_b1 (sml_mpl115a2_t dev)
Get b1 coefficient.
int16_t sml_mpl115a2_get_b2 (sml_mpl115a2_t dev)
Get b2 coefficient.
int16_t sml_mpl115a2_get_c12 (sml_mpl115a2_t dev)
Get c12 coefficient.
void sml_mpl115a2_convert (sml_mpl115a2_t dev)
Start Pressure and Temperature Conversion.
Detailed Description
Miniature I2C Digital Barometer.
MPL115A2 Digital Barometer
Read out the constants a0, b1, b2 and c12, then convert and finally read back Padc and Tadc
Auto-generated 01 May 2018; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file mpl115a2.h.
Data Structure Documentation
struct sml_mpl115a2_t
Definition at line 23 of file mpl115a2.h.
Data Fields
sml_i2c_regmap_t iic
Function Documentation
sml_mpl115a2_t sml_mpl115a2_create (sml_i2c_t i2c)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
Returns
Device handle
Definition at line 34 of file mpl115a2.h.
References sml_i2c_regmap_create().
 {
     sml_mpl115a2_t dev;
     dev.iic = sml_i2c_regmap_create( i2c, SML_MPL115A2_BASE_ADDR, 0x100, 1 );
     return dev;
 }
void sml_mpl115a2_get_padc (sml_mpl115a2_t dev, int * padc)
Get Pressure ADC output value.
Parameters
dev The device handle
padc pointer to Pressure ADC output value
Definition at line 47 of file mpl115a2.h.
References sml_i2c_regmap_read().
 {
     uint16_t _value;
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x0, 2 );
     _value = ((int)(_bytes[0]) << 8) | (int)(_bytes[1]);
     *padc = (_value >> 6) & 0x3ff;
 }
void sml_mpl115a2_get_tadc (sml_mpl115a2_t dev, int * tadc)
Get Temperature ADC output value.
Parameters
dev The device handle
tadc pointer to Temperature ADC output value
Definition at line 62 of file mpl115a2.h.
References sml_i2c_regmap_read().
 {
     uint16_t _value;
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x2, 2 );
     _value = ((int)(_bytes[0]) << 8) | (int)(_bytes[1]);
     *tadc = (_value >> 6) & 0x3ff;
 }
int16_t sml_mpl115a2_get_a0 (sml_mpl115a2_t dev)
Get a0 coefficient.
Parameters
dev The device handle
Returns
a0 coefficient
Definition at line 77 of file mpl115a2.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x4, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpl115a2_get_b1 (sml_mpl115a2_t dev)
Get b1 coefficient.
Parameters
dev The device handle
Returns
b1 coefficient
Definition at line 90 of file mpl115a2.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x6, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpl115a2_get_b2 (sml_mpl115a2_t dev)
Get b2 coefficient.
Parameters
dev The device handle
Returns
b2 coefficient
Definition at line 103 of file mpl115a2.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x8, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpl115a2_get_c12 (sml_mpl115a2_t dev)
Get c12 coefficient.
Parameters
dev The device handle
Returns
c12 coefficient
Definition at line 116 of file mpl115a2.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0xa, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_mpl115a2_convert (sml_mpl115a2_t dev)
Start Pressure and Temperature Conversion.
Parameters
dev The device handle
Definition at line 128 of file mpl115a2.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = 0;
     sml_i2c_regmap_write( dev.iic, &_value, 0x12, 1 );
 }