ScriptML C API: resources/c/include/scriptml/mpu6050.h File Reference
mpu6050.h File Reference
MPU6050 device driver.
#include <i2c_regmap.h>
#include <gpio.h>
Data Structures
struct sml_mpu6050_t
Macros
#define SML_MPU6050_BASE_ADDR 0x68
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_ACCEL_YOUT 0x6
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_GYRO_XOUT 0x2
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_GYRO_ZOUT 0x4
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_ACCEL_ZOUT 0x7
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_DISABLED 0x0
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_TEMP_OUT 0x1
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_ACCEL_XOUT 0x5
#define SML_MPU6050_CONFIG_EXT_SYNC_SET_GYRO_YOUT 0x3
#define SML_MPU6050_GYRO_CONFIG_FS_SEL_250 0x0
#define SML_MPU6050_GYRO_CONFIG_FS_SEL_2000 0x3
#define SML_MPU6050_GYRO_CONFIG_FS_SEL_500 0x1
#define SML_MPU6050_GYRO_CONFIG_FS_SEL_1000 0x2
#define SML_MPU6050_ACCEL_CONFIG_AFS_SEL_8 0x2
#define SML_MPU6050_ACCEL_CONFIG_AFS_SEL_2 0x0
#define SML_MPU6050_ACCEL_CONFIG_AFS_SEL_4 0x1
#define SML_MPU6050_ACCEL_CONFIG_AFS_SEL_16 0x3
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_PLL_19M 0x5
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_STOP 0x7
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_INTERNAL 0x0
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_PLL_X 0x1
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_PLL_Y 0x2
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_PLL_Z 0x3
#define SML_MPU6050_PWR_MGMT_1_CLKSEL_PLL_32K 0x4
#define SML_MPU6050_PWR_MGMT_2_LP_WAKE_CTRL_20 0x2
#define SML_MPU6050_PWR_MGMT_2_LP_WAKE_CTRL_1_25 0x0
#define SML_MPU6050_PWR_MGMT_2_LP_WAKE_CTRL_5 0x1
#define SML_MPU6050_PWR_MGMT_2_LP_WAKE_CTRL_40 0x3
Functions
sml_mpu6050_t sml_mpu6050_create (sml_i2c_t i2c, int addr_offset, sml_gpio_handle_t intr_pin)
Create device driver instance.
void sml_mpu6050_set_smprt_div (sml_mpu6050_t dev, uint8_t smprt_div)
Set sample rate divisor.
uint8_t sml_mpu6050_get_smprt_div (sml_mpu6050_t dev)
Get sample rate divisor.
void sml_mpu6050_set_config (sml_mpu6050_t dev, int ext_sync_set, int dlpf_cfg)
Set configuration.
void sml_mpu6050_set_gyro_config (sml_mpu6050_t dev, int fs_sel)
Set gyroscope configuration.
void sml_mpu6050_set_accel_config (sml_mpu6050_t dev, int afs_sel)
Set accelerometer configuration.
void sml_mpu6050_set_fifo_en (sml_mpu6050_t dev, int temp_fifo_en, int xg_fifo_en, int yg_fifo_en, int zg_fifo_en, int accel_fifo_en, int slv2_fifo_en, int slv1_fifo_en, int slv0_fifo_en)
Set FIFO enable.
void sml_mpu6050_set_int_pin_cfg (sml_mpu6050_t dev, int int_level, int int_open, int latch_int_en, int int_rd_clear, int fsync_int_level, int fsync_int_en, int i2c_bypass_en)
Set int pin/bypass enable configuration.
void sml_mpu6050_set_int_enable (sml_mpu6050_t dev, int fifo_oflow_en, int i2c_mst_int_en, int data_ready_en)
Set interrupt enable.
void sml_mpu6050_get_int_status (sml_mpu6050_t dev, int *fifo_oflow_int, int *i2c_mst_int_int, int *data_ready_int)
Get interrupt status.
int16_t sml_mpu6050_get_accel_xout (sml_mpu6050_t dev)
Get accelerometer measurement.
int16_t sml_mpu6050_get_accel_yout (sml_mpu6050_t dev)
Get accelerometer measurement.
int16_t sml_mpu6050_get_accel_zout (sml_mpu6050_t dev)
Get accelerometer measurement.
int16_t sml_mpu6050_get_temp_out (sml_mpu6050_t dev)
Get temperature measurement.
int16_t sml_mpu6050_get_gyro_xout (sml_mpu6050_t dev)
Get gyroscope measurement.
int16_t sml_mpu6050_get_gyro_yout (sml_mpu6050_t dev)
Get gyroscope measurement.
int16_t sml_mpu6050_get_gyro_zout (sml_mpu6050_t dev)
Get gyroscope measurement.
void sml_mpu6050_set_signal_path_reset (sml_mpu6050_t dev, int gyro_reset, int accel_reset, int temp_reset)
Set signal path reset.
void sml_mpu6050_set_user_ctrl (sml_mpu6050_t dev, int fifo_en, int i2c_mst_en, int i2c_if_dis, int fifo_reset, int i2c_mst_reset, int sig_cond_reset)
Set user control.
void sml_mpu6050_set_pwr_mgmt_1 (sml_mpu6050_t dev, int device_reset, int sleep, int cycle, int temp_dis, int clksel)
Set power management 1.
void sml_mpu6050_set_pwr_mgmt_2 (sml_mpu6050_t dev, int lp_wake_ctrl, int stby_xa, int stby_ya, int stby_za, int stby_xg, int stby_yg, int stby_zg)
Set power management 2.
uint16_t sml_mpu6050_get_fifo_count (sml_mpu6050_t dev)
Get FIFO count register.
void sml_mpu6050_set_fifo_r_w (sml_mpu6050_t dev, uint8_t fifo_r_w)
Set FIFO read write.
uint8_t sml_mpu6050_get_fifo_r_w (sml_mpu6050_t dev)
Get FIFO read write.
void sml_mpu6050_get_who_am_i (sml_mpu6050_t dev, int *who_am_i)
Get who am I.
Detailed Description
MPU6050 device driver.
MPU5060 Digital Gyroscope and Accelerometer
Read who_am_i to confirm device presence.
Write pwr_mgmt_1 and pwr_mgmt_2 to configure the device and take it out of sleep.
Read raw values from accel_xout etc and gyro_xout etc.
Perform conversions as specified by the data sheet.
Auto-generated 28 May 2018; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file mpu6050.h.
Data Structure Documentation
struct sml_mpu6050_t
Definition at line 64 of file mpu6050.h.
Data Fields
sml_i2c_regmap_t iic
sml_gpio_handle_t intr_gpio
Function Documentation
sml_mpu6050_t sml_mpu6050_create (sml_i2c_t i2c, int addr_offset, sml_gpio_handle_t intr_pin)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
addr_offset The I2C address offset
intr_pin An instance of the GPIO driver for the pin connected to the interrupt line
Returns
Device handle
Definition at line 78 of file mpu6050.h.
References sml_i2c_regmap_create().
 {
     sml_mpu6050_t dev;
     dev.intr_gpio = intr_pin;
     dev.iic = sml_i2c_regmap_create( i2c, SML_MPU6050_BASE_ADDR + addr_offset, 0x100, 1 );
     return dev;
 }
void sml_mpu6050_set_smprt_div (sml_mpu6050_t dev, uint8_t smprt_div)
Set sample rate divisor.
Parameters
dev The device handle
smprt_div sample rate divisor
Definition at line 92 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &smprt_div, 0x19, 1 );
 }
uint8_t sml_mpu6050_get_smprt_div (sml_mpu6050_t dev)
Get sample rate divisor.
Parameters
dev The device handle
Returns
sample rate divisor
Definition at line 103 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x19, 1 );
     return _bytes[0];
 }
void sml_mpu6050_set_config (sml_mpu6050_t dev, int ext_sync_set, int dlpf_cfg)
Set configuration.
Parameters
dev The device handle
ext_sync_set external frame sync
dlpf_cfg digital low-pass filter
Definition at line 117 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((ext_sync_set & 0x7) << 3) | (dlpf_cfg & 0x7);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1a, 1 );
 }
void sml_mpu6050_set_gyro_config (sml_mpu6050_t dev, int fs_sel)
Set gyroscope configuration.
Parameters
dev The device handle
fs_sel full-scale selection
Definition at line 130 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((fs_sel & 0x3) << 3);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1b, 1 );
 }
void sml_mpu6050_set_accel_config (sml_mpu6050_t dev, int afs_sel)
Set accelerometer configuration.
Parameters
dev The device handle
afs_sel accelerometer full-scale selection
Definition at line 143 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((afs_sel & 0x3) << 3);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1c, 1 );
 }
void sml_mpu6050_set_fifo_en (sml_mpu6050_t dev, int temp_fifo_en, int xg_fifo_en, int yg_fifo_en, int zg_fifo_en, int accel_fifo_en, int slv2_fifo_en, int slv1_fifo_en, int slv0_fifo_en)
Set FIFO enable.
Parameters
dev The device handle
temp_fifo_en enable TEMP_OUT to be written to FIFO
xg_fifo_en enable GYRO_XOUT to be written to FIFO
yg_fifo_en enable GYRO_YOUT to be written to FIFO
zg_fifo_en enable GYRO_ZOUT to be written to FIFO
accel_fifo_en enable ACCEL_XOUT, ACCEL_YOUT and ACCEL_ZOUT to be written to FIFO
slv2_fifo_en enable EXT_SENS_DATA for slave 2 to be written to FIFO
slv1_fifo_en enable EXT_SENS_DATA for slave 1 to be written to FIFO
slv0_fifo_en enable EXT_SENS_DATA for slave 0 to be written to FIFO
Definition at line 163 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((temp_fifo_en & 0x1) << 7) | ((xg_fifo_en & 0x1) << 6) | ((yg_fifo_en & 0x1) << 5) | ((zg_fifo_en & 0x1) << 4) | ((accel_fifo_en & 0x1) << 3) | ((slv2_fifo_en & 0x1) << 2) | ((slv1_fifo_en & 0x1) << 1) | (slv0_fifo_en & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x23, 1 );
 }
void sml_mpu6050_set_int_pin_cfg (sml_mpu6050_t dev, int int_level, int int_open, int latch_int_en, int int_rd_clear, int fsync_int_level, int fsync_int_en, int i2c_bypass_en)
Set int pin/bypass enable configuration.
Parameters
dev The device handle
int_level int pin active low
int_open int pin open drain
latch_int_en int pin held high until int cleared
int_rd_clear int bit cleared by any read
fsync_int_level FSYNC int pin active low
fsync_int_en enable FSYNC int
i2c_bypass_en enable host access to aux I2C
Definition at line 182 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((int_level & 0x1) << 7) | ((int_open & 0x1) << 6) | ((latch_int_en & 0x1) << 5) | ((int_rd_clear & 0x1) << 4) | ((fsync_int_level & 0x1) << 3) | ((fsync_int_en & 0x1) << 2) | ((i2c_bypass_en & 0x1) << 1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x37, 1 );
 }
void sml_mpu6050_set_int_enable (sml_mpu6050_t dev, int fifo_oflow_en, int i2c_mst_int_en, int data_ready_en)
Set interrupt enable.
Parameters
dev The device handle
fifo_oflow_en enable FIFO overflow interrupt
i2c_mst_int_en enable master I2C interrupt
data_ready_en enable data ready I2C interrupt
Definition at line 197 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((fifo_oflow_en & 0x1) << 4) | ((i2c_mst_int_en & 0x1) << 3) | (data_ready_en & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x38, 1 );
 }
void sml_mpu6050_get_int_status (sml_mpu6050_t dev, int * fifo_oflow_int, int * i2c_mst_int_int, int * data_ready_int)
Get interrupt status.
Parameters
dev The device handle
fifo_oflow_int pointer to FIFO overflow interrupt generated bit
i2c_mst_int_int pointer to master I2C interrupt generated bit
data_ready_int pointer to data ready I2C interrupt generated bit
Definition at line 212 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x3a, 1 );
     *fifo_oflow_int = (_bytes[0] >> 4) & 0x1;
     *i2c_mst_int_int = (_bytes[0] >> 3) & 0x1;
     *data_ready_int = _bytes[0] & 0x1;
 }
int16_t sml_mpu6050_get_accel_xout (sml_mpu6050_t dev)
Get accelerometer measurement.
Parameters
dev The device handle
Returns
accelerometer measurement
Definition at line 227 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x3b, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpu6050_get_accel_yout (sml_mpu6050_t dev)
Get accelerometer measurement.
Parameters
dev The device handle
Returns
accelerometer measurement
Definition at line 240 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x3d, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpu6050_get_accel_zout (sml_mpu6050_t dev)
Get accelerometer measurement.
Parameters
dev The device handle
Returns
accelerometer measurement
Definition at line 253 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x3f, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpu6050_get_temp_out (sml_mpu6050_t dev)
Get temperature measurement.
Parameters
dev The device handle
Returns
temperature measurement
Definition at line 266 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x41, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpu6050_get_gyro_xout (sml_mpu6050_t dev)
Get gyroscope measurement.
Parameters
dev The device handle
Returns
gyroscope measurement
Definition at line 279 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x43, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpu6050_get_gyro_yout (sml_mpu6050_t dev)
Get gyroscope measurement.
Parameters
dev The device handle
Returns
gyroscope measurement
Definition at line 292 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x45, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
int16_t sml_mpu6050_get_gyro_zout (sml_mpu6050_t dev)
Get gyroscope measurement.
Parameters
dev The device handle
Returns
gyroscope measurement
Definition at line 305 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x47, 2 );
     return (int16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_mpu6050_set_signal_path_reset (sml_mpu6050_t dev, int gyro_reset, int accel_reset, int temp_reset)
Set signal path reset.
Parameters
dev The device handle
gyro_reset reset gyroscope analog and digital signal paths
accel_reset reset accelerometer analog and digital signal paths
temp_reset reset temperature sensor analog and digital signal paths
Definition at line 320 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((gyro_reset & 0x1) << 2) | ((accel_reset & 0x1) << 1) | (temp_reset & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x68, 1 );
 }
void sml_mpu6050_set_user_ctrl (sml_mpu6050_t dev, int fifo_en, int i2c_mst_en, int i2c_if_dis, int fifo_reset, int i2c_mst_reset, int sig_cond_reset)
Set user control.
Parameters
dev The device handle
fifo_en enable FIFO operations
i2c_mst_en enable I2C master mode
i2c_if_dis disable I2C interface
fifo_reset reset FIFO buffer
i2c_mst_reset reset I2C master
sig_cond_reset reset signal paths and interrupt condition
Definition at line 338 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((fifo_en & 0x1) << 6) | ((i2c_mst_en & 0x1) << 5) | ((i2c_if_dis & 0x1) << 4) | ((fifo_reset & 0x1) << 2) | ((i2c_mst_reset & 0x1) << 1) | (sig_cond_reset & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x6a, 1 );
 }
void sml_mpu6050_set_pwr_mgmt_1 (sml_mpu6050_t dev, int device_reset, int sleep, int cycle, int temp_dis, int clksel)
Set power management 1.
Parameters
dev The device handle
device_reset reset the entire device
sleep low power sleep mode
cycle cycle between sleep and sampling
temp_dis disable temperature sensor
clksel clock source
Definition at line 355 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((device_reset & 0x1) << 7) | ((sleep & 0x1) << 6) | ((cycle & 0x1) << 5) | ((temp_dis & 0x1) << 3) | (clksel & 0x7);
     sml_i2c_regmap_write( dev.iic, &_value, 0x6b, 1 );
 }
void sml_mpu6050_set_pwr_mgmt_2 (sml_mpu6050_t dev, int lp_wake_ctrl, int stby_xa, int stby_ya, int stby_za, int stby_xg, int stby_yg, int stby_zg)
Set power management 2.
Parameters
dev The device handle
lp_wake_ctrl low power wakeup frequency
stby_xa x-axis accelerometer into standby mode
stby_ya y-axis accelerometer into standby mode
stby_za z-axis accelerometer into standby mode
stby_xg x-axis gyroscope into standby mode
stby_yg y-axis gyroscope into standby mode
stby_zg z-axis gyroscope into standby mode
Definition at line 374 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((lp_wake_ctrl & 0x3) << 6) | ((stby_xa & 0x1) << 5) | ((stby_ya & 0x1) << 4) | ((stby_za & 0x1) << 3) | ((stby_xg & 0x1) << 2) | ((stby_yg & 0x1) << 1) | (stby_zg & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x6c, 1 );
 }
uint16_t sml_mpu6050_get_fifo_count (sml_mpu6050_t dev)
Get FIFO count register.
Parameters
dev The device handle
Returns
FIFO count register
Definition at line 387 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[2];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x72, 2 );
     return (uint16_t)(((int)(_bytes[0]) << 8) | (int)(_bytes[1]));
 }
void sml_mpu6050_set_fifo_r_w (sml_mpu6050_t dev, uint8_t fifo_r_w)
Set FIFO read write.
Parameters
dev The device handle
fifo_r_w FIFO read write
Definition at line 400 of file mpu6050.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &fifo_r_w, 0x74, 1 );
 }
uint8_t sml_mpu6050_get_fifo_r_w (sml_mpu6050_t dev)
Get FIFO read write.
Parameters
dev The device handle
Returns
FIFO read write
Definition at line 411 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x74, 1 );
     return _bytes[0];
 }
void sml_mpu6050_get_who_am_i (sml_mpu6050_t dev, int * who_am_i)
Get who am I.
Parameters
dev The device handle
who_am_i pointer to who am I
Definition at line 424 of file mpu6050.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x75, 1 );
     *who_am_i = (_bytes[0] >> 1) & 0x3f;
 }