ScriptML C API: resources/c/include/scriptml/pca9685.h File Reference
pca9685.h File Reference
16-channel, 12-bit PWM Fm+ I2C-bus LED Controller
#include <i2c_regmap.h>
Data Structures
struct sml_pca9685_t
Macros
#define SML_PCA9685_BASE_ADDR 0x40
#define SML_PCA9685_MODE2_OCH_STOP_COMMAND 0x0
#define SML_PCA9685_MODE2_OCH_ACK 0x1
#define SML_PCA9685_MODE2_OUTDRV_OPEN_DRAIN 0x0
#define SML_PCA9685_MODE2_OUTDRV_TOTEM_POLE 0x1
#define SML_PCA9685_MODE2_OUTNE_0 0x0
#define SML_PCA9685_MODE2_OUTNE_1 0x1
#define SML_PCA9685_MODE2_OUTNE_HI_Z 0x2
Functions
sml_pca9685_t sml_pca9685_create (sml_i2c_t i2c, int addr_offset)
Create device driver instance.
void sml_pca9685_set_mode1 (sml_pca9685_t dev, int restart, int extclk, int ai, int sleep, int sub1, int sub2, int sub3, int allcall)
Set mode register 1.
void sml_pca9685_get_mode1 (sml_pca9685_t dev, int *restart, int *extclk, int *ai, int *sleep, int *sub1, int *sub2, int *sub3, int *allcall)
Get mode register 1.
void sml_pca9685_set_mode2 (sml_pca9685_t dev, int invrt, int och, int outdrv, int outne)
Set mode register 2.
void sml_pca9685_set_subadr (sml_pca9685_t dev, int channel, uint8_t subadr)
Set I2C-bus subaddress.
void sml_pca9685_set_led_on_off (sml_pca9685_t dev, int channel, int on_count, int full_on, int off_count, int full_off)
Set LED output and brightness control.
void sml_pca9685_set_all_led_on_off (sml_pca9685_t dev, int on_count, int full_on, int off_count, int full_off)
Set all the LED control registers.
void sml_pca9685_set_pre_scale (sml_pca9685_t dev, uint8_t pre_scale)
Set prescaler for PWM output frequency.
Detailed Description
16-channel, 12-bit PWM Fm+ I2C-bus LED Controller
PCA9685 PWM LED Driver
The internal clock is 25MHz
The PWM waveform frequency is clock frequency / (pre_scale * 4096)
The device powers up in sleep mode, and must be powered up by clearing the sleep! bit in themode1` register before use.
The ai bit in register mode1 must be set before any of the led_on_off APIs will function correctly, because they use auto-increment to access multiple registers efficiently.
The device must be in sleep mode before the pre_scale register can be updated.
Wakeup procedure: clear sleep bit of register mode1. Wait at least 500us for the clock to stabilise. set restart bit of mode1 register.
Auto-generated 28 April 2018; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file pca9685.h.
Data Structure Documentation
struct sml_pca9685_t
Definition at line 41 of file pca9685.h.
Data Fields
sml_i2c_regmap_t iic
Function Documentation
sml_pca9685_t sml_pca9685_create (sml_i2c_t i2c, int addr_offset)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
addr_offset The I2C address offset
Returns
Device handle
Definition at line 53 of file pca9685.h.
References sml_i2c_regmap_create().
 {
     sml_pca9685_t dev;
     dev.iic = sml_i2c_regmap_create( i2c, SML_PCA9685_BASE_ADDR + addr_offset, 0x100, 1 );
     return dev;
 }
void sml_pca9685_set_mode1 (sml_pca9685_t dev, int restart, int extclk, int ai, int sleep, int sub1, int sub2, int sub3, int allcall)
Set mode register 1.
Parameters
dev The device handle
restart RESTART logic state and reset
extclk external Clock
ai register auto-increment enable
sleep low power mode
sub1 PCA9685 responds to I2C-bus subaddress 1
sub2 PCA9685 responds to I2C-bus subaddress 2
sub3 PCA9685 responds to I2C-bus subaddress 3
allcall PCA9685 responds to LED All Call I2C-bus
Definition at line 73 of file pca9685.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((restart & 0x1) << 7) | ((extclk & 0x1) << 6) | ((ai & 0x1) << 5) | ((sleep & 0x1) << 4) | ((sub1 & 0x1) << 3) | ((sub2 & 0x1) << 2) | ((sub3 & 0x1) << 1) | (allcall & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x0, 1 );
 }
void sml_pca9685_get_mode1 (sml_pca9685_t dev, int * restart, int * extclk, int * ai, int * sleep, int * sub1, int * sub2, int * sub3, int * allcall)
Get mode register 1.
Parameters
dev The device handle
restart pointer to RESTART logic state and reset bit
extclk pointer to external Clock bit
ai pointer to register auto-increment enable bit
sleep pointer to low power mode bit
sub1 pointer to PCA9685 responds to I2C-bus subaddress 1 bit
sub2 pointer to PCA9685 responds to I2C-bus subaddress 2 bit
sub3 pointer to PCA9685 responds to I2C-bus subaddress 3 bit
allcall pointer to PCA9685 responds to LED All Call I2C-bus bit
Definition at line 93 of file pca9685.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x0, 1 );
     *restart = (_bytes[0] >> 7) & 0x1;
     *extclk = (_bytes[0] >> 6) & 0x1;
     *ai = (_bytes[0] >> 5) & 0x1;
     *sleep = (_bytes[0] >> 4) & 0x1;
     *sub1 = (_bytes[0] >> 3) & 0x1;
     *sub2 = (_bytes[0] >> 2) & 0x1;
     *sub3 = (_bytes[0] >> 1) & 0x1;
     *allcall = _bytes[0] & 0x1;
 }
void sml_pca9685_set_mode2 (sml_pca9685_t dev, int invrt, int och, int outdrv, int outne)
Set mode register 2.
Parameters
dev The device handle
invrt output logic state inverted
och output change on
outdrv LEDn output configuration (when enabled)
outne LEDn output configuration when ~OE = 1 (output drivers not enabled)
Definition at line 116 of file pca9685.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((invrt & 0x1) << 4) | ((och & 0x1) << 3) | ((outdrv & 0x1) << 2) | (outne & 0x3);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1, 1 );
 }
void sml_pca9685_set_subadr (sml_pca9685_t dev, int channel, uint8_t subadr)
Set I2C-bus subaddress.
Parameters
dev The device handle
channel Channel number; 0 to 2
subadr I2C-bus subaddress
Definition at line 130 of file pca9685.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &subadr, 0x2+channel, 1 );
 }
void sml_pca9685_set_led_on_off (sml_pca9685_t dev, int channel, int on_count, int full_on, int off_count, int full_off)
Set LED output and brightness control.
Parameters
dev The device handle
channel Channel number; 0 to 15
on_count LED on count
full_on LED full on
off_count LED off count
full_off LED full off
Definition at line 145 of file pca9685.h.
References sml_i2c_regmap_write().
 {
     uint32_t _value;
     uint8_t _bytes[4];
     _value = (on_count & 0xfff) | ((full_on & 0x1) << 12) | ((off_count & 0xfff) << 16) | ((full_off & 0x1) << 28);
     _bytes[0] = _value & 0xff;
     _bytes[1] = (_value >> 8) & 0xff;
     _bytes[2] = (_value >> 16) & 0xff;
     _bytes[3] = (_value >> 24) & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0x6+channel*4, 4 );
 }
void sml_pca9685_set_all_led_on_off (sml_pca9685_t dev, int on_count, int full_on, int off_count, int full_off)
Set all the LED control registers.
Parameters
dev The device handle
on_count LED on count
full_on LED full on
off_count LED off count
full_off LED full off
Definition at line 166 of file pca9685.h.
References sml_i2c_regmap_write().
 {
     uint32_t _value;
     uint8_t _bytes[4];
     _value = (on_count & 0xfff) | ((full_on & 0x1) << 12) | ((off_count & 0xfff) << 16) | ((full_off & 0x1) << 28);
     _bytes[0] = _value & 0xff;
     _bytes[1] = (_value >> 8) & 0xff;
     _bytes[2] = (_value >> 16) & 0xff;
     _bytes[3] = (_value >> 24) & 0xff;
     sml_i2c_regmap_write( dev.iic, _bytes, 0xfa, 4 );
 }
void sml_pca9685_set_pre_scale (sml_pca9685_t dev, uint8_t pre_scale)
Set prescaler for PWM output frequency.
Parameters
dev The device handle
pre_scale prescaler for PWM output frequency
Definition at line 184 of file pca9685.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &pre_scale, 0xfe, 1 );
 }