ScriptML C API: resources/c/include/scriptml/pca9534.h File Reference
pca9534.h File Reference
GPIO Extender.
#include <i2c_regmap.h>
#include <gpio.h>
Data Structures
struct sml_pca9534_t
Macros
#define SML_PCA9534_BASE_ADDR 0x20
Functions
sml_pca9534_t sml_pca9534_create (sml_i2c_t i2c, int addr_offset, sml_gpio_handle_t intr_pin)
Create device driver instance.
uint8_t sml_pca9534_get_input (sml_pca9534_t dev)
Get Input Port register.
void sml_pca9534_set_output (sml_pca9534_t dev, uint8_t output)
Set Output Port register.
uint8_t sml_pca9534_get_output (sml_pca9534_t dev)
Get Output Port register.
void sml_pca9534_set_polarity (sml_pca9534_t dev, uint8_t polarity)
Set Polarity Inversion register.
uint8_t sml_pca9534_get_polarity (sml_pca9534_t dev)
Get Polarity Inversion register.
void sml_pca9534_set_configuration (sml_pca9534_t dev, uint8_t configuration)
Set Configuration register.
uint8_t sml_pca9534_get_configuration (sml_pca9534_t dev)
Get Configuration register.
Detailed Description
GPIO Extender.
8-bit I2C-bus and SMBus low power I/O port with interrupt
Configuration register is really a direction register. Bits set to 1 correspond to inputs and 0 to outputs.
Auto-generated 28 October 2017; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file pca9534.h.
Data Structure Documentation
struct sml_pca9534_t
Definition at line 26 of file pca9534.h.
Data Fields
sml_i2c_regmap_t iic
sml_gpio_handle_t intr_gpio
Function Documentation
sml_pca9534_t sml_pca9534_create (sml_i2c_t i2c, int addr_offset, sml_gpio_handle_t intr_pin)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
addr_offset The I2C address offset
intr_pin An instance of the GPIO driver for the pin connected to the interrupt line
Returns
Device handle
Definition at line 40 of file pca9534.h.
References sml_i2c_regmap_create().
 {
     sml_pca9534_t dev;
     dev.intr_gpio = intr_pin;
     dev.iic = sml_i2c_regmap_create( i2c, SML_PCA9534_BASE_ADDR + addr_offset, 0x100, 1 );
     return dev;
 }
uint8_t sml_pca9534_get_input (sml_pca9534_t dev)
Get Input Port register.
Parameters
dev The device handle
Returns
Input Port register
Definition at line 54 of file pca9534.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x0, 1 );
     return _bytes[0];
 }
void sml_pca9534_set_output (sml_pca9534_t dev, uint8_t output)
Set Output Port register.
Parameters
dev The device handle
output Output Port register
Definition at line 67 of file pca9534.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &output, 0x1, 1 );
 }
uint8_t sml_pca9534_get_output (sml_pca9534_t dev)
Get Output Port register.
Parameters
dev The device handle
Returns
Output Port register
Definition at line 78 of file pca9534.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x1, 1 );
     return _bytes[0];
 }
void sml_pca9534_set_polarity (sml_pca9534_t dev, uint8_t polarity)
Set Polarity Inversion register.
Parameters
dev The device handle
polarity Polarity Inversion register
Definition at line 91 of file pca9534.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &polarity, 0x2, 1 );
 }
uint8_t sml_pca9534_get_polarity (sml_pca9534_t dev)
Get Polarity Inversion register.
Parameters
dev The device handle
Returns
Polarity Inversion register
Definition at line 102 of file pca9534.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x2, 1 );
     return _bytes[0];
 }
void sml_pca9534_set_configuration (sml_pca9534_t dev, uint8_t configuration)
Set Configuration register.
Parameters
dev The device handle
configuration Configuration register
Definition at line 115 of file pca9534.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &configuration, 0x3, 1 );
 }
uint8_t sml_pca9534_get_configuration (sml_pca9534_t dev)
Get Configuration register.
Parameters
dev The device handle
Returns
Configuration register
Definition at line 126 of file pca9534.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x3, 1 );
     return _bytes[0];
 }