ScriptML C API: resources/c/include/scriptml/pcf8563.h File Reference
pcf8563.h File Reference
Real-time clock.
#include <i2c_regmap.h>
#include <gpio.h>
Data Structures
struct sml_pcf8563_t
Macros
#define SML_PCF8563_BASE_ADDR 0x51
#define SML_PCF8563_CONTROL_STATUS_1_STOP_RTC_RUNS 0x0
#define SML_PCF8563_CONTROL_STATUS_1_STOP_RTC_STOPPED 0x1
#define SML_PCF8563_CONTROL_STATUS_2_TI_TP_TF_ACTIVE 0x0
#define SML_PCF8563_CONTROL_STATUS_2_TI_TP_PULSE 0x0
#define SML_PCF8563_VL_AND_TIME_COMBINED_VL_GUARANTEED 0x0
#define SML_PCF8563_VL_AND_TIME_COMBINED_VL_NOT_GUARANTEED 0x1
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_SUNDAY 0x0
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_MONDAY 0x1
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_TUESDAY 0x2
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_WEDNSDAY 0x3
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_THURSDAY 0x4
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_FRIDAY 0x5
#define SML_PCF8563_VL_AND_TIME_COMBINED_WEEKDAYS_SATURDAY 0x6
#define SML_PCF8563_CLKOUT_CONTROL_FD_32KHZ 0x0
#define SML_PCF8563_CLKOUT_CONTROL_FD_1KHZ 0x1
#define SML_PCF8563_CLKOUT_CONTROL_FD_32HZ 0x2
#define SML_PCF8563_CLKOUT_CONTROL_FD_1HZ 0x3
#define SML_PCF8563_TIMER_CONTROL_TD_4KHZ 0x0
#define SML_PCF8563_TIMER_CONTROL_TD_64HZ 0x1
#define SML_PCF8563_TIMER_CONTROL_TD_1HZ 0x2
#define SML_PCF8563_TIMER_CONTROL_TD_1_60HZ 0x3
Functions
sml_pcf8563_t sml_pcf8563_create (sml_i2c_t i2c, sml_gpio_handle_t intr_pin)
Create device driver instance.
void sml_pcf8563_set_control_status_1 (sml_pcf8563_t dev, int stop)
Set Control and status register 1.
void sml_pcf8563_get_control_status_1 (sml_pcf8563_t dev, int *stop)
Get Control and status register 1.
void sml_pcf8563_set_control_status_2 (sml_pcf8563_t dev, int ti_tp, int af, int tf, int aie, int tie)
Set Control and status register 2.
void sml_pcf8563_get_control_status_2 (sml_pcf8563_t dev, int *ti_tp, int *af, int *tf, int *aie, int *tie)
Get Control and status register 2.
void sml_pcf8563_set_vl_and_time_combined (sml_pcf8563_t dev, int vl, int seconds_units, int seconds_tens, int minutes_units, int minutes_tens, int hours_units, int hours_tens, int days_units, int days_tens, int weekdays, int century, int months_units, int months_tens, int years_units, int years_tens)
Set All current time fields; must be a single access for coherency.
void sml_pcf8563_get_vl_and_time_combined (sml_pcf8563_t dev, int *vl, int *seconds_units, int *seconds_tens, int *minutes_units, int *minutes_tens, int *hours_units, int *hours_tens, int *days_units, int *days_tens, int *weekdays, int *century, int *months_units, int *months_tens, int *years_units, int *years_tens)
Get All current time fields; must be a single access for coherency.
void sml_pcf8563_set_minute_alarm (sml_pcf8563_t dev, int ae_m, int minutes_units, int minutes_tens)
Set Alarm minutes.
void sml_pcf8563_get_minute_alarm (sml_pcf8563_t dev, int *ae_m, int *minutes_units, int *minutes_tens)
Get Alarm minutes.
void sml_pcf8563_set_hour_alarm (sml_pcf8563_t dev, int ae_h, int hours_units, int hours_tens)
Set Alarm hours.
void sml_pcf8563_get_hour_alarm (sml_pcf8563_t dev, int *ae_h, int *hours_units, int *hours_tens)
Get Alarm hours.
void sml_pcf8563_set_day_alarm (sml_pcf8563_t dev, int ae_d, int days_units, int days_tens)
Set Alarm days.
void sml_pcf8563_get_day_alarm (sml_pcf8563_t dev, int *ae_d, int *days_units, int *days_tens)
Get Alarm days.
void sml_pcf8563_set_weekday_alarm (sml_pcf8563_t dev, int ae_w, int weekdays)
Set Alarm weekday.
void sml_pcf8563_get_weekday_alarm (sml_pcf8563_t dev, int *ae_w, int *weekdays)
Get Alarm weekday.
void sml_pcf8563_set_clkout_control (sml_pcf8563_t dev, int fe, int fd)
Set CLKOUT control.
void sml_pcf8563_get_clkout_control (sml_pcf8563_t dev, int *fe, int *fd)
Get CLKOUT control.
void sml_pcf8563_set_timer_control (sml_pcf8563_t dev, int te, int td)
Set Timer control.
void sml_pcf8563_get_timer_control (sml_pcf8563_t dev, int *te, int *td)
Get Timer control.
void sml_pcf8563_set_timer (sml_pcf8563_t dev, uint8_t timer)
Set Timer.
uint8_t sml_pcf8563_get_timer (sml_pcf8563_t dev)
Get Timer.
Detailed Description
Real-time clock.
Real-time clock/calendar
Auto-generated 15 January 2018; do not edit
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file pcf8563.h.
Data Structure Documentation
struct sml_pcf8563_t
Definition at line 51 of file pcf8563.h.
Data Fields
sml_i2c_regmap_t iic
sml_gpio_handle_t intr_gpio
Function Documentation
sml_pcf8563_t sml_pcf8563_create (sml_i2c_t i2c, sml_gpio_handle_t intr_pin)
Create device driver instance.
Parameters
i2c An instance of the I2C driver for the bus on which the device is placed
intr_pin An instance of the GPIO driver for the pin connected to the interrupt line
Returns
Device handle
Definition at line 64 of file pcf8563.h.
References sml_i2c_regmap_create().
 {
     sml_pcf8563_t dev;
     dev.intr_gpio = intr_pin;
     dev.iic = sml_i2c_regmap_create( i2c, SML_PCF8563_BASE_ADDR, 0x100, 0 );
     return dev;
 }
void sml_pcf8563_set_control_status_1 (sml_pcf8563_t dev, int stop)
Set Control and status register 1.
Parameters
dev The device handle
stop STOP
Definition at line 78 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((stop & 0x1) << 5);
     sml_i2c_regmap_write( dev.iic, &_value, 0x0, 1 );
 }
void sml_pcf8563_get_control_status_1 (sml_pcf8563_t dev, int * stop)
Get Control and status register 1.
Parameters
dev The device handle
stop pointer to STOP bit
Definition at line 91 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x0, 1 );
     *stop = (_bytes[0] >> 5) & 0x1;
 }
void sml_pcf8563_set_control_status_2 (sml_pcf8563_t dev, int ti_tp, int af, int tf, int aie, int tie)
Set Control and status register 2.
Parameters
dev The device handle
ti_tp Timer interrupt type
af Alarm flag
tf Timer flag
aie Alarm interrupt enable
tie Timer interrupt enable
Definition at line 108 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((ti_tp & 0x1) << 4) | ((af & 0x1) << 3) | ((tf & 0x1) << 2) | ((aie & 0x1) << 1) | (tie & 0x1);
     sml_i2c_regmap_write( dev.iic, &_value, 0x1, 1 );
 }
void sml_pcf8563_get_control_status_2 (sml_pcf8563_t dev, int * ti_tp, int * af, int * tf, int * aie, int * tie)
Get Control and status register 2.
Parameters
dev The device handle
ti_tp pointer to Timer interrupt type bit
af pointer to Alarm flag bit
tf pointer to Timer flag bit
aie pointer to Alarm interrupt enable bit
tie pointer to Timer interrupt enable bit
Definition at line 125 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x1, 1 );
     *ti_tp = (_bytes[0] >> 4) & 0x1;
     *af = (_bytes[0] >> 3) & 0x1;
     *tf = (_bytes[0] >> 2) & 0x1;
     *aie = (_bytes[0] >> 1) & 0x1;
     *tie = _bytes[0] & 0x1;
 }
void sml_pcf8563_set_vl_and_time_combined (sml_pcf8563_t dev, int vl, int seconds_units, int seconds_tens, int minutes_units, int minutes_tens, int hours_units, int hours_tens, int days_units, int days_tens, int weekdays, int century, int months_units, int months_tens, int years_units, int years_tens)
Set All current time fields; must be a single access for coherency.
Parameters
dev The device handle
vl clock integrity status
seconds_units Seconds units place
seconds_tens Seconds tens place
minutes_units Minutes units place
minutes_tens Minutes tens place
hours_units Hours units place
hours_tens Hours tens place
days_units Days units place
days_tens Days tens place
weekdays Weekdays (whole value)
century Century modulo 2
months_units Months units place
months_tens Months tens place
years_units Years units place
years_tens Years tens place
Definition at line 156 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _bytes[7];
     _bytes[0] = ((vl & 0x1) << 7) | (seconds_units & 0xf) | ((seconds_tens & 0x7) << 4);
     _bytes[1] = (minutes_units & 0xf) | ((minutes_tens & 0x7) << 4);
     _bytes[2] = (hours_units & 0xf) | ((hours_tens & 0x3) << 4);
     _bytes[3] = (days_units & 0xf) | ((days_tens & 0x3) << 4);
     _bytes[4] = (weekdays & 0x7);
     _bytes[5] = ((century & 0x1) << 7) | (months_units & 0xf) | ((months_tens & 0x1) << 4);
     _bytes[6] = (years_units & 0xf) | ((years_tens & 0xf) << 4);
     sml_i2c_regmap_write( dev.iic, _bytes, 0x2, 7 );
 }
void sml_pcf8563_get_vl_and_time_combined (sml_pcf8563_t dev, int * vl, int * seconds_units, int * seconds_tens, int * minutes_units, int * minutes_tens, int * hours_units, int * hours_tens, int * days_units, int * days_tens, int * weekdays, int * century, int * months_units, int * months_tens, int * years_units, int * years_tens)
Get All current time fields; must be a single access for coherency.
Parameters
dev The device handle
vl pointer to clock integrity status bit
seconds_units pointer to Seconds units place
seconds_tens pointer to Seconds tens place
minutes_units pointer to Minutes units place
minutes_tens pointer to Minutes tens place
hours_units pointer to Hours units place
hours_tens pointer to Hours tens place
days_units pointer to Days units place
days_tens pointer to Days tens place
weekdays pointer to Weekdays (whole value)
century pointer to Century modulo 2 bit
months_units pointer to Months units place
months_tens pointer to Months tens place bit
years_units pointer to Years units place
years_tens pointer to Years tens place
Definition at line 189 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[7];
     sml_i2c_regmap_read( dev.iic, _bytes, 0x2, 7 );
     *vl = (_bytes[0] >> 7) & 0x1;
     *seconds_units = _bytes[0] & 0xf;
     *seconds_tens = (_bytes[0] >> 4) & 0x7;
     *minutes_units = _bytes[1] & 0xf;
     *minutes_tens = (_bytes[1] >> 4) & 0x7;
     *hours_units = _bytes[2] & 0xf;
     *hours_tens = (_bytes[2] >> 4) & 0x3;
     *days_units = _bytes[3] & 0xf;
     *days_tens = (_bytes[3] >> 4) & 0x3;
     *weekdays = _bytes[4] & 0x7;
     *century = (_bytes[5] >> 7) & 0x1;
     *months_units = _bytes[5] & 0xf;
     *months_tens = (_bytes[5] >> 4) & 0x1;
     *years_units = _bytes[6] & 0xf;
     *years_tens = (_bytes[6] >> 4) & 0xf;
 }
void sml_pcf8563_set_minute_alarm (sml_pcf8563_t dev, int ae_m, int minutes_units, int minutes_tens)
Set Alarm minutes.
Parameters
dev The device handle
ae_m Minute alarm disable
minutes_units Minutes units place
minutes_tens Minutes tens place
Definition at line 218 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((ae_m & 0x1) << 7) | (minutes_units & 0xf) | ((minutes_tens & 0x7) << 4);
     sml_i2c_regmap_write( dev.iic, &_value, 0x9, 1 );
 }
void sml_pcf8563_get_minute_alarm (sml_pcf8563_t dev, int * ae_m, int * minutes_units, int * minutes_tens)
Get Alarm minutes.
Parameters
dev The device handle
ae_m pointer to Minute alarm disable bit
minutes_units pointer to Minutes units place
minutes_tens pointer to Minutes tens place
Definition at line 233 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0x9, 1 );
     *ae_m = (_bytes[0] >> 7) & 0x1;
     *minutes_units = _bytes[0] & 0xf;
     *minutes_tens = (_bytes[0] >> 4) & 0x7;
 }
void sml_pcf8563_set_hour_alarm (sml_pcf8563_t dev, int ae_h, int hours_units, int hours_tens)
Set Alarm hours.
Parameters
dev The device handle
ae_h Hour alarm disable
hours_units Hours units place
hours_tens Hours tens place
Definition at line 250 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((ae_h & 0x1) << 7) | (hours_units & 0xf) | ((hours_tens & 0x3) << 4);
     sml_i2c_regmap_write( dev.iic, &_value, 0xa, 1 );
 }
void sml_pcf8563_get_hour_alarm (sml_pcf8563_t dev, int * ae_h, int * hours_units, int * hours_tens)
Get Alarm hours.
Parameters
dev The device handle
ae_h pointer to Hour alarm disable bit
hours_units pointer to Hours units place
hours_tens pointer to Hours tens place
Definition at line 265 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0xa, 1 );
     *ae_h = (_bytes[0] >> 7) & 0x1;
     *hours_units = _bytes[0] & 0xf;
     *hours_tens = (_bytes[0] >> 4) & 0x3;
 }
void sml_pcf8563_set_day_alarm (sml_pcf8563_t dev, int ae_d, int days_units, int days_tens)
Set Alarm days.
Parameters
dev The device handle
ae_d Day alarm disable
days_units Days units place
days_tens Days tens place
Definition at line 282 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((ae_d & 0x1) << 7) | (days_units & 0xf) | ((days_tens & 0x3) << 4);
     sml_i2c_regmap_write( dev.iic, &_value, 0xb, 1 );
 }
void sml_pcf8563_get_day_alarm (sml_pcf8563_t dev, int * ae_d, int * days_units, int * days_tens)
Get Alarm days.
Parameters
dev The device handle
ae_d pointer to Day alarm disable bit
days_units pointer to Days units place
days_tens pointer to Days tens place
Definition at line 297 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0xb, 1 );
     *ae_d = (_bytes[0] >> 7) & 0x1;
     *days_units = _bytes[0] & 0xf;
     *days_tens = (_bytes[0] >> 4) & 0x3;
 }
void sml_pcf8563_set_weekday_alarm (sml_pcf8563_t dev, int ae_w, int weekdays)
Set Alarm weekday.
Parameters
dev The device handle
ae_w Weekday alarm disable
weekdays Weekdays (whole field)
Definition at line 313 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((ae_w & 0x1) << 7) | (weekdays & 0x7);
     sml_i2c_regmap_write( dev.iic, &_value, 0xc, 1 );
 }
void sml_pcf8563_get_weekday_alarm (sml_pcf8563_t dev, int * ae_w, int * weekdays)
Get Alarm weekday.
Parameters
dev The device handle
ae_w pointer to Weekday alarm disable bit
weekdays pointer to Weekdays (whole field)
Definition at line 327 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0xc, 1 );
     *ae_w = (_bytes[0] >> 7) & 0x1;
     *weekdays = _bytes[0] & 0x7;
 }
void sml_pcf8563_set_clkout_control (sml_pcf8563_t dev, int fe, int fd)
Set CLKOUT control.
Parameters
dev The device handle
fe Activate CLKOUT output
fd CLKOUT frequency
Definition at line 342 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((fe & 0x1) << 7) | (fd & 0x3);
     sml_i2c_regmap_write( dev.iic, &_value, 0xd, 1 );
 }
void sml_pcf8563_get_clkout_control (sml_pcf8563_t dev, int * fe, int * fd)
Get CLKOUT control.
Parameters
dev The device handle
fe pointer to Activate CLKOUT output bit
fd pointer to CLKOUT frequency
Definition at line 356 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0xd, 1 );
     *fe = (_bytes[0] >> 7) & 0x1;
     *fd = _bytes[0] & 0x3;
 }
void sml_pcf8563_set_timer_control (sml_pcf8563_t dev, int te, int td)
Set Timer control.
Parameters
dev The device handle
te Timer enable
td Timer frequency
Definition at line 371 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     uint8_t _value;
     _value = ((te & 0x1) << 7) | (td & 0x3);
     sml_i2c_regmap_write( dev.iic, &_value, 0xe, 1 );
 }
void sml_pcf8563_get_timer_control (sml_pcf8563_t dev, int * te, int * td)
Get Timer control.
Parameters
dev The device handle
te pointer to Timer enable bit
td pointer to Timer frequency
Definition at line 385 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0xe, 1 );
     *te = (_bytes[0] >> 7) & 0x1;
     *td = _bytes[0] & 0x3;
 }
void sml_pcf8563_set_timer (sml_pcf8563_t dev, uint8_t timer)
Set Timer.
Parameters
dev The device handle
timer Timer
Definition at line 399 of file pcf8563.h.
References sml_i2c_regmap_write().
 {
     sml_i2c_regmap_write( dev.iic, &timer, 0xf, 1 );
 }
uint8_t sml_pcf8563_get_timer (sml_pcf8563_t dev)
Get Timer.
Parameters
dev The device handle
Returns
Timer
Definition at line 410 of file pcf8563.h.
References sml_i2c_regmap_read().
 {
     uint8_t _bytes[1];
     sml_i2c_regmap_read( dev.iic, &_bytes, 0xf, 1 );
     return _bytes[0];
 }