ScriptML C API: resources/c/include/scriptml/persistent.h File Reference
persistent.h File Reference
Special functions for managing persistent flags.
#include <unistd.h>
#include <assert.h>
#include <string.h>
Functions
void sml_persistent_flag_write_str (___StringType_T(size:___NULL()) name, ___StringType_T(size:___NULL()) value)
Write a string to a persistent flag.
void sml_persistent_flag_write_int (___StringType_T(size:___NULL()) name, int value)
Write an integer to a persistent flag.
void sml_persistent_flag_write_float (___StringType_T(size:___NULL()) name, float value)
Write a floating point value to a persistent flag.
void sml_persistent_flag_read_str (___StringType_T(size:___NULL()) name, char *buf)
Read a string from a persistent flag.
int sml_persistent_flag_read_int (___StringType_T(size:___NULL()) name)
Read an integer from a persistent flag.
float sml_persistent_flag_read_float (___StringType_T(size:___NULL()) name)
Read a floating-point number from a persistent flag.
Detailed Description
Special functions for managing persistent flags.
Persistent flags may be used to store small amounts of data on the IOI that remains present after a restart, power-cycle or firmware upgrade (but not a re-imaging of the SD card).
Each flag has a name (which should contain alpha-numeric and _ only) and a value which can be a string, integer or floating-point number.
Writing or attempting to read a non-existant flag creates it.
Flags may also be accessed from the server.
Copyright (c) Open IO Labs Ltd 2017 All Rights Reserved
Definition in file persistent.h.
Function Documentation
void sml_persistent_flag_write_str (___StringType_T(size:___NULL()) name, ___StringType_T(size:___NULL()) value)
Write a string to a persistent flag.
Parameters
name Name of flag to write
value String to write
Definition at line 33 of file persistent.h.
References assert.
                                                          :___NULL() ) name, ___StringType_T( size:___NULL() ) value )
 {
     ___Send(request:"PersistentFlag_WriteStr", client_handle:___NULL(), str_payload:name+":"+value, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     // Check that the response message was as expected - we require OK
     assert( l[0]=="OK" );
 }
void sml_persistent_flag_write_int (___StringType_T(size:___NULL()) name, int value)
Write an integer to a persistent flag.
Parameters
name Name of flag to write
value Number to write
Definition at line 49 of file persistent.h.
References assert.
Referenced by sml_auto_start_disable(), and sml_auto_start_enable().
                                                          :___NULL() ) name, int value )
 {
     ___Send(request:"PersistentFlag_WriteInt", client_handle:___NULL(), str_payload:name, int_payload:___ISeq(value), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     // Check that the response message was as expected - we require OK
     assert( l[0]=="OK" );
 }
void sml_persistent_flag_write_float (___StringType_T(size:___NULL()) name, float value)
Write a floating point value to a persistent flag.
Parameters
name Name of flag to write
value Number to write
Definition at line 65 of file persistent.h.
References assert.
                                                            :___NULL() ) name, float value )
 {
     ___Send(request:"PersistentFlag_WriteFloat", client_handle:___NULL(), str_payload:name, int_payload:___ISeq(), float_payload:___ISeq(value));
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     // Check that the response message was as expected - we require OK
     assert( l[0]=="OK" );
 }
void sml_persistent_flag_read_str (___StringType_T(size:___NULL()) name, char * buf)
Read a string from a persistent flag.
Default string is ""
Parameters
name Name of flag to write
buf Buffer to receive the string
Definition at line 83 of file persistent.h.
References assert, and strcpy().
                                                         :___NULL() ) name, char *buf )
 {
     ___Send(request:"PersistentFlag_ReadStr", client_handle:___NULL(), str_payload:name, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     // Check that the response message was as expected - we require Value
     assert( l[0]=="Value" );
     strcpy( buf, l[1] );
 }
int sml_persistent_flag_read_int (___StringType_T(size:___NULL()) name)
Read an integer from a persistent flag.
Default integer is 0
Parameters
name Name of flag to write
Returns
value in flag
Definition at line 103 of file persistent.h.
References assert.
                                                        :___NULL() ) name )
 {
     ___Send(request:"PersistentFlag_ReadInt", client_handle:___NULL(), str_payload:name, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     // Check that the response message was as expected - we require Value
     assert( l[0]=="Value" );
     return l[1];
 }
float sml_persistent_flag_read_float (___StringType_T(size:___NULL()) name)
Read a floating-point number from a persistent flag.
Default integer is 0.0
Parameters
name Name of flag to write
Returns
value in flag
Definition at line 123 of file persistent.h.
References assert.
                                                            :___NULL() ) name )
 {
     ___Send(request:"PersistentFlag_ReadFloat", client_handle:___NULL(), str_payload:name, int_payload:___ISeq(), float_payload:___ISeq());
     ___ListType_T(element_type:___NULL(), size:___NULL()) l = ___Receive();
     // Check that the response message was as expected - we require Value
     assert( l[0]=="Value" );
     return l[1];
 }