ScriptML C API: resources/c/include/pthread.h File Reference
pthread.h File Reference
Posix pthreads.
#include <coroutines.h>
#include <stddef.h>
Data Structures
struct sched_param
struct pthread_attr_t
struct pthread_cond_t
Macros
#define PTHREAD_CREATE_JOINABLE 0
#define PTHREAD_CREATE_DETACHED 1
#define PTHREAD_SCOPE_SYSTEM 0
#define PTHREAD_SCOPE_PROCESS 1
#define PTHREAD_INHERIT_SCHED 0
#define PTHREAD_EXPLICIT_SCHED 1
#define SCHED_OTHER 0
#define SCHED_FIFO 1
#define SCHED_RR 2
#define PTHREAD_MUTEX_INITIALIZER false
#define PTHREAD_RWLOCK_INITIALIZER 0
#define PTHREAD_COND_INITIALIZER {0, 0}
Typedefs
typedef sml_coroutine_handle_t pthread_t
typedef bool pthread_mutex_t
typedef int pthread_mutexattr_t
typedef int pthread_rwlock_t
typedef int pthread_rwlockattr_t
typedef int pthread_condattr_t
Functions
int pthread_attr_init (pthread_attr_t *attr)
Initialise a pthreads attribute structure.
int pthread_attr_destroy (pthread_attr_t *attr)
Uninitialise a pthreads attribute structure.
int pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate)
Set the detach state in a thread attributes block.
int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate)
Read the detach state from a thread attributes block.
int pthread_attr_setinheritsched (pthread_attr_t *attr, int inheritsched)
Set the scheduler inheritance in a thread attributes block.
int pthread_attr_getinheritsched (const pthread_attr_t *attr, int *inheritsched)
Read the scheduler inheritance from a thread attributes block.
int pthread_attr_setschedparam (pthread_attr_t *attr, const struct sched_param *param)
Set the scheduler parameters in a thread attributes block.
int pthread_attr_getschedparam (const pthread_attr_t *attr, struct sched_param *param)
Read the scheduler parameters from a thread attributes block.
int pthread_attr_setschedpolicy (pthread_attr_t *attr, int policy)
Set the scheduler policy in a thread attributes block.
int pthread_attr_getschedpolicy (const pthread_attr_t *attr, int *policy)
Read the scheduler policy from a thread attributes block.
int pthread_attr_setscope (pthread_attr_t *attr, int scope)
Set the thread scope in a thread attributes block.
int pthread_attr_getscope (const pthread_attr_t *attr, int *scope)
Read the scheduler policy from a thread attributes block.
int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(___NULL_T() arg), ___NULL_T() arg)
Create a thread.
int pthread_yield ()
Yield the current thread to other threads.
void pthread_exit (___NULL_T() value)
Exit the thread, supplying a result code.
int pthread_join (pthread_t thread, void **value_ptr)
Wait for thread to complete.
pthread_t pthread_self ()
Obtain id of current thread.
int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)
Create mutex object.
int pthread_mutex_destroy (pthread_mutex_t *mutex)
Destroy mutex object.
int pthread_mutex_trylock (pthread_mutex_t *mutex)
Attempt to lock mutex object.
int pthread_mutex_lock (pthread_mutex_t *mutex)
Lock mutex object, blocking.
int pthread_mutex_unlock (pthread_mutex_t *mutex)
Unlock mutex object.
int pthread_rwlock_init (pthread_rwlock_t *rwlock, const pthread_rwlockattr_t *attr)
Create read/write lock object.
int pthread_rwlock_destroy (pthread_rwlock_t *rwlock)
Destroy read/write lock object.
int pthread_rwlock_trywrlock (pthread_rwlock_t *rwlock)
Attempt to lock read/write lock object as writer.
int pthread_rwlock_wrlock (pthread_rwlock_t *rwlock)
Lock read/write lock object as writer, blocking.
int pthread_rwlock_tryrdlock (pthread_rwlock_t *rwlock)
Attempt to lock read/write lock object as reader.
int pthread_rwlock_rdlock (pthread_rwlock_t *rwlock)
Lock read/write lock object as reader, blocking.
int pthread_rwlock_unlock (pthread_rwlock_t *rwlock)
Unlock read/write lock object.
int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr)
Create condition variable object.
int pthread_cond_destroy (pthread_cond_t *cond)
Destroy condition variable object.
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
Wait on condition variable object.
int pthread_cond_signal (pthread_cond_t *cond)
Signal condition variable object for one waiter.
int pthread_cond_broadcast (pthread_cond_t *cond)
Signal condition variable object for all waiters.
Detailed Description
Posix pthreads.
See https://www.mankier.com/7/pthreads Implemented here: PThread, mutex, read/write lock, condition variable.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file pthread.h.
Data Structure Documentation
struct sched_param
Definition at line 43 of file pthread.h.
Data Fields
int sched_priority
struct pthread_attr_t
Thread attributes object
Definition at line 48 of file pthread.h.
Data Fields
int detachstate
int scope
int inheritsched
int policy
struct sched_param param
int guardsize
int stack_addr
int stack_size
struct pthread_cond_t
Read/write lock object
Definition at line 509 of file pthread.h.
Data Fields
int waiters
int triggers
Typedef Documentation
typedef bool pthread_mutex_t
Mutex object
Definition at line 322 of file pthread.h.
typedef int pthread_rwlock_t
Read/write lock object
Definition at line 400 of file pthread.h.
Function Documentation
int pthread_attr_init (pthread_attr_t * attr)
Initialise a pthreads attribute structure.
Parameters
attr Pointer to the attribute block to initialise
Returns
Zero on success, non-zero on failure
Definition at line 78 of file pthread.h.
 {
     attr->detachstate = PTHREAD_CREATE_JOINABLE;
     attr->scope = PTHREAD_SCOPE_SYSTEM;
     attr->inheritsched = PTHREAD_INHERIT_SCHED;
     attr->policy = SCHED_FIFO; // Non-standard: gives coroutine behaviour
     attr->param.sched_priority = 1; // Non-standard: gives coroutine behaviour
     attr->stack_addr = 0;
     attr->stack_size = 0;
     return 0;
 }
int pthread_attr_destroy (pthread_attr_t * attr)
Uninitialise a pthreads attribute structure.
Parameters
attr Pointer to the attribute block to uninitialise
Returns
Zero on success, non-zero on failure
Definition at line 97 of file pthread.h.
 {
     return 0;
 }
int pthread_attr_setdetachstate (pthread_attr_t * attr, int detachstate)
Set the detach state in a thread attributes block.
Parameters
attr Pointer to the attribute block to update
detachstate One of PTHREAD_CREATE_JOINABLE or PTHREAD_CREATE_DETACHED
Returns
Zero on success, non-zero on failure
Definition at line 110 of file pthread.h.
 {
     attr->detachstate = detachstate;
     return 0;
 }
int pthread_attr_getdetachstate (const pthread_attr_t * attr, int * detachstate)
Read the detach state from a thread attributes block.
Parameters
attr Pointer to the attribute block to update
detachstate Pointer to the detachment state (int)
Returns
Zero on success, non-zero on failure
Definition at line 124 of file pthread.h.
 {
     *detachstate = attr->detachstate;
     return 0;
 }
int pthread_attr_setinheritsched (pthread_attr_t * attr, int inheritsched)
Set the scheduler inheritance in a thread attributes block.
Parameters
attr Pointer to the attribute block to update
inheritsched One of PTHREAD_INHERIT_SCHED or PTHREAD_EXPLICIT_SCHED
Returns
Zero on success, non-zero on failure
Definition at line 138 of file pthread.h.
 {
     attr->inheritsched = inheritsched;
     return 0;
 }
int pthread_attr_getinheritsched (const pthread_attr_t * attr, int * inheritsched)
Read the scheduler inheritance from a thread attributes block.
Parameters
attr Pointer to the attribute block to update
inheritsched Pointer to the scheduler inheritance (int)
Returns
Zero on success, non-zero on failure
Definition at line 152 of file pthread.h.
 {
     *inheritsched = attr->inheritsched;
     return 0;
 }
int pthread_attr_setschedparam (pthread_attr_t * attr, const struct sched_param * param)
Set the scheduler parameters in a thread attributes block.
Parameters
attr Pointer to the attribute block to update
param Pointer to the sched_param struct to use
Returns
Zero on success, non-zero on failure
Definition at line 166 of file pthread.h.
 {
     attr->param = *param;
     return 0;
 }
int pthread_attr_getschedparam (const pthread_attr_t * attr, struct sched_param * param)
Read the scheduler parameters from a thread attributes block.
Parameters
attr Pointer to the attribute block to update
param Pointer to the sched_param struct to receive the scheduler parameters
Returns
Zero on success, non-zero on failure
Definition at line 180 of file pthread.h.
 {
     *param = attr->param;
     return 0;
 }
int pthread_attr_setschedpolicy (pthread_attr_t * attr, int policy)
Set the scheduler policy in a thread attributes block.
Parameters
attr Pointer to the attribute block to update
policy One of SCHED_OTHER, SCHED_FIFO or SCHED_RR
Returns
Zero on success, non-zero on failure
Definition at line 194 of file pthread.h.
 {
     attr->policy = policy;
     return 0;
 }
int pthread_attr_getschedpolicy (const pthread_attr_t * attr, int * policy)
Read the scheduler policy from a thread attributes block.
Parameters
attr Pointer to the attribute block to update
policy Pointer to the scheduler policy (int)
Returns
Zero on success, non-zero on failure
Definition at line 208 of file pthread.h.
 {
     *policy = attr->policy;
     return 0;
 }
int pthread_attr_setscope (pthread_attr_t * attr, int scope)
Set the thread scope in a thread attributes block.
Parameters
attr Pointer to the attribute block to update
policy One of PTHREAD_SCOPE_SYSTEM, PTHREAD_SCOPE_PROCESS
Returns
Zero on success, non-zero on failure
Definition at line 222 of file pthread.h.
 {
     attr->scope = scope;
     return 0;
 }
int pthread_attr_getscope (const pthread_attr_t * attr, int * scope)
Read the scheduler policy from a thread attributes block.
Parameters
attr Pointer to the attribute block to update
policy Pointer to the scheduler policy (int)
Returns
Zero on success, non-zero on failure
Definition at line 236 of file pthread.h.
 {
     *scope = attr->scope;
     return 0;
 }
int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void *(*)(___NULL_T() arg) start_routine, ___NULL_T() arg)
Create a thread.
Parameters
thread Thread id is written here
attr Pointer to the attribute block to update
start_routine Pointer to the thread's initial function
arg An arbitrary argument
Returns
Zero on success, non-zero on failure
Definition at line 252 of file pthread.h.
References EINVAL, and sml_coroutine_create_1().
 {
     // Require that the attributes are configured to make the thread
     // resemble a coroutine.
     if( attr &&
         ( attr->param.sched_priority != 1 ||
           attr->policy != SCHED_FIFO ) )
         return EINVAL;
     *thread = sml_coroutine_create_1( *start_routine, arg );
     return 0;
 }
int pthread_yield ()
Yield the current thread to other threads.
Returns
Zero on success, non-zero on failure
Definition at line 274 of file pthread.h.
References sml_coroutine_yield().
 {
     sml_coroutine_yield();
     return 0;
 }
void pthread_exit (___NULL_T() value)
Exit the thread, supplying a result code.
Parameters
value_ptr value to return (any type)
Returns
Never returns
Definition at line 287 of file pthread.h.
References sml_coroutine_exit().
 {
     sml_coroutine_exit(value);
 }
int pthread_join (pthread_t thread, void ** value_ptr)
Wait for thread to complete.
Parameters
thread Thread to await
value_ptr Pointer to void * value result
Returns
Zero on success, non-zero on failure
Definition at line 300 of file pthread.h.
 {
     void *result = sml_coroutine_join(thread);
     if( value_ptr )
         *value_ptr = result;
     return 0;
 }
pthread_t pthread_self ()
Obtain id of current thread.
Returns
Current thread's thread id
Definition at line 314 of file pthread.h.
References sml_coroutine_get_current_id().
 {
     return sml_coroutine_get_current_id();
 }
int pthread_mutex_init (pthread_mutex_t * mutex, const pthread_mutexattr_t * attr)
Create mutex object.
Parameters
mutex Pointer to mutex object to initialise
attr Pointer to mutex attributes object (unused)
Returns
Zero on success, non-zero on failure
Definition at line 335 of file pthread.h.
 {
     *mutex = PTHREAD_MUTEX_INITIALIZER;
     return 0;
 }
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Destroy mutex object.
Parameters
mutex Pointer to mutex object to uninitialise
Returns
Zero on success, non-zero on failure
Definition at line 349 of file pthread.h.
 {
     return 0;
 }
int pthread_mutex_trylock (pthread_mutex_t * mutex)
Attempt to lock mutex object.
Parameters
mutex Pointer to mutex object to lock
Returns
Zero on success, EBUSY if locked, other on failure
Definition at line 361 of file pthread.h.
References EBUSY.
 {
     if( *mutex )
         return EBUSY; // fail if locked
     *mutex = true;
     return 0;
 }
int pthread_mutex_lock (pthread_mutex_t * mutex)
Lock mutex object, blocking.
Parameters
mutex Pointer to mutex object to lock
Returns
Zero on success, non-zero on failure
Definition at line 376 of file pthread.h.
References sml_coroutine_wait.
 {
     sml_coroutine_wait( !(*mutex) ); // all threads waiting on the mutex are waiting here
     *mutex = true;
     return 0;
 }
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Unlock mutex object.
Parameters
mutex Pointer to mutex object to lock
Returns
Zero on success, non-zero on failure
Definition at line 390 of file pthread.h.
 {
     *mutex = false;
     return 0;
 }
int pthread_rwlock_init (pthread_rwlock_t * rwlock, const pthread_rwlockattr_t * attr)
Create read/write lock object.
Parameters
rwlock Pointer to read/write lock object to initialise
attr Pointer to read/write lock attributes object (unused)
Returns
Zero on success, non-zero on failure
Definition at line 413 of file pthread.h.
 {
     *rwlock = 0;
     return 0;
 }
int pthread_rwlock_destroy (pthread_rwlock_t * rwlock)
Destroy read/write lock object.
Parameters
rwlock Pointer to read/write lock object to uninitialise
Returns
Zero on success, non-zero on failure
Definition at line 427 of file pthread.h.
 {
     return 0;
 }
int pthread_rwlock_trywrlock (pthread_rwlock_t * rwlock)
Attempt to lock read/write lock object as writer.
Parameters
rwlock Pointer to read/write lock object to lock
Returns
Zero on success, EBUSY if locked, other on failure
Definition at line 439 of file pthread.h.
References EBUSY.
 {
     if( *rwlock != 0 )
         return EBUSY; // fail if locked
     *rwlock = -1;
     return 0;
 }
int pthread_rwlock_wrlock (pthread_rwlock_t * rwlock)
Lock read/write lock object as writer, blocking.
Parameters
rwlock Pointer to read/write lock object to lock
Returns
Zero on success, non-zero on failure
Definition at line 454 of file pthread.h.
References sml_coroutine_wait.
 {
     sml_coroutine_wait( *rwlock == 0 ); // all threads waiting to write are waiting here
     *rwlock = -1;
     return 0;
 }
int pthread_rwlock_tryrdlock (pthread_rwlock_t * rwlock)
Attempt to lock read/write lock object as reader.
Parameters
rwlock Pointer to read/write lock object to lock
Returns
Zero on success, EBUSY if locked, other on failure
Definition at line 468 of file pthread.h.
References EBUSY.
 {
     if( *rwlock == -1 )
         return EBUSY; // fail if locked
     (*rwlock)++;
     return 0;
 }
int pthread_rwlock_rdlock (pthread_rwlock_t * rwlock)
Lock read/write lock object as reader, blocking.
Parameters
rwlock Pointer to read/write lock object to lock
Returns
Zero on success, non-zero on failure
Definition at line 483 of file pthread.h.
References sml_coroutine_wait.
 {
     sml_coroutine_wait( *rwlock != -1 ); // all threads waiting to read are waiting here
     (*rwlock)++;
     return 0;
 }
int pthread_rwlock_unlock (pthread_rwlock_t * rwlock)
Unlock read/write lock object.
Parameters
rwlock Pointer to read/write lock object to lock
Returns
Zero on success, non-zero on failure
Definition at line 497 of file pthread.h.
 {
     if( *rwlock == -1 )
         *rwlock = 0;
     else
         (*rwlock)--;
     return 0;
 }
int pthread_cond_init (pthread_cond_t * cond, const pthread_condattr_t * attr)
Create condition variable object.
Parameters
cond Pointer to condition variable object to initialise
attr Pointer to condition variable attributes object (unused)
Returns
Zero on success, non-zero on failure
Definition at line 526 of file pthread.h.
 {
     cond->waiters = 0;
     cond->triggers = 0;
     return 0;
 }
int pthread_cond_destroy (pthread_cond_t * cond)
Destroy condition variable object.
Parameters
rwlock Pointer to condition variable object to uninitialise
Returns
Zero on success, non-zero on failure
Definition at line 541 of file pthread.h.
 {
     return 0;
 }
int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex)
Wait on condition variable object.
Parameters
cond Pointer to condition variable object to wait on
mutex Pointer to mutex object
Returns
Zero on success, non-zero on failure
Definition at line 554 of file pthread.h.
References sml_coroutine_wait.
 {
     // release the mutex
     *mutex = false;
     // Wait for a signal
     cond->waiters++;
     sml_coroutine_wait( cond->triggers != 0 );
     // consume the signal
     cond->triggers--;
     cond->waiters--;
     // wait for the mutex and re-lock
     sml_coroutine_wait( !(*mutex) );
     *mutex = true;
     return 0;
 }
int pthread_cond_signal (pthread_cond_t * cond)
Signal condition variable object for one waiter.
Parameters
cond Pointer to condition variable object to signal
Returns
Zero on success, non-zero on failure
Definition at line 578 of file pthread.h.
References sml_coroutine_yield().
 {
     cond->triggers++;
     // Since signal() is *intended* to allow other threads to run, yield here
     // (unlike mutex unlock, which *could* allow other threads to run but is not
     // intentionally put there to do so)
     sml_coroutine_yield();
     return 0;
 }
int pthread_cond_broadcast (pthread_cond_t * cond)
Signal condition variable object for all waiters.
Parameters
cond Pointer to condition variable object to signal
Returns
Zero on success, non-zero on failure
Definition at line 595 of file pthread.h.
References sml_coroutine_yield().
 {
     cond->triggers = cond->waiters;
     // Since broadcast() is *intended* to allow other threads to run, yield here
     // (unlike mutex unlock, which *could* allow other threads to run but is not
     // intentionally put there to do so)
     sml_coroutine_yield();
     return 0;
 }