ScriptML C API: resources/c/include/scriptml/spi.h File Reference
spi.h File Reference
Generic SPI bus driver using /dev and ioctl.
#include <scriptml/devsysfs.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
Data Structures
struct spi_ioc_transfer
Macros
#define SPI_CPHA 0x01
#define SPI_CPOL 0x02
#define SPI_MODE_0 (0|0)
#define SPI_MODE_1 (0|SPI_CPHA)
#define SPI_MODE_2 (SPI_CPOL|0)
#define SPI_MODE_3 (SPI_CPOL|SPI_CPHA)
#define SPI_CS_HIGH 0x04
#define SPI_LSB_FIRST 0x08
#define SPI_3WIRE 0x10
#define SPI_LOOP 0x20
#define SPI_NO_CS 0x40
#define SPI_READY 0x80
#define SPI_TX_DUAL 0x100
#define SPI_TX_QUAD 0x200
#define SPI_RX_DUAL 0x400
#define SPI_RX_QUAD 0x800
#define SPI_IOC_MESSAGE(N) (0x40006b00 | (((uint32_t)(N)*32)<<16))
#define SPI_IOC_RD_MODE 0x80016b01
#define SPI_IOC_WR_MODE 0x40016b01
#define SPI_IOC_RD_LSB_FIRST 0x80016b02
#define SPI_IOC_WR_LSB_FIRST 0x40016b02
#define SPI_IOC_RD_BITS_PER_WORD 0x80016b03
#define SPI_IOC_WR_BITS_PER_WORD 0x40016b03
#define SPI_IOC_RD_MAX_SPEED_HZ 0x80046b04
#define SPI_IOC_WR_MAX_SPEED_HZ 0x40046b04
#define SPI_IOC_RD_MODE32 0x80046b05
#define SPI_IOC_WR_MODE32 0x40046b05
Typedefs
typedef sml_devsysfs_t sml_spi_t
Functions
sml_spi_t sml_spi_open (char *path)
Create device driver instance.
void sml_spi_close (sml_spi_t dev)
Destroy device driver instance.
void sml_spi_config (sml_spi_t dev, uint32_t mode, uint8_t endian, uint32_t speed_hz, uint8_t bits_per_word)
Configure SPI device.
void sml_spi_sync_transfer (sml_spi_t dev, struct spi_ioc_transfer *xfers, unsigned int num_xfers)
Generic synchronous SPI operation.
void sml_spi_write (sml_spi_t dev, const uint8_t *buf, size_t count)
Write to SPI device.
void sml_spi_read (sml_spi_t dev, uint8_t *buf, size_t count)
Read from SPI device.
Detailed Description
Generic SPI bus driver using /dev and ioctl.
General:
Broadly speaking this driver follows the precedents set by the internal Linux API for device drivers that access their devices via I2C.
For maximum flexibility, this driver does not encode the paths to the SPI nodes. This is because it will often be desirable to make such paths a config option, or to use a symbolic link or other alias in lieu of the usual path.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file spi.h.
Data Structure Documentation
struct spi_ioc_transfer
SPI message structure from linux/spi/spi.h
Definition at line 31 of file spi.h.
Data Fields
uint8_t * tx_buf
uint32_t pad0
uint8_t * rx_buf
uint32_t pad1
uint32_t len
uint32_t speed_hz
uint16_t delay_usecs
uint8_t bits_per_word
uint8_t cs_change
uint8_t tx_nbits
uint8_t rx_nbits
uint16_t pad
Function Documentation
sml_spi_t sml_spi_open (char * path)
Create device driver instance.
Parameters
path Absolute path to the device node.
Returns
Device handle
Example paths would be "/dev/spidev0.0", "/dev/spidev0.1" and so on
Definition at line 75 of file spi.h.
References sml_devsysfs_open().
 {
     return sml_devsysfs_open( path );
 }
void sml_spi_close (sml_spi_t dev)
Destroy device driver instance.
Parameters
dev Device handle
Definition at line 85 of file spi.h.
References sml_devsysfs_close().
 {
     return sml_devsysfs_close( dev );
 }
void sml_spi_config (sml_spi_t dev, uint32_t mode, uint8_t endian, uint32_t speed_hz, uint8_t bits_per_word)
Configure SPI device.
Parameters
dev Device handle
mode SPI mode
endian 1 for litten-endian; 0 for big-endian
speed_hz Upper limit of SPI clock speed
bits_per_word Word size in bits
The spi_msg structures should be filled in with addr, flags and a pointer to a char buffer containing bytes to read or write.
Definition at line 115 of file spi.h.
References sml_devsysfs_ioctl().
 {
     sml_devsysfs_ioctl( dev, SPI_IOC_WR_MODE32, &mode );
     sml_devsysfs_ioctl( dev, SPI_IOC_WR_LSB_FIRST, &endian );
     sml_devsysfs_ioctl( dev, SPI_IOC_WR_MAX_SPEED_HZ, &speed_hz );
     sml_devsysfs_ioctl( dev, SPI_IOC_WR_BITS_PER_WORD, &bits_per_word );
 }
void sml_spi_sync_transfer (sml_spi_t dev, struct spi_ioc_transfer * xfers, unsigned int num_xfers)
Generic synchronous SPI operation.
Parameters
dev Device handle
xfers Array of transfer structures
num_xfers Number of transfer structures
Definition at line 130 of file spi.h.
References sml_devsysfs_ioctl().
Referenced by sml_spi_read(), and sml_spi_write().
 {
     sml_devsysfs_ioctl( dev, SPI_IOC_MESSAGE(num_xfers), xfers );
 }
void sml_spi_write (sml_spi_t dev, const uint8_t * buf, size_t count)
Write to SPI device.
Parameters
dev Device handle
xfers buf Buffer of data to write
count Number of transfer structures
Single block write transaction
Definition at line 144 of file spi.h.
References sml_spi_sync_transfer().
 {
     struct spi_ioc_transfer xfer;
     xfer.tx_buf = buf;
     xfer.len = count;
     sml_spi_sync_transfer( dev, &xfer, 1 );
 }
void sml_spi_read (sml_spi_t dev, uint8_t * buf, size_t count)
Read from SPI device.
Parameters
dev Device handle
buf Buffer of data for read
count Number of bytes to read
Single block read transaction
Definition at line 161 of file spi.h.
References sml_spi_sync_transfer().
 {
     struct spi_ioc_transfer xfer;
     xfer.rx_buf = buf;
     xfer.len = count;
     sml_spi_sync_transfer( dev, &xfer, 1 );
 }