ScriptML C API: resources/c/include/stdio.h File Reference
stdio.h File Reference
Standard input/output functions.
#include <stdarg.h>
#include <stdlib.h>
#include <unistd.h>
Functions
int putchar (int c)
Write a character to standard output.
int printf (const char *format,...)
Formatted print to stdout.
int sprintf (char *out, const char *format,...)
Formatted print to string.
Detailed Description
Standard input/output functions.
See https://www.mankier.com/0p/stdio.h Simplified version of stdio.h, providing a simplified printf/sprintf and putchar
Copyright 2001, 2002 Georges Menie (www.menie.org) stdarg version contributed by Christian Ettinger
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Definition in file stdio.h.
Function Documentation
int putchar (int c)
Write a character to standard output.
Parameters
c The character to write
Returns
Zero on success, non-zero on failure
Definition at line 41 of file stdio.h.
References va_arg, va_end, and va_list.
 {
     ___PrintCharacter(stream:STDOUT_FILENO, target:c);
     return c;
 }
int printf (const char * format, ...)
Formatted print to stdout.
Parameters
format Format string
... Argments to populate the format tokens
Returns
number of characters printed
Definition at line 236 of file stdio.h.
References va_list, and va_start.
Referenced by sml_devsysfs_close(), sml_devsysfs_ioctl(), sml_devsysfs_open(), sml_devsysfs_read(), sml_devsysfs_read_block(), sml_devsysfs_read_block_to_eof(), sml_devsysfs_read_to_eof(), sml_devsysfs_write(), sml_devsysfs_write_block(), sml_i2c_regmap_read(), sml_i2c_regmap_readL(), sml_i2c_regmap_write(), and sml_i2c_regmap_writeL().
 {
         va_list args;
         va_start( args, format );
         return __print( 0, format, args );
 }
int sprintf (char * out, const char * format, ...)
Formatted print to string.
Parameters
format Format string
... Argments to populate the format tokens
Returns
number of characters written
Definition at line 252 of file stdio.h.
References va_list, and va_start.
Referenced by sml_bluetooth_pair(), sml_bluetooth_serial_bind(), and sml_serial_open().
 {
         va_list args;
         va_start( args, format );
         return __print( &out, format, args );
 }