ScriptML C API: resources/c/include/stdlib.h File Reference
stdlib.h File Reference
Standard library.
#include <stddef.h>
#include "stdlib_math.h"
Data Structures
struct div_t
struct ldiv_t
Macros
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
Functions
void exit (int status)
Exit script.
void * malloc (size_t size)
Allocate an array of bytes.
void free (void *ptr)
Free an array of bytes.
Detailed Description
Standard library.
See https://www.mankier.com/0p/stdlib.h Miscellaneous standard library functions
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file stdlib.h.
Data Structure Documentation
struct div_t
Definition at line 17 of file stdlib.h.
Data Fields
int quot
int rem
struct ldiv_t
Definition at line 23 of file stdlib.h.
Data Fields
int quot
int rem
Function Documentation
void exit (int status)
Exit script.
Parameters
status Script exit status
Returns
never returns
Definition at line 38 of file stdlib.h.
 {
     ___Exit( value:status );
 }
void* malloc (size_t size)
Allocate an array of bytes.
Parameters
size Number of bytes
Returns
pointer to start of buffer
Definition at line 50 of file stdlib.h.
Referenced by int_to_byte(), sml_devsysfs_read(), sml_devsysfs_read_block(), sml_i2c_regmap_readL(), sml_i2c_regmap_write(), and sml_i2c_regmap_writeL().
 {
     return ___ListDefaultExpr( element_type:___ByteType(), size:size );
 }
void free (void * ptr)
Free an array of bytes.
Parameters
ptr Pointer to data
Definition at line 61 of file stdlib.h.
 {
 }