ScriptML C API: resources/c/include/string.h File Reference
string.h File Reference
Standard string library.
#include <stddef.h>
Functions
size_t strlen (const char *s)
Get length of string.
char * strcpy (char *dest, const char *src)
Copy string.
char * strncpy (char *dest, const char *src, size_t n)
Copy string.
char * strcat (char *dest, const char *src)
Concatenate string.
char * strncat (char *dest, const char *src, size_t n)
Concatenate string.
int strcmp (const char *s1, const char *s2)
Compare strings.
int strncmp (const char *s1, const char *s2, int n)
Compare sub-strings, upto n characters.
char * strchr (const char *s, int c)
Search for a character in a string.
char * strrchr (const char *s, int c)
Reverse search for a character in a string.
char * strpbrk (const char *s, const char *accept)
Search for one of a set of characters in a string.
size_t strspn (const char *s, const char *accept)
Count the number of contiguous characters at the beginning of a string in the accept set.
size_t strcspn (const char *s, const char *reject)
Count the number of contiguous characters at the beginning of a string not in the reject set.
char * strtok_r (char *str, const char *delim, char **saveptr)
Divide a sting into tokens; re-entrant version.
char * strtok (char *str, const char *delim)
Divide a sting into tokens; unsafe version.
char * strstr (const char *haystack, const char *needle)
Find a string within another.
char * memcpy (char *dest, const char *src, size_t n)
Copy memory.
char * memmove (char *dest, const char *src, size_t n)
Move memory (src and dest buffers may overlap)
char * memset (char *s, int c, size_t n)
Fill a block of memory with a single character.
char * memchr (const char *s, int c, size_t n)
Search for a character in memory.
int memcmp (const char *s1, const char *s2, size_t n)
Compare memory areas.
Detailed Description
Standard string library.
See https://www.mankier.com/0p/string.h C string and memory manipulation functions
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Definition in file string.h.
Function Documentation
size_t strlen (const char * s)
Get length of string.
Parameters
s Pointer to the string
Returns
number of characters in the string
Definition at line 23 of file string.h.
Referenced by sml_devsysfs_write(), sml_devsysfs_write_block(), strcat(), strcspn(), strncat(), and strstr().
 {
     size_t i=0;
     while( *s++ )
         i++;
     return i;
 }
char* strcpy (char * dest, const char * src)
Copy string.
Parameters
dest Pointer to destination string buffer
src Pointer to source string buffer
Returns
Pointer to destination string buffer
Definition at line 39 of file string.h.
Referenced by sml_osc_send(), sml_persistent_flag_read_str(), and strcat().
 {
     char *dp = dest;
     while( *src )
         *dp++ = *src++;
     *dp++ = (char)0;
     return dest;
 }
char* strncpy (char * dest, const char * src, size_t n)
Copy string.
Parameters
dest Pointer to destination string buffer
src Pointer to source string buffer
n Number of characters to copy
Returns
Pointer to destination string buffer
Definition at line 57 of file string.h.
Referenced by strncat().
 {
     char *dp = dest;
     int i;
     for( i=0; i<n && *src; i++ )
         *dp++ = *src++;
     return dest;
 }
char* strcat (char * dest, const char * src)
Concatenate string.
Parameters
dest Pointer to target string buffer
src Pointer to source string buffer
Returns
Pointer to target string buffer
Definition at line 74 of file string.h.
References strcpy(), and strlen().
Referenced by sml_osc_send().
 {
     size_t dl = strlen(dest);
     strcpy( dest+dl, src );
     return dest;
 }
char* strncat (char * dest, const char * src, size_t n)
Concatenate string.
Parameters
dest Pointer to target string buffer
src Pointer to source string buffer
n Number of characters to copy
Returns
Pointer to target string buffer (always null-terminated)
Definition at line 90 of file string.h.
References strlen(), and strncpy().
 {
     size_t dl = strlen(dest);
     strncpy( dest+dl, src, n );
     dest[dl+n] = 0;
     return dest;
 }
int strcmp (const char * s1, const char * s2)
Compare strings.
Parameters
s1 Pointer to first string
s2 Pointer to second string
Returns
Comparison value: negative when s1<s2, zero when s1==s2 and positive when s1>s2
Definition at line 106 of file string.h.
 {
     while( *s1 && *s2 )
     {
         if( *s1 != *s2 )
             return *s1 - *s2;
         s1++;
         s2++;
     }
     // Whichever ended first reads '\0', which is smaller than other characters
     return *s1 - *s2;
 }
int strncmp (const char * s1, const char * s2, int n)
Compare sub-strings, upto n characters.
Parameters
s1 Pointer to first string
s2 Pointer to second string
n Maximum number of charaqcters to compare
Returns
Comparison value: negative when s1<s2, zero when s1==s2 and positive when s1>s2
Definition at line 128 of file string.h.
Referenced by strstr().
 {
     int i;
     for( i=0; i<n && *s1 && *s2; i++ )
     {
         if( *s1 != *s2 )
             return *s1 - *s2;
         s1++;
         s2++;
     }
     // Whichever ended first reads '\0', which is smaller than other characters
     if( i<n )
         return *s1 - *s2;
     else
         return 0; // ran out of characters so call them the same
 }
char* strchr (const char * s, int c)
Search for a character in a string.
Parameters
s Pointer to first byte of string
c Byte value to search for
Returns
Pointer to found character or NULL if not found
Definition at line 153 of file string.h.
References NULL.
Referenced by strpbrk(), strspn(), and strtok_r().
 {
     while( *s )
     {
         if( *s==c )
             return s;
         s++;
     }
     return NULL;
 }
char* strrchr (const char * s, int c)
Reverse search for a character in a string.
Parameters
s Pointer to first byte of string
c Byte value to search for
Returns
Pointer to found character or NULL if not found
Definition at line 172 of file string.h.
References NULL.
 {
     // One-pass algorithm
     char *pos = NULL;
     while( *s )
     {
         if( *s==c )
             pos = s;
         s++;
     }
     return pos;
 }
char* strpbrk (const char * s, const char * accept)
Search for one of a set of characters in a string.
Parameters
s Pointer to first byte of string
accept String containing the set of characters
Returns
Pointer to found character or NULL if not found
Definition at line 193 of file string.h.
References NULL, and strchr().
Referenced by strcspn(), and strtok_r().
 {
     while( *s )
     {
         if( strchr(accept, *s) )
             return s;
         s++;
     }
     return NULL;
 }
size_t strspn (const char * s, const char * accept)
Count the number of contiguous characters at the beginning of a string in the accept set.
Parameters
s Pointer to first byte of string
accept String containing the set of characters to accept
Returns
Number of initial characters not in set
Definition at line 212 of file string.h.
References strchr().
 {
     const char *d = s;
     while( *d && strchr(accept, *d) )
     {
         d++; // check the next char
     }
     return d-s;
 }
size_t strcspn (const char * s, const char * reject)
Count the number of contiguous characters at the beginning of a string not in the reject set.
Parameters
s Pointer to first byte of string
reject String containing the set of characters to reject
Returns
Number of initial characters not in set
Definition at line 230 of file string.h.
References strlen(), and strpbrk().
 {
     const char *p = strpbrk(s, reject);
     if( p )
         return p-s;
     else
         return strlen(s);
 }
char* strtok_r (char * str, const char * delim, char ** saveptr)
Divide a sting into tokens; re-entrant version.
Parameters
str Pointer to string to be scanned or NULL to continue scan.
delim String containing the set of characters
saveptr Algorithm state variable - maintain across a scan operation
Returns
Found token or NULL if none.
Note: declare saveptr as char *; no initialisation required; pass in &saveptr. Call repeatedly. Pass in the string to parse on first call then NULL on successive calls to continue parsing the same string. NULL is returned when there are no remainin tokens.
Definition at line 254 of file string.h.
References NULL, strchr(), and strpbrk().
Referenced by strtok().
 {
     if( str )
         *saveptr = str; // startup
     else if( !*saveptr )
         return NULL;   // shutdown
     char *d = strpbrk(*saveptr, delim);
     if( d )
     {
         *d = 0; // NULL-terminate
         do
         {
             d++; // check the next char
             if( *d==0 )
             {
                 d = NULL;
                 break;
             }
         } while( strchr(delim, *d) );
     }
     str = *saveptr;
     *saveptr = d;
     return str;
 }
char* strtok (char * str, const char * delim)
Divide a sting into tokens; unsafe version.
Parameters
str Pointer to string to be scanned or NULL to continue scan.
delim String containing the set of characters
Returns
Found token or NULL if none.
Note: Not thread- or coroutine-safe. Cannot nest parsing loops.
Definition at line 293 of file string.h.
References strtok_r().
 {
     static char *saveptr;
     return strtok_r(str, delim, saveptr);
 }
char* strstr (const char * haystack, const char * needle)
Find a string within another.
Parameters
haystack Pointer to string to be searched.
needle Pointer to sub-string to search for
Returns
Start of found substring or NULL if not found.
Note: Not thread- or coroutine-safe. Cannot nest parsing loops.
Definition at line 309 of file string.h.
References NULL, strlen(), and strncmp().
 {
     int i;
     int ofs = strlen(needle);
     if( ofs==0 )
         return haystack; // 0-length substring is found immediately (empty AND-rule == true)
     if( strlen(haystack) < ofs )
         return NULL;
     while( *(haystack+ofs-1) )
     {
         if( strncmp(haystack, needle, ofs) == 0 )
             return haystack;
         haystack++;
     }
     return NULL;
 }
char* memcpy (char * dest, const char * src, size_t n)
Copy memory.
Parameters
dest Pointer to destination string buffer
src Pointer to source string buffer
Returns
Pointer to destination string buffer
Definition at line 334 of file string.h.
Referenced by memmove(), sml_i2c_regmap_write(), and sml_i2c_regmap_writeL().
 {
     char *dp = dest;
     int i;
     for( i=0; i<n; i++ )
         *dp++ = *src++;
     return dest;
 }
char* memmove (char * dest, const char * src, size_t n)
Move memory (src and dest buffers may overlap)
Parameters
dest Pointer to destination string buffer
src Pointer to source string buffer
Returns
Pointer to destination string buffer
Definition at line 351 of file string.h.
References memcpy().
 {
     if( dest < src )
         return memcpy(dest, src, n);
     char *dp = dest+n-1;
     src = src+n-1;
     int i;
     for( i=0; i<n; i++ )
         *dp-- = *src--;
     return dest;
 }
char* memset (char * s, int c, size_t n)
Fill a block of memory with a single character.
Parameters
s Pointer to destination memory block
c Character to write
n Size of destination memory block
Returns
Pointer to destination memory block
Definition at line 374 of file string.h.
 {
     int i;
     for(i=0; i<n; i++)
         *s++ = c;
     return s;
 }
char* memchr (const char * s, int c, size_t n)
Search for a character in memory.
Parameters
s Pointer to first byte of memory area
c Byte value to search for
n Size of area
Returns
Pointer to found character or NULL if not found
Definition at line 391 of file string.h.
References NULL.
 {
     int i;
     for( i=0; i<n; i++ )
     {
         if( *s==c )
             return s;
         s++;
     }
     return NULL;
 }
int memcmp (const char * s1, const char * s2, size_t n)
Compare memory areas.
Parameters
s1 Pointer to first area
s2 Pointer to second area
n Size of areas
Returns
Comparison value: negative when s1<s2, zero when s1==s2 and positive when s1>s2
Definition at line 412 of file string.h.
 {
     int i;
     for( i=0; i<n; i++ )
     {
         if( *s1 != *s2 )
             return *s1 - *s2;
         s1++;
         s2++;
     }
     return 0;
 }