ScriptML Python API: serial.Serial Class Reference
serial.Serial Class Reference
serial device driver class
Public Member Functions
def __init__ (self, port=None, baudrate=9600, bytesize=EIGHTBITS, parity=PARITY_NONE, stopbits=STOPBITS_ONE, timeout=None, xonxoff=False, rtscts=False, write_timeout=None, dsrdtr=False, inter_byte_timeout=None)
Initialise access to the serial port.
def open (self)
def close (self)
End access to the serial port.
def write (self, data)
Write to serial port.
def read (self, size=1)
Read from serial port.
def flush (self)
def flush (self)
def reset_input_buffer (self)
def reset_output_buffer (self)
def send_break (self, duration=0.25)
Public Attributes
port
baudrate
bytesize
parity
stopbits
timeout
xonxoff
rtscts
write_timeout
dsrdtr
inter_byte_timeout
dev
Detailed Description
serial device driver class
Instantiate one of these for each serial port
Definition at line 31 of file serial.py.
Constructor & Destructor Documentation
def serial.Serial.__init__ (self, port = None, baudrate = 9600, bytesize = EIGHTBITS, parity = PARITY_NONE, stopbits = STOPBITS_ONE, timeout = None, xonxoff = False, rtscts = False, write_timeout = None, dsrdtr = False, inter_byte_timeout = None)
Initialise access to the serial port.
Returns
handle for the serial port
Definition at line 48 of file serial.py.
References serial.Serial._reconfigure_port(), serial.Serial.baudrate, serial.Serial.bytesize, serial.Serial.close(), serial.Serial.dev, serial.Serial.dsrdtr, serial.Serial.inter_byte_timeout, serial.Serial.parity, serial.Serial.port, serial.Serial.rtscts, serial.Serial.stopbits, serial.Serial.timeout, serial.Serial.write_timeout, and serial.Serial.xonxoff.
                   inter_byte_timeout=None ):
         self.port = port
         self.baudrate = baudrate
         self.bytesize = bytesize
         self.parity = parity
         self.stopbits = stopbits
         self.timeout = timeout
         self.xonxoff = xonxoff
         self.rtscts = rtscts
         self.write_timeout = write_timeout
         self.dsrdtr = dsrdtr
         self.inter_byte_timeout = inter_byte_timeout
         self.dev = None
Member Function Documentation
def serial.Serial.write (self, data)
Write to serial port.
Parameters
h serial port handle
text text to write to the port
Definition at line 104 of file serial.py.
References serial.Serial.read().
     def write( self, data ):
         self.dev.write( data )
def serial.Serial.read (self, size = 1)
Read from serial port.
Parameters
h serial port handle
Returns
buffer for text read from port
Definition at line 113 of file serial.py.
References serial.Serial.dev, and builtins.int().
Referenced by serial.Serial.write().
     def read( self, size=1 ):
         return self.dev.read( size )
The documentation for this class was generated from the following file:
resources/python/standard/serial.py