ScriptML Python API: gpio.device Class Reference
gpio.device Class Reference
GPIO device driver class.
Public Member Functions
def set_direction (self, d)
Set GPIO pin direction.
def __init__ (self, pin)
Initialise access to a GPIO pin.
def __del__ (self)
Destroy device driver instance.
def set_level (self, l)
Set level of a GPIO output pin.
def get_level (self)
Get level of a GPIO output pin.
def set_callback (self, edge_type, callback)
Register a callback to be invoked on certain level changes.
Public Attributes
direction
spin
value_dev
direction_dev
watcher
Detailed Description
GPIO device driver class.
Instantiate one of these for each GPIO pin
Definition at line 48 of file gpio.py.
Constructor & Destructor Documentation
def gpio.device.__init__ (self, pin)
Initialise access to a GPIO pin.
Parameters
num GPIO pin number (as a string) or name
Definition at line 63 of file gpio.py.
References gpio.device.direction_dev, gpio.device.set_direction(), gpio.device.spin, builtins.str(), gpio.device.value_dev, and gpio.device.watcher.
Referenced by pca9534.device.__init__(), lm75b.device.__init__(), isl29023.device.__init__(), pcf8563.device.__init__(), and mpu6050.device.__init__().
     def __init__( self, pin ):
         self.spin = str(pin)
         path = "/sys/class/gpio/gpio"+self.spin+"/"
         self.value_dev = devsysfs.device( path+"value" )
         self.direction_dev = devsysfs.device( path+"direction" )
         self.set_direction( IN )
         self.watcher = None
Member Function Documentation
def gpio.device.set_direction (self, d)
Set GPIO pin direction.
Parameters
dir Direction; one of IN or OUT
Definition at line 54 of file gpio.py.
References gpio.device.direction.
Referenced by gpio.device.__init__().
     def set_direction( self, d ):
         self.direction = d
         self.direction_dev.write( "out" if self.direction==OUT else "in" )
def gpio.device.set_level (self, l)
Set level of a GPIO output pin.
Parameters
l Level; 0 or 1
Definition at line 83 of file gpio.py.
References gpio.device.direction, builtins.int(), and builtins.str().
     def set_level( self, l ):
         assert self.direction==OUT, "Attempt to set level of GPIO configured as input"
         self.value_dev.write( str(int(l)) )
def gpio.device.get_level (self)
Get level of a GPIO output pin.
Returns
Level; 0 or 1
Definition at line 92 of file gpio.py.
References builtins.int().
Referenced by pcf8574.device.wait_any_change().
     def get_level( self ):
         sl = self.value_dev.read_block_to_eof(0)
         return int(sl)
def gpio.device.set_callback (self, edge_type, callback)
Register a callback to be invoked on certain level changes.
Parameters
edge_type Which edges should invoke the function: RISING, FALLING or BOTH
callback The callback function. Takes one argument which is the GPIO string
Definition at line 103 of file gpio.py.
References gpio.device.watcher.
     def set_callback( self, edge_type, callback ):
         self.watcher = coroutines.coroutine( _watcher_coroutine_func, [self, edge_type, callback] )
The documentation for this class was generated from the following file:
resources/python/scriptml/gpio.py