ScriptML Python API: i2c.device Class Reference
i2c.device Class Reference
I2C bus driver class.
Public Member Functions
def __init__ (self, path)
Create device driver instance.
def __del__ (self, path)
Destroy device driver instance.
def transfer (self, msgs)
Perform an i2c transfer.
def msg (self, addr, flags, buf)
Create a single I2C message.
def write (self, addr, buf)
Write to I2C device.
def read (self, addr, count=1)
Read from I2C device.
def smbus_set_addr (self, addr)
Set I2C bus device address.
def smbus_access (self, read_write, command, size, data)
Perform I2C/SMBUS access.
def smbus_write_quick (self, value)
SMBus Quick Command
def smbus_read_byte (self)
SMBus Receive Byte:
def smbus_write_byte (self, value)
SMBus Send Byte:
def smbus_read_byte_data (self, command)
SMBus Register Read Byte:
def smbus_write_byte_data (self, command, value)
SMBus Register Write Byte:
def smbus_read_word_data (self, command)
SMBus Register Read Word:
def smbus_write_word_data (self, command, value)
SMBus Register Write Word:
def smbus_process_call (self, command, value)
SMBus Process Call:
def smbus_read_block_data (self, command)
SMBus Block Read:
def smbus_write_block_data (self, command, length, values)
SMBus Block Write:
Public Attributes
dev
Detailed Description
I2C bus driver class.
Instantiate one of these for each I2C bus you need to use
Definition at line 76 of file i2c.py.
Constructor & Destructor Documentation
def i2c.device.__init__ (self, path)
Create device driver instance.
Parameters
path Absolute path to the device node.
Example paths would be "/dev/i2c-1", "/dev/i2c-2" and so on
Definition at line 83 of file i2c.py.
References devsysfs.device.dev, and i2c.device.dev.
     def __init__( self, path ):
         self.dev = devsysfs.device( path )
Member Function Documentation
def i2c.device.transfer (self, msgs)
Perform an i2c transfer.
Parameters
msgs A list of message objects
The message objects must have been created using the msg() function. A list is always required, even if only one msg is present. This function corresponds to the i2c_transfer() function defined in the Linux kernel. The i2c_rdwr_ioctl_data structure is created automatically from the supplied message list.
Definition at line 99 of file i2c.py.
References devsysfs.block(), and builtins.len().
Referenced by i2c.device.read(), and i2c.device.write().
     def transfer( self, msgs ):
         # Create struct i2c_rdwr_ioctl_data
         rdwr_arg = [devsysfs.block(msgs),uint32(len(msgs))]
         self.dev.ioctl( I2C_RDWR, devsysfs.block(rdwr_arg) )
def i2c.device.msg (self, addr, flags, buf)
Create a single I2C message.
Parameters
addr I2c address for transfer (not including R/W bit)
flags Any OR-combinations of the I2C_M_ flags
buf A list of uint8 types serving as buffer for the transfer
The size of the buffer is the length of the transfer, and so a buffer must be provided for reads as well as writes. The buffer is mutated by a read transfer, regardless of any apparent immutability of its elements. The message created by this call corresponds to the i2c_msg structure defined in the Linux kernel.
Definition at line 115 of file i2c.py.
References devsysfs.block(), and builtins.len().
Referenced by i2c.device.read(), and i2c.device.write().
     def msg( self, addr, flags, buf ):
         # Create strcut i2c_msg
         return [uint16(addr), uint16(flags), uint16(len(buf)), devsysfs.block(buf)]
def i2c.device.write (self, addr, buf)
Write to I2C device.
Parameters
self Device handle
addr I2C device address
buf Buffer of data to write
count Number of bytes to write
Single block write transaction
Definition at line 129 of file i2c.py.
References i2c.device.msg(), and i2c.device.transfer().
     def write( self, addr, buf ):
         msg = self.msg( addr, 0, buf )
         self.transfer([msg])
def i2c.device.read (self, addr, count = 1)
Read from I2C device.
Parameters
self Device handle
addr I2C device address
buf Buffer of data for read
count Number of bytes to read
Single block read transaction
Definition at line 144 of file i2c.py.
References i2c.device.msg(), builtins.range(), and i2c.device.transfer().
     def read( self, addr, count=1 ):
         buf = []
         for i in range(count):
             buf = buf + [uint8()]
         msgs = [self.msg( addr, i2c.I2C_M_RD, buf )]
         self.transfer(msgs)
         return buf
def i2c.device.smbus_set_addr (self, addr)
Set I2C bus device address.
Parameters
read_write Data direction; one of I2C_SMBUS_READ or I2C_SMBUS_WRITE
Definition at line 160 of file i2c.py.
     def smbus_set_addr( self, addr ):
         self.dev.ioctl( I2C_SLAVE, uint32(addr) )
def i2c.device.smbus_access (self, read_write, command, size, data)
Perform I2C/SMBUS access.
Parameters
read_write Data direction; one of I2C_SMBUS_READ or I2C_SMBUS_WRITE
command Depends on the transaction type - usually the register or only byte to transfer
size The transaction type; one of I2C_SMBUS_QUICK etc
data Optional extra data block, organised as bytes
The size parameter chooses the kind of transaction (not the size). command is the first byte used and additional bytes are in a block pointed to by data.
Definition at line 172 of file i2c.py.
References devsysfs.block().
Referenced by i2c.device.smbus_process_call(), i2c.device.smbus_read_block_data(), i2c.device.smbus_read_byte(), i2c.device.smbus_read_byte_data(), i2c.device.smbus_read_word_data(), i2c.device.smbus_write_block_data(), i2c.device.smbus_write_byte(), i2c.device.smbus_write_byte_data(), i2c.device.smbus_write_quick(), and i2c.device.smbus_write_word_data().
     def smbus_access( self, read_write, command, size, data ):
         args = [uint8(read_write), uint8(command), uint32(size), devsysfs.block(data)]
         self.dev.ioctl( I2C_SMBUS, devsysfs.block(args) )
def i2c.device.smbus_write_quick (self, value)
SMBus Quick Command
This sends a single bit to the device, at the place of the Rd/Wr bit.
Bus sequence A Addr Rd/Wr [A] P
Parameters
value Value of bit (1 for read)
Definition at line 185 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_write_quick(self, value):
         self.smbus_access(value, 0, I2C_SMBUS_QUICK, [])
def i2c.device.smbus_read_byte (self)
SMBus Receive Byte:
This reads a single byte from a device, without specifying a device register. Some devices are so simple that this interface is enough; for others, it is a shorthand if you want to read the same register as in the previous SMBus command.
Bus sequence S Addr Rd [A] [Data] NA P
Returns
The byte that was read
Definition at line 200 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_read_byte(self):
         byte = uint8()
         self.smbus_access(I2C_SMBUS_READ, 0, I2C_SMBUS_BYTE, [byte])
         return byte
def i2c.device.smbus_write_byte (self, value)
SMBus Send Byte:
This operation is the reverse of Receive Byte: it sends a single byte to a device. See Receive Byte for more information.
Bus sequence: S Addr Wr [A] Data [A] P
Parameters
value The byte to write
Definition at line 215 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_write_byte(self, value):
         self.smbus_access(I2C_SMBUS_WRITE, value, I2C_SMBUS_BYTE, [])
def i2c.device.smbus_read_byte_data (self, command)
SMBus Register Read Byte:
This reads a single byte from a device, from a designated register. The register is specified through the Comm byte.
Bus sequence S Addr Wr [A] Comm [A] S Addr Rd [A] [Data] NA P
Parameters
command The register to read from
Returns
The byte that was read
Definition at line 229 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_read_byte_data(self, command):
         byte = uint8()
         self.smbus_access(I2C_SMBUS_READ, command,
                              I2C_SMBUS_BYTE_DATA, [byte])
         return byte
def i2c.device.smbus_write_byte_data (self, command, value)
SMBus Register Write Byte:
This writes a single byte to a device, to a designated register. The register is specified through the Comm byte. This is the opposite of the Read Byte operation.
Bus sequence: S Addr Wr [A] Comm [A] Data [A] P
Parameters
command The register to write to
value the byte to write
Definition at line 247 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_write_byte_data(self, command, value):
         byte = uint8(value)
         self.smbus_access(I2C_SMBUS_WRITE, command, I2C_SMBUS_BYTE_DATA, [byte])
def i2c.device.smbus_read_word_data (self, command)
SMBus Register Read Word:
This operation is very like Read Byte; again, data is read from a device, from a designated register that is specified through the Comm byte. But this time, the data is a complete word (16 bits).
Bus sequence: S Addr Wr [A] Comm [A] S Addr Rd [A] [DataLow] A [DataHigh] NA P
Parameters
command The register to read from
Returns
The word that was read
Definition at line 263 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_read_word_data(self, command):
         word = uint16()
         self.smbus_access(I2C_SMBUS_READ, command, I2C_SMBUS_WORD_DATA, [word])
         return word
def i2c.device.smbus_write_word_data (self, command, value)
SMBus Register Write Word:
This is the opposite of the Read Word operation. 16 bits of data is written to a device, to the designated register that is specified through the Comm byte.
Bus sequence: S Addr Wr [A] Comm [A] DataLow [A] DataHigh [A] P
Parameters
command The register to write to
value the word to write
Definition at line 281 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_write_word_data(self, command, value):
         word = uint16(value)
         self.smbus_access(I2C_SMBUS_WRITE, command, I2C_SMBUS_WORD_DATA, [word])
def i2c.device.smbus_process_call (self, command, value)
SMBus Process Call:
This command selects a device register (through the Comm byte), sends 16 bits of data to it, and reads 16 bits of data in return.
Bus sequence: S Addr Wr [A] Comm [A] DataLow [A] DataHigh [A] S Addr Rd [A] [DataLow] A [DataHigh] NA P
Parameters
command The register to write to/read from
value the word to write
Returns
The word that was read back
Definition at line 297 of file i2c.py.
References i2c.device.smbus_access().
     def smbus_process_call(self, command, value):
         word = uint16(value)
         self.smbus_access(I2C_SMBUS_WRITE, command, I2C_SMBUS_PROC_CALL, [word])
         return word
def i2c.device.smbus_read_block_data (self, command)
SMBus Block Read:
This command reads a block of up to 32 bytes from a device, from a designated register that is specified through the Comm byte. The amount of data is specified by the device in the Count byte.
Bus sequence: S Addr Wr [A] Comm [A] S Addr Rd [A] [Count] A [Data] A [Data] A ... A [Data] NA P
Parameters
command The register to read from
Returns
The number of read bytes, and a list containing the read bytes
Definition at line 314 of file i2c.py.
References builtins.range(), and i2c.device.smbus_access().
     def smbus_read_block_data(self, command):
         data = []
         for i in range(I2C_SMBUS_BLOCK_MAX_PADDED):
             data = data + [uint8()]
         self.smbus_access(I2C_SMBUS_READ, command, I2C_SMBUS_BLOCK_DATA, data)
         return data[0], data[1:]
def i2c.device.smbus_write_block_data (self, command, length, values)
SMBus Block Write:
The opposite of the Block Read command, this writes up to 32 bytes to a device, to a designated register that is specified through the Comm byte. The amount of data is specified in the Count byte.
Bus sequence: S Addr Wr [A] Comm [A] Count [A] Data [A] Data [A] ... [A] Data [A] P
Parameters
command The register to write to
length The number of bytes
values Pointer to the block of bytes to write
Definition at line 334 of file i2c.py.
References builtins.range(), and i2c.device.smbus_access().
     def smbus_write_block_data(self, command, length, values):
         data = [length]
         for i in range(length):
             data = data + [uint8(values[i])]
         self.smbus_access(I2C_SMBUS_WRITE, command, I2C_SMBUS_BLOCK_DATA, data)
The documentation for this class was generated from the following file:
resources/python/scriptml/i2c.py