ScriptML Python API: ngimu.device Class Reference
ngimu.device Class Reference
Public Member Functions
def __init__ (self, my_port, device_ip, device_port, user)
Open NGIMU connection.
def handler (self, path, ints, floats, strings)
def send (self, path, types, sargv, iargv, fargv)
Send a message to the NGIMU.
def command (self, ack_flag, path, types, sargv, iargv, fargv)
Send a message to the NGIMU.
def read_setting (self, path)
Send a message to the NGIMU.
def command_mute (self)
Send "mute" command to NGIMU.
def command_unmute (self)
Send "unmute" command to NGIMU.
def command_reset (self)
Send "reset" command to NGIMU.
def command_sleep (self)
Send "sleep" command to NGIMU.
def command_identify (self)
Send "identify" command to NGIMU.
def command_apply (self)
Send "apply" command to NGIMU.
def command_default (self)
Send "default" command to NGIMU.
def command_ahrs_initialise (self)
Send "ahrs_initialise" command to NGIMU.
def command_ahrs_zero (self)
Send "ahrs_zero" command to NGIMU.
def command_echo (self, sarg, iarg, farg)
Send "echo" command to NGIMU.
def set_rate (self, channel, rate)
Set the update rate of a channel of data.
Public Attributes
device_ip
user
acks
read_ack
read_path
read_ints
read_floats
read_strings
Detailed Description
Definition at line 28 of file ngimu.py.
Constructor & Destructor Documentation
def ngimu.device.__init__ (self, my_port, device_ip, device_port, user)
Open NGIMU connection.
Parameters
handler OSC message handler function
my_port Handler is called for messages incoming on this port
device_ip IP address of the device
device_port Port on device to send messages to
data A user data object that is passed to the handler
Definition at line 38 of file ngimu.py.
References ngimu.device.acks, ngimu.device.device_ip, ngimu.device.read_ack, ngimu.device.read_floats, ngimu.device.read_ints, ngimu.device.read_path, ngimu.device.read_strings, and ngimu.device.user.
     def __init__( self, my_port, device_ip, device_port, user ):
         self.device_ip = device_ip
         self.user = user
         self.acks = {}
         self.acks["mute"] = False
         self.acks["unmute"] = False
         self.acks["reset"] = False
         self.acks["sleep"] = False
         self.acks["identify"] = False
         self.acks["apply"] = False
         self.acks["default"] = False
         self.acks["ahrs_initialise"] = False
         self.acks["ahrs_zero"] = False
         self.acks["echo"] = False
         self.read_ack = False
         self.read_path = None
         osc.init( _handler, my_port, device_ip, device_port, self )
Member Function Documentation
def ngimu.device.send (self, path, types, sargv, iargv, fargv)
Send a message to the NGIMU.
Parameters
path OSC-defined path to the resource to write (a string separated by /)
types OSC-defined types of the parameters of the message
sargv String arguments referenced by types argument, in their own order
iargv Integer arguments referenced by types argument, in their own order
fargv Floating-point arguments referenced by types argument, in their own order
Definition at line 127 of file ngimu.py.
References ngimu.device.device_ip.
Referenced by ngimu.device.command(), ngimu.device.read_setting(), and ngimu.device.set_rate().
     def send( self, path, types, sargv, iargv, fargv ):
         osc.send_message( self.device_ip, path, types, sargv, iargv, fargv )
def ngimu.device.command (self, ack_flag, path, types, sargv, iargv, fargv)
Send a message to the NGIMU.
Parameters
path OSC-defined path to the resource to write (a string separated by /)
ack_flag index into self.acks map - blocks until this flag is True
types OSC-defined types of the parameters of the message
sargv String arguments referenced by types argument, in their own order
iargv Integer arguments referenced by types argument, in their own order
fargv Floating-point arguments referenced by types argument, in their own order
Definition at line 140 of file ngimu.py.
References ngimu.device.acks, and ngimu.device.send().
Referenced by ngimu.device.command_ahrs_initialise(), ngimu.device.command_ahrs_zero(), ngimu.device.command_apply(), ngimu.device.command_default(), ngimu.device.command_echo(), ngimu.device.command_identify(), ngimu.device.command_mute(), ngimu.device.command_reset(), ngimu.device.command_sleep(), and ngimu.device.command_unmute().
     def command( self, ack_flag, path, types, sargv, iargv, fargv ):
         self.send( path, types, sargv, iargv, fargv )
         while self.acks[ack_flag] == False:
             pass
         self.acks[ack_flag] = False
def ngimu.device.read_setting (self, path)
Send a message to the NGIMU.
Parameters
path OSC-defined path to the resource to read (a string separated by /)
Returns
a tuple made up of (list of strings, list of integers, list of floats)
Definition at line 152 of file ngimu.py.
References ngimu.device.read_ack, ngimu.device.read_floats, ngimu.device.read_ints, ngimu.device.read_path, ngimu.device.read_strings, and ngimu.device.send().
     def read_setting( self, path ):
         self.read_path = path
         self.send( path, "", [], [], [] )
         while self.read_ack == False:
             pass
         self.read_ack = False
         return (self.read_strings, self.read_ints, self.read_floats)
def ngimu.device.command_echo (self, sarg, iarg, farg)
Send "echo" command to NGIMU.
Parameters
sarg String argument
iarg Integer argument
farg Floating-point argument
Definition at line 220 of file ngimu.py.
References ngimu.device.command().
     def command_echo( self, sarg, iarg, farg ):
         self.command( "echo", "/echo", "sif", [sarg], [iarg], [farg] )
def ngimu.device.set_rate (self, channel, rate)
Set the update rate of a channel of data.
Parameters
channel The kind of data to send, eg "sensors", "magnitudes" etc
rate the new rate in Hertz
Definition at line 228 of file ngimu.py.
References ngimu.device.send().
     def set_rate( self, channel, rate ):
         self.send( "/rate/"+channel, "f", [], [], [rate] )
The documentation for this class was generated from the following file:
resources/python/scriptml/ngimu.py