ScriptML Python API: devsysfs Namespace Reference
devsysfs Namespace Reference
Access to /dev and /sys nodes.
Classes
class device
Dev node or sysfs node class.
Functions
def mono_write (path, data)
Monolithic write to device.
def mono_write_block (path, pos, data)
Monolithic write a block of data to device.
def mono_read_to_eof (path)
Monolithic read from device until EOF.
def mono_read (path, len)
Monolithic read a number of bytes from device.
def mono_read_block (path, pos, len)
Monolithic read a block of data from device.
def mono_ioctl (path, request, data)
Perform monolithic ioctl on device.
def pointer (x)
Create a pointer to an ioctl data block for CLib access.
Detailed Description
Access to /dev and /sys nodes.
General:
This is the correct API to use for device drivers when accessing these nodes under /dev or /sys. Other "file" APIs may not be able to access these nodes in the correct manner.
There is a class-based interface which holds the device file open while the driver class instance exists, and alternative free functions that open the device, act, and close it again. the latter are termed "monolithic" and begin with mono_.
Read and write operations work with lists of byte data only (numpy.uint8 or numpy.int8). The variants containing _block are for intended for block devices and use pread() and pwrite(). The others use read() and write() are meant for character devices. This correspondance is not strict and some devices don't really correspond to block or character idioms.
The ioctl can accept data structures made up of pointers, arrays and structs, and converts them to and from a memory-based form for use with the underlying ioctl operation. Alignment padding is generated consistent with the C++11 cross-compiler used to build the scriptml interpreter.
Python:
The python version of ioctl uses lists populated with numpy types such as numpy.uint8 and so on in lieu of structs. Free function pointer() is provided to create a C pointer to a list. This should be used to seperate contiguous blocks of data (where the ioctl's data structure requirement is to use a pointer). Otherwise, nested lists are concatenated into a single block, as with C structures.
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Function Documentation
def devsysfs.mono_write (path, data)
Monolithic write to device.
Parameters
path Path to device
data Data to write to the device
Definition at line 136 of file devsysfs.py.
 def mono_write( path, data ):
     device( path ).write( data )
def devsysfs.mono_write_block (path, pos, data)
Monolithic write a block of data to device.
Parameters
path Path to device
pos Position of start of block
data Data to write to the device
Definition at line 147 of file devsysfs.py.
 def mono_write_block( path, pos, data ):
     device( path ).write_block( pos, data )
def devsysfs.mono_read_to_eof (path)
Monolithic read from device until EOF.
Parameters
path Path to device
Returns
Data read from device
Definition at line 157 of file devsysfs.py.
 def mono_read_to_eof( path ):
     return device( path ).read_to_eof()
def devsysfs.mono_read (path, len)
Monolithic read a number of bytes from device.
Parameters
path Path to device
len Number of bytes
Returns
Data read from device
Definition at line 168 of file devsysfs.py.
 def mono_read( path, len ):
     return device( path ).read( len )
def devsysfs.mono_read_block (path, pos, len)
Monolithic read a block of data from device.
Parameters
path Path to device
pos Position of start of block
len Number of bytes
Returns
Data read from device
Definition at line 180 of file devsysfs.py.
 def mono_read_block( path, pos, len ):
     return device( path ).read_block( pos, len )
def devsysfs.mono_ioctl (path, request, data)
Perform monolithic ioctl on device.
Parameters
path Path to device
request Ioctl request code
data Input data block
Returns
Output data block
data is usually a data block returned by the block() function, except in a few cases where a fundamental type such as "int" is used directly.
Definition at line 195 of file devsysfs.py.
 def mono_ioctl( path, request, data ):
     return device( path ).ioctl( request, data )
def devsysfs.pointer (x)
Create a pointer to an ioctl data block for CLib access.
Parameters
x The data structure to point to
Returns
An object that may be embedded in other blocks or passed to CLib intrinsics
The return value is in fact a C-style pointer, with automatic garbage collection. Pass in None to produce a NULL pointer (the None object cannot be converted for CLib access).
Definition at line 209 of file devsysfs.py.
Referenced by spi.device.config(), i2c.device.msg(), spi.device.read(), i2c.device.smbus_access(), spi.device.sync_transfer(), i2c.device.transfer(), and spi.device.write().
 def pointer(x):
     if x is None:
         return ___PointerExpr( target=___NULL() )
     else:
         return ___PointerExpr( target=x )