ScriptML Python API: numpy Namespace Reference
numpy Namespace Reference
ScriptML elments of numpy.
Functions
def mean (l)
Arithmetic mean.
def median (l)
Median value.
def mode (l)
Mode value.
def var (l)
Variance.
def std (l)
Standard deviation.
def prod (items)
Product of elements in a list.
Variables
type
target
specifiers
Detailed Description
ScriptML elments of numpy.
See https://docs.python.org/2/library/time.html
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Function Documentation
def numpy.mean (l)
Arithmetic mean.
Parameters
l list of numeric values
Returns
The mean value
Definition at line 35 of file numpy.py.
References builtins.float(), builtins.len(), and builtins.sum().
Referenced by median(), and var().
 def mean(l):
     return float(sum(l)) / len(l)
def numpy.median (l)
Median value.
Parameters
l list of numeric values
Returns
The median value
Definition at line 45 of file numpy.py.
References builtins.len(), mean(), and builtins.sorted().
 def median(l):
     sl = sorted(l)
     lm = []
     if len(sl) % 2 == 1:
         lm = [sl[(len(sl)-1)/2]]
     else:
         lm = [sl[len(sl)/2-1], sl[len(sl)/2]]
     return mean(lm)
def numpy.mode (l)
Mode value.
Parameters
l list of numeric values
Returns
The mode value
Definition at line 61 of file numpy.py.
 def mode(l):
     hist={}
     for x in l:
         if x in hist:
             hist[x] += 1
         else:
             hist[x] = 1
     mx=l[0]
     mh=hist[mx]
     for x in hist:
         h = hist[x]
         if h > mh:
             mh = h
             mx = x
     return mx
def numpy.var (l)
Variance.
Parameters
l list of numeric values
Returns
The variance
Definition at line 84 of file numpy.py.
References builtins.len(), and mean().
Referenced by std().
 def var(l):
     m = mean(l)
     vs = 0.0
     for x in l:
         vs += (x-m)*(x-m)
     return vs / len(l)
def numpy.std (l)
Standard deviation.
Parameters
l list of numeric values
Returns
The standard deviation
Definition at line 98 of file numpy.py.
References math.sqrt(), and var().
 def std(l):
     return math.sqrt( var(l) )
def numpy.prod (items)
Product of elements in a list.
Parameters
items The list of values
Returns
The product
Definition at line 108 of file numpy.py.
References builtins.reduce().
 def prod( items ):
     return reduce( lambda x, y: x*y, items )