ScriptML Python API: time Namespace Reference
time Namespace Reference
ScriptML standard time module.
Functions
def time ()
Get the time since the epoch in seconds.
def integer_time ()
Get time since the epoch as two integers.
def sleep (secs)
Stop execution for a period of time.
Detailed Description
ScriptML standard time module.
See https://docs.python.org/2/library/time.html
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Function Documentation
def time.time ()
Get the time since the epoch in seconds.
Returns
time in seconds as a float - includes fractional part
Definition at line 18 of file time.py.
References builtins.float().
Referenced by ngimu.device.command(), and ngimu.device.read_setting().
 def time():
     l = ___GetTimeOfDay( args_list=___ArgsList(args=___ISeq() ), variadic_arg=___NULL() )
     secs = l[0]
     microsecs = l[1]
     return float(secs) + (float(microsecs)/1000000.0)
def time.integer_time ()
Get time since the epoch as two integers.
Returns
a tuple of the form (seconds, microseconds)
Note: this is a ScriptML extension designed to permit the user to avoid error due to loss of precision in floating point representations (double is just about capable of microsecond precision in 2017; float cannot even get to the nearest minute)
Definition at line 34 of file time.py.
 def integer_time():
     return ___GetTimeOfDay( args_list=___ArgsList(args=___ISeq() ), variadic_arg=___NULL() )
def time.sleep (secs)
Stop execution for a period of time.
Parameters
secs Time to wait in seconds
Fractional values may be used for the wait time, to obtain sub-second resolution down to an implementation-defined granularity.
Definition at line 46 of file time.py.
References builtins.int().
 def sleep( secs ):
     ___Sleep( seconds=int(secs), useconds=int(1000000*secs)%1000000 )