ScriptML Python API: builtins Namespace Reference
builtins Namespace Reference
ScriptML Python built-in definitions.
Functions
def len (l)
Get the number of elements in an iterable object.
def range (start, stop=0, step=1)
Create an iterable object spanning a range of values.
def bool (x=0)
Convert to boolean.
def int (x=0)
Convert to integer.
def float (x=0.0)
Convert to floating-point.
def list (seq=[])
Convert to list.
def tuple (seq=[])
Convert to tuple.
def str (s="")
Convert to string.
def filter (operation, items)
create a list containing only the elements that the lambda evaluates as true
def map (operation, items)
create a list containing the results of applying the lambda
def reduce (operation, items)
Apply the lambda repeatedly to the list to obtain a single value.
def sum (items)
Sum of elements in a list.
def min (items)
Get smallest element in a list.
def max (items)
Get biggeest element in a list.
def any (items)
Determine if any elements of list are true.
def all (items)
Determine if all elements of list are true.
def round (x)
Round to nearest whole number.
def abs (x)
Obtain the absolute value.
def divmod (a, b)
Obtain quotient and remainder.
def sorted (l0)
Sort a list.
def exit (status=0)
Stop the script.
Variables
target
The None value for unassigned objects.
operand
type
The KeyboardInterrupt exception type (2 is SIGINT)
True = bool(1)
The boolean value true.
False = bool(0)
The boolean value false.
Detailed Description
ScriptML Python built-in definitions.
This file is automatically imported by ScriptML
Copyright (c) Open IO Labs Ltd 2016 All Rights Reserved
Function Documentation
def builtins.len (l)
Get the number of elements in an iterable object.
Parameters
l An iterable object
Returns
An integer containing the number of elements
Definition at line 16 of file builtins.py.
Referenced by numpy.mean(), numpy.median(), i2c.device.msg(), sorted(), i2c.device.transfer(), and numpy.var().
 def len(l):
     return ___Len(target=l)
def builtins.range (start, stop = 0, step = 1)
Create an iterable object spanning a range of values.
Parameters
start The value of the first element
stop The value of the last element, or an infinite range if omitted
step The difference between neighbouring elements, or one if omitted
Returns
An immutable iterable object spanning the required range
Definition at line 25 of file builtins.py.
Referenced by i2c_regmap.i2c_regmap.read(), i2c.device.read(), i2c.device.smbus_read_block_data(), i2c.device.smbus_write_block_data(), sorted(), and i2c_regmap.i2c_regmap.write().
 def range(start, stop=0, step=1):
     if stop==0 and step==1: # TODO use None as default values
         return ___RangeExpr(start=0, stop=start, step=1)
     else:
         return ___RangeExpr(start=start, stop=stop, step=step)
def builtins.bool (x = 0)
Convert to boolean.
Parameters
x The object to convert
Returns
A boolean value
Definition at line 35 of file builtins.py.
Referenced by lwm2m.create_IPSO_Actuation(), lwm2m.create_IPSO_Digital_Input(), lwm2m.create_IPSO_Digital_Output(), lwm2m.create_IPSO_Light_Control(), lwm2m.create_IPSO_Power_Control(), lwm2m.create_IPSO_Presence(), and lwm2m.create_OpenIO_Motor_Control().
 def bool(x=0):
     return ___Convert(target=x, type=___BoolType())
def builtins.int (x = 0)
Convert to integer.
Parameters
x The object to convert
Returns
An integer value
Definition at line 42 of file builtins.py.
Referenced by lwm2m.create_IPSO_Light_Control(), lwm2m.create_OpenIO_I2C_Interface(), lwm2m.create_OpenIO_Motor_Control(), lwm2m.create_OpenIO_SPI_Interface(), lwm2m.create_OpenIO_UART_Interface(), gpio.device.get_level(), serial.Serial.read(), gpio.device.set_level(), and time.sleep().
 def int(x=0):
     return ___Convert(target=x, type=___IntegerType())
def builtins.float (x = 0.0)
Convert to floating-point.
Parameters
x The object to convert
Returns
A floating-point value
Definition at line 49 of file builtins.py.
Referenced by lwm2m.create_IPSO_Accelerometer(), lwm2m.create_IPSO_Altitude(), lwm2m.create_IPSO_Analog_Input(), lwm2m.create_IPSO_Analog_Output(), lwm2m.create_IPSO_Barometer(), lwm2m.create_IPSO_Current(), lwm2m.create_IPSO_Depth(), lwm2m.create_IPSO_Frequency(), lwm2m.create_IPSO_Generic_Sensor(), lwm2m.create_IPSO_Gyrometer(), lwm2m.create_IPSO_Humidity(), lwm2m.create_IPSO_Illuminance(), lwm2m.create_IPSO_Load(), lwm2m.create_IPSO_Loudness(), lwm2m.create_IPSO_Magnetometer(), lwm2m.create_IPSO_Percentage(), lwm2m.create_IPSO_Power_Measurement(), lwm2m.create_IPSO_Pressure(), lwm2m.create_IPSO_Set_Point(), lwm2m.create_IPSO_Temperature(), lwm2m.create_IPSO_Voltage(), numpy.mean(), and time.time().
 def float(x=0.0):
     return ___Convert(target=x, type=___FloatType())
def builtins.list (seq = [])
Convert to list.
Parameters
x The object to convert
Returns
A list object
Definition at line 56 of file builtins.py.
 def list(seq=[]):
     return ___Convert(target=seq, type=___ListType(element_type=___NULL(), size=___NULL()))
def builtins.tuple (seq = [])
Convert to tuple.
Parameters
x The object to convert
Returns
A tuple object
Definition at line 63 of file builtins.py.
 def tuple(seq=[]):
     return ___Convert(target=seq, type=___TupleType(element_type=___NULL(), size=___NULL()))
def builtins.str (s = "")
Convert to string.
Parameters
x The object to convert
Returns
A string object
Definition at line 70 of file builtins.py.
Referenced by gpio.device.__init__(), lwm2m.create_IPSO_Accelerometer(), lwm2m.create_IPSO_Altitude(), lwm2m.create_IPSO_Barometer(), lwm2m.create_IPSO_Current(), lwm2m.create_IPSO_Depth(), lwm2m.create_IPSO_Frequency(), lwm2m.create_IPSO_Generic_Sensor(), lwm2m.create_IPSO_Gyrometer(), lwm2m.create_IPSO_Humidity(), lwm2m.create_IPSO_Illuminance(), lwm2m.create_IPSO_Load(), lwm2m.create_IPSO_Loudness(), lwm2m.create_IPSO_Magnetometer(), lwm2m.create_IPSO_Percentage(), lwm2m.create_IPSO_Pressure(), lwm2m.create_IPSO_Set_Point(), lwm2m.create_IPSO_Temperature(), lwm2m.create_IPSO_Voltage(), lwm2m.create_OpenIO_Camera_Interface(), lwm2m.create_OpenIO_Clientpushed_text_object(), lwm2m.create_OpenIO_Surface_Plotter(), and gpio.device.set_level().
 def str(s=""):
     return ___Convert(target=s, type=___StringType(size=___NULL()))
def builtins.filter (operation, items)
create a list containing only the elements that the lambda evaluates as true
Parameters
operation A lambda or function that is called with elements of items and returns a boolean
items The items to process, iterable
Returns
A list containing only the elements that the lambda evaluates as true
Definition at line 87 of file builtins.py.
 def filter( operation, items ):
     return ___ApplyFilter(operation=operation, items=items)
def builtins.map (operation, items)
create a list containing the results of applying the lambda
Parameters
operation A lambda or function that is called with elements of items and returns some new value
items The items to process, iterable
Returns
A list made of of the returns from the lambda
Definition at line 95 of file builtins.py.
 def map( operation, items ):
     return ___ApplyMap(operation=operation, items=items)
def builtins.reduce (operation, items)
Apply the lambda repeatedly to the list to obtain a single value.
Parameters
operation A lambda or function that is called with elements of items and returns some new value
items The items to process, iterable
Returns
A single value resulting from applying the lambda repeatedly
Definition at line 103 of file builtins.py.
Referenced by all(), any(), max(), min(), numpy.prod(), and sum().
 def reduce( operation, items ):
     return ___ApplyReduce(operation=operation, items=items)
def builtins.sum (items)
Sum of elements in a list.
Parameters
items The list to sum
Returns
The total value
Definition at line 110 of file builtins.py.
References reduce().
Referenced by numpy.mean().
 def sum( items ):
     return reduce( lambda x, y: x+y, items )
def builtins.min (items)
Get smallest element in a list.
Parameters
items The list to test
Returns
The smallest value
Definition at line 117 of file builtins.py.
References reduce().
 def min( items ):
     return reduce( lambda x, y: x if x<y else y, items )
def builtins.max (items)
Get biggeest element in a list.
Parameters
items The list to test
Returns
The biggest value
Definition at line 124 of file builtins.py.
References reduce().
 def max( items ):
     return reduce( lambda x, y: x if x>y else y, items )
def builtins.any (items)
Determine if any elements of list are true.
Parameters
items The list to test
Returns
True if any are true
Definition at line 131 of file builtins.py.
References reduce().
 def any( items ):
     return reduce( lambda x, y: x or y, items )
def builtins.all (items)
Determine if all elements of list are true.
Parameters
items The list to test
Returns
True if all are true
Definition at line 138 of file builtins.py.
References reduce().
 def all( items ):
     return reduce( lambda x, y: x and y, items )
def builtins.round (x)
Round to nearest whole number.
Parameters
value The value to round
Returns
Nearest whole number to value
Definition at line 145 of file builtins.py.
 def round( x ):
     return ___UnaryOperation( poperator=___Round(), operand=x )
def builtins.abs (x)
Obtain the absolute value.
Parameters
value The value
Returns
Non-negative number with same absolute value as value
Definition at line 152 of file builtins.py.
 def abs( x ):
     return ___UnaryOperation( poperator=___Abs(), operand=x )
def builtins.divmod (a, b)
Obtain quotient and remainder.
Note: this version only correct for integer arguments
Parameters
a Numerator
b denominator
Returns
A list containing: quotient, remainder
Definition at line 162 of file builtins.py.
 def divmod( a, b ):
     return (a // b, a % b)
 # Note: You can overwrite these objects in Python.
def builtins.sorted (l0)
Sort a list.
Parameters
l0 List to sort
Returns
Sorted list, ascending
Definition at line 179 of file builtins.py.
References len(), and range().
Referenced by numpy.median().
 def sorted(l0):
     l = []
     for x in l0:
         l += [x]
     nl = []
     while len(l) > 0:
         mi=0
         m=l[0]
         for i in range(1, len(l)):
             if l[i] < m:
                 m = l[i]
                 mi = i
         l = l[0:mi] + l[mi+1:len(l)]
         nl = nl + [m]
     return nl
def builtins.exit (status = 0)
Stop the script.
Parameters
status The system status code, where 0 indicates success
Definition at line 198 of file builtins.py.
 def exit( status=0 ):
     ___Exit( value=status );
Variable Documentation
builtins.type
The KeyboardInterrupt exception type (2 is SIGINT)
The ExternalError exception type.
Definition at line 77 of file builtins.py.